blizzardman_objects_set:
;id
	.BYTE $00
	.BYTE $00
	.BYTE $00
	.BYTE $01
	.BYTE $01
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $07
	.BYTE $07
	.BYTE $07
	.BYTE $08
	.BYTE $09
	.BYTE $09
	.BYTE $0A
	.BYTE $0A
	.BYTE $0A
	.BYTE $0A
	.BYTE $0A
	.BYTE $0B
	.BYTE $0B
	.BYTE $0B
	.BYTE $0B
	.BYTE $0B
	.BYTE $0C
	.BYTE $0C
	.BYTE $0D
	.BYTE $0E
	.BYTE $0F
	.BYTE $10
	.BYTE $10
	.BYTE $11
	.BYTE $11
	.BYTE $11
	.BYTE $12
	.BYTE $12
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $14
	.BYTE $14
	.BYTE $14
	.BYTE $15
	.BYTE $15
	.BYTE $16
	.BYTE $16
	.BYTE $16
	.BYTE $16
	.BYTE $16
	.BYTE $17
	.BYTE $18
	.BYTE -1

;x
	.BYTE $40
	.BYTE $98
	.BYTE $9F
	.BYTE $6F
	.BYTE $90
	.BYTE $0F
	.BYTE $2F
	.BYTE $87
	.BYTE $AD
	.BYTE $F0
	.BYTE $5A
	.BYTE $74
	.BYTE $87
	.BYTE $C1
	.BYTE $EC
	.BYTE $06
	.BYTE $B6
	.BYTE $D0
	.BYTE $06
	.BYTE $54
	.BYTE $A9
	.BYTE $B7
	.BYTE $C0
	.BYTE $4F
	.BYTE $80
	.BYTE $87
	.BYTE $40
	.BYTE $4A
	.BYTE $EF
	.BYTE $96
	.BYTE $38
	.BYTE $50
	.BYTE $37
	.BYTE $62
	.BYTE $77
	.BYTE $B3
	.BYTE $D7
	.BYTE $13
	.BYTE $31
	.BYTE $80
	.BYTE $B6
	.BYTE $B7
	.BYTE $10
	.BYTE $3A
	.BYTE $80
	.BYTE $40
	.BYTE $50
	.BYTE $10
	.BYTE $6F
	.BYTE $CC
	.BYTE $D4
	.BYTE $DC
	.BYTE $10
	.BYTE $EE
	.BYTE $24
	.BYTE $59
	.BYTE $90
	.BYTE $C0
	.BYTE $C7
	.BYTE $4F
	.BYTE $80
	.BYTE $90
	.BYTE $40
	.BYTE $DA
	.BYTE $68
	.BYTE $A8
	.BYTE $C0
	.BYTE $D4
	.BYTE $D7
	.BYTE $C0
	.BYTE $80
	.BYTE -1

;y
	.BYTE $00
	.BYTE $FA
	.BYTE $FB
	.BYTE $93
	.BYTE $AB
	.BYTE $59
	.BYTE $8E
	.BYTE $84
	.BYTE $54
	.BYTE $B7
	.BYTE $98
	.BYTE $62
	.BYTE $78
	.BYTE $5D
	.BYTE $89
	.BYTE $6A
	.BYTE $33
	.BYTE $6D
	.BYTE $36
	.BYTE $31
	.BYTE $B5
	.BYTE $6D
	.BYTE $01
	.BYTE $77
	.BYTE $02
	.BYTE $75
	.BYTE $03
	.BYTE $74
	.BYTE $B4
	.BYTE $97
	.BYTE $7F
	.BYTE $57
	.BYTE $B4
	.BYTE $7F
	.BYTE $94
	.BYTE $5E
	.BYTE $54
	.BYTE $3F
	.BYTE $57
	.BYTE $01
	.BYTE $3F
	.BYTE $54
	.BYTE $04
	.BYTE $67
	.BYTE $05
	.BYTE $00
	.BYTE $4F
	.BYTE $4F
	.BYTE $70
	.BYTE $73
	.BYTE $73
	.BYTE $73
	.BYTE $73
	.BYTE $A2
	.BYTE $97
	.BYTE $8C
	.BYTE $7D
	.BYTE $06
	.BYTE $67
	.BYTE $92
	.BYTE $07
	.BYTE $6B
	.BYTE $19
	.BYTE $67
	.BYTE $93
	.BYTE $AA
	.BYTE $1A
	.BYTE $56
	.BYTE $6A
	.BYTE $0B
	.BYTE $0A
	.BYTE -1

;objects
	.BYTE objects_scrolling
	.BYTE objects_au_au
	.BYTE objects_count_bomb_up
	.BYTE objects_au_au
	.BYTE objects_count_bomb_up
	.BYTE objects_large_weapon_capsule
	.BYTE objects_propeller_eye
	.BYTE objects_au_au
	.BYTE objects_au_au
	.BYTE objects_1up
	.BYTE objects_count_bomb_up
	.BYTE objects_propeller_eye
	.BYTE objects_count_bomb_up
	.BYTE objects_count_bomb_up
	.BYTE objects_propeller_eye
	.BYTE objects_count_bomb_up
	.BYTE objects_count_bomb_left
	.BYTE objects_teck
	.BYTE objects_large_life_capsule
	.BYTE objects_count_bomb_left
	.BYTE objects_propeller_eye
	.BYTE objects_teck
	.BYTE objects_scrolling
	.BYTE objects_1up
	.BYTE objects_scrolling
	.BYTE objects_propeller_eye
	.BYTE objects_scrolling
	.BYTE objects_curlinger
	.BYTE objects_curlinger
	.BYTE objects_shield_attacker_gtr
	.BYTE objects_shield_attacker_gtr
	.BYTE objects_e_tank
	.BYTE objects_curlinger
	.BYTE objects_shield_attacker_gtr
	.BYTE objects_curlinger
	.BYTE objects_shield_attacker_gtr
	.BYTE objects_curlinger
	.BYTE objects_shield_attacker_gtr
	.BYTE objects_large_life_capsule
	.BYTE objects_scrolling
	.BYTE objects_shield_attacker_gtr
	.BYTE objects_curlinger
	.BYTE objects_scrolling
	.BYTE objects_squidon
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_cannon_joe_right
	.BYTE objects_cannon_joe_left
	.BYTE objects_cannon_joe_left
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_e_tank
	.BYTE objects_count_bomb_up
	.BYTE objects_count_bomb_up
	.BYTE objects_count_bomb_up
	.BYTE objects_count_bomb_up
	.BYTE objects_scrolling
	.BYTE objects_count_bomb_up
	.BYTE objects_count_bomb_up
	.BYTE objects_scrolling
	.BYTE objects_count_bomb_up
	.BYTE objects_scrolling
	.BYTE objects_squidon
	.BYTE objects_count_bomb_up
	.BYTE objects_count_bomb_up
	.BYTE objects_scrolling
	.BYTE objects_count_bomb_left
	.BYTE objects_count_bomb_up
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE -1
blizzardman_objects_set_end:
