;track ids
.ENUM
	track_windman
	track_blizzardman
	track_yamatoman
	track_flameman
	track_plantman
	track_centaurman
	track_tomahawkman
	track_knightman
	track_ending
	track_x
	track_staff_roll
	track_wily
	track_boss_fighting
	track_opening
	track_capcom
	track_stage_select
	track_boss_show
	track_x_castle
	track_wily_castle
	track_boss_defeated
	track_game_over
	track_password
	track_get_weapon
	track_wily_defeated
	track_wily_fighting
	track_title
	track_nothing
	track_ending_blizzardman
	track_ending_centaurman
	track_ending_flameman
	track_ending_knightman
	track_ending_plantman
	track_ending_tomahawkman
	track_ending_windman
	track_ending_yamatoman
	track_mega_buster
	track_landing
	track_megaman_hit
	track_death
	track_enemy_immune
	track_28
	track_charge_shot_full_charging
	track_adapter
	track_power_adapter_half_charge_shot
	track_power_adapter_destroy_block
	track_jet
	track_beat
	track_1up
	track_door
	track_refill
	track_select
	track_confirm
	track_open_menu
	track_enemy_hit
	track_explosion
	track_teleport_in
	track_error
	track_protoman_whistle
	track_teleport_out
	track_appearing_block
	track_jump_into_water
	track_3d
	track_power_adapter_destroy_ice
	track_3f
	track_submarine_up
	track_submarine_down
	track_enemy_bullet
	track_brown
	track_colton
	track_fire_telly
	track_teck
	track_curlinger
	track_heli_buton
	track_power_slam_up
	track_power_slam_down
	track_power_slam_landing
	track_batabattan_landing
	track_4d
	track_count_bomb
	track_fan
	track_oil
	track_51
	track_flameman_fire_pillar
	track_heli_buton_appear
	track_spring
	track_spike_ceiling_up
	track_spike_ceiling_down
	track_spike_ceiling_end
	track_centaur_flash
	track_blizzard_attack
	track_blizzardman_rolling
	track_blizzardman_rollout
	track_centaurman_disappear
	track_centaurman_appear
	track_centaurman_running
	track_get_weapon_energy
	track_wily_machine_6_stomp
	track_lighting
	track_route
	track_wily_ufo
	track_64
	track_get_weapon_blast
.ENDENUM
