tomahawkman_objects_set:
;id
	.BYTE $00
	.BYTE $01
	.BYTE $01
	.BYTE $01
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $03
	.BYTE $03
	.BYTE $04
	.BYTE $04
	.BYTE $05
	.BYTE $05
	.BYTE $06
	.BYTE $07
	.BYTE $07
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $09
	.BYTE $09
	.BYTE $0A
	.BYTE $0B
	.BYTE $0B
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0D
	.BYTE $0E
	.BYTE $0E
	.BYTE $0F
	.BYTE $0F
	.BYTE $10
	.BYTE $10
	.BYTE $11
	.BYTE $11
	.BYTE $11
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $13
	.BYTE $14
	.BYTE $14
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $16
	.BYTE $17
	.BYTE $18
	.BYTE $18
	.BYTE $1A
	.BYTE $1A
	.BYTE $1B
	.BYTE $1B
	.BYTE $1B
	.BYTE $1B
	.BYTE $1B
	.BYTE $1C
	.BYTE $1C
	.BYTE $1D
	.BYTE $1D
	.BYTE $1D
	.BYTE $1E
	.BYTE $1F
	.BYTE -1

;x
	.BYTE $40
	.BYTE $50
	.BYTE $D1
	.BYTE $F0
	.BYTE $50
	.BYTE $70
	.BYTE $B1
	.BYTE $C0
	.BYTE $79
	.BYTE $80
	.BYTE $80
	.BYTE $93
	.BYTE $90
	.BYTE $A8
	.BYTE $40
	.BYTE $47
	.BYTE $D0
	.BYTE $77
	.BYTE $B3
	.BYTE $F0
	.BYTE $29
	.BYTE $80
	.BYTE $40
	.BYTE $95
	.BYTE $D4
	.BYTE $48
	.BYTE $58
	.BYTE $73
	.BYTE $C0
	.BYTE $D4
	.BYTE $C0
	.BYTE $4A
	.BYTE $80
	.BYTE $40
	.BYTE $B0
	.BYTE $80
	.BYTE $88
	.BYTE $40
	.BYTE $94
	.BYTE $D8
	.BYTE $54
	.BYTE $73
	.BYTE $C0
	.BYTE $CF
	.BYTE $80
	.BYTE $40
	.BYTE $D0
	.BYTE $10
	.BYTE $54
	.BYTE $90
	.BYTE $C0
	.BYTE $C1
	.BYTE $E3
	.BYTE $80
	.BYTE $80
	.BYTE $40
	.BYTE $F6
	.BYTE $32
	.BYTE $B8
	.BYTE $10
	.BYTE $89
	.BYTE $A1
	.BYTE $B7
	.BYTE $C0
	.BYTE $6F
	.BYTE $80
	.BYTE $6F
	.BYTE $B0
	.BYTE $C0
	.BYTE $80
	.BYTE $80
	.BYTE -1

;y
	.BYTE $29
	.BYTE $8F
	.BYTE $8F
	.BYTE $9B
	.BYTE $6F
	.BYTE $77
	.BYTE $4F
	.BYTE $01
	.BYTE $6F
	.BYTE $22
	.BYTE $36
	.BYTE $8F
	.BYTE $23
	.BYTE $73
	.BYTE $00
	.BYTE $6F
	.BYTE $6F
	.BYTE $95
	.BYTE $B5
	.BYTE $0D
	.BYTE $73
	.BYTE $07
	.BYTE $21
	.BYTE $6F
	.BYTE $4F
	.BYTE $9B
	.BYTE $9B
	.BYTE $4F
	.BYTE $2B
	.BYTE $AF
	.BYTE $02
	.BYTE $93
	.BYTE $22
	.BYTE $36
	.BYTE $80
	.BYTE $23
	.BYTE $73
	.BYTE $00
	.BYTE $AF
	.BYTE $2D
	.BYTE $AF
	.BYTE $2D
	.BYTE $0D
	.BYTE $8F
	.BYTE $27
	.BYTE $08
	.BYTE $4F
	.BYTE $6F
	.BYTE $36
	.BYTE $6F
	.BYTE $09
	.BYTE $1F
	.BYTE $8F
	.BYTE $4E
	.BYTE $0A
	.BYTE $24
	.BYTE $99
	.BYTE $A0
	.BYTE $86
	.BYTE $A4
	.BYTE $97
	.BYTE $97
	.BYTE $99
	.BYTE $25
	.BYTE $00
	.BYTE $28
	.BYTE $97
	.BYTE $55
	.BYTE $1A
	.BYTE $4E
	.BYTE $0A
	.BYTE -1

;objects
	.BYTE objects_scrolling
	.BYTE objects_colton
	.BYTE objects_colton
	.BYTE objects_small_life_capsule
	.BYTE objects_colton
	.BYTE objects_e_tank
	.BYTE objects_colton
	.BYTE objects_scrolling
	.BYTE objects_colton
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_shield_attacker_gtr
	.BYTE objects_scrolling
	.BYTE objects_metall_potton
	.BYTE objects_scrolling
	.BYTE objects_molier
	.BYTE objects_molier
	.BYTE objects_metall
	.BYTE objects_metall
	.BYTE objects_scrolling
	.BYTE objects_eddie
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_skull_walker
	.BYTE objects_skull_walker
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_skull_walker
	.BYTE objects_scrolling
	.BYTE objects_skull_walker
	.BYTE objects_scrolling
	.BYTE objects_twin_roader
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_power_slam
	.BYTE objects_scrolling
	.BYTE objects_metall_potton
	.BYTE objects_scrolling
	.BYTE objects_shield_attacker_gtr
	.BYTE objects_teck
	.BYTE objects_shield_attacker_gtr
	.BYTE objects_teck
	.BYTE objects_scrolling
	.BYTE objects_shield_attacker_gtr
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_skull_walker
	.BYTE objects_skull_walker
	.BYTE objects_hotchkissn
	.BYTE objects_skull_walker
	.BYTE objects_scrolling
	.BYTE objects_hotchkissn
	.BYTE objects_skull_walker
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_jet_platform
	.BYTE objects_jet_platform
	.BYTE objects_jet_platform
	.BYTE objects_jet_platform
	.BYTE objects_large_life_capsule
	.BYTE objects_e_tank
	.BYTE objects_large_weapon_capsule
	.BYTE objects_scrolling
	.BYTE objects_protoman_give_energy_balancer
	.BYTE objects_scrolling
	.BYTE objects_large_life_capsule
	.BYTE objects_spike_platform
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE -1
tomahawkman_objects_set_end:
