knightman_objects_set:
;id
	.BYTE $00
	.BYTE $01
	.BYTE $01
	.BYTE $01
	.BYTE $02
	.BYTE $02
	.BYTE $03
	.BYTE $03
	.BYTE $05
	.BYTE $06
	.BYTE $06
	.BYTE $07
	.BYTE $07
	.BYTE $08
	.BYTE $08
	.BYTE $09
	.BYTE $0A
	.BYTE $0B
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0D
	.BYTE $0D
	.BYTE $0D
	.BYTE $0D
	.BYTE $0E
	.BYTE $0E
	.BYTE $0F
	.BYTE $10
	.BYTE $10
	.BYTE $10
	.BYTE $10
	.BYTE $11
	.BYTE $11
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $14
	.BYTE $14
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $16
	.BYTE $17
	.BYTE $18
	.BYTE $18
	.BYTE $19
	.BYTE $1A
	.BYTE -1

;x
	.BYTE $40
	.BYTE $69
	.BYTE $80
	.BYTE $9F
	.BYTE $40
	.BYTE $D8
	.BYTE $40
	.BYTE $F0
	.BYTE $BF
	.BYTE $31
	.BYTE $C0
	.BYTE $80
	.BYTE $B2
	.BYTE $2B
	.BYTE $80
	.BYTE $80
	.BYTE $40
	.BYTE $80
	.BYTE $10
	.BYTE $97
	.BYTE $F8
	.BYTE $28
	.BYTE $36
	.BYTE $C0
	.BYTE $D4
	.BYTE $2B
	.BYTE $80
	.BYTE $40
	.BYTE $17
	.BYTE $77
	.BYTE $C0
	.BYTE $D0
	.BYTE $2C
	.BYTE $80
	.BYTE $40
	.BYTE $80
	.BYTE $EA
	.BYTE $00
	.BYTE $16
	.BYTE $17
	.BYTE $56
	.BYTE $96
	.BYTE $D6
	.BYTE $3E
	.BYTE $95
	.BYTE $35
	.BYTE $B6
	.BYTE $C0
	.BYTE $80
	.BYTE $80
	.BYTE $40
	.BYTE $76
	.BYTE $80
	.BYTE $80
	.BYTE -1

;y
	.BYTE $42
	.BYTE $53
	.BYTE $02
	.BYTE $97
	.BYTE $36
	.BYTE $B3
	.BYTE $3F
	.BYTE $AF
	.BYTE $AF
	.BYTE $AF
	.BYTE $2B
	.BYTE $07
	.BYTE $93
	.BYTE $AE
	.BYTE $43
	.BYTE $43
	.BYTE $08
	.BYTE $51
	.BYTE $53
	.BYTE $93
	.BYTE $63
	.BYTE $AB
	.BYTE $AB
	.BYTE $0D
	.BYTE $83
	.BYTE $93
	.BYTE $07
	.BYTE $08
	.BYTE $93
	.BYTE $83
	.BYTE $40
	.BYTE $17
	.BYTE $2C
	.BYTE $68
	.BYTE $03
	.BYTE $F2
	.BYTE $5B
	.BYTE $5B
	.BYTE $74
	.BYTE $5B
	.BYTE $24
	.BYTE $94
	.BYTE $C8
	.BYTE $B8
	.BYTE $33
	.BYTE $97
	.BYTE $77
	.BYTE $41
	.BYTE $44
	.BYTE $0A
	.BYTE $1A
	.BYTE $97
	.BYTE $44
	.BYTE $0A
	.BYTE -1

;objects
	.BYTE objects_scrolling
	.BYTE objects_twin_roader
	.BYTE objects_scrolling
	.BYTE objects_1up
	.BYTE objects_scrolling
	.BYTE objects_brown
	.BYTE objects_scrolling
	.BYTE objects_molier
	.BYTE objects_molier
	.BYTE objects_molier
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_tatebo
	.BYTE objects_skull_walker
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_brown
	.BYTE objects_brown
	.BYTE objects_brown
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_scrolling
	.BYTE objects_brown
	.BYTE objects_eddie
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_brain_break
	.BYTE objects_brain_break
	.BYTE objects_scrolling
	.BYTE objects_e_tank
	.BYTE objects_sw_525
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_bumper_up
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_cyber_gabyoall_top
	.BYTE objects_small_life_capsule
	.BYTE objects_cyber_gabyoall_top
	.BYTE objects_cyber_gabyoall_top
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_cyber_gabyoall_top
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE -1
knightman_objects_set_end:
