x3_objects_set:
;id
	.BYTE $00
	.BYTE $00
	.BYTE $00
	.BYTE $00
	.BYTE $01
	.BYTE $01
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $07
	.BYTE $07
	.BYTE $07
	.BYTE $07
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $09
	.BYTE $09
	.BYTE $09
	.BYTE $09
	.BYTE $09
	.BYTE $09
	.BYTE $0A
	.BYTE $0A
	.BYTE $0A
	.BYTE $0B
	.BYTE $0B
	.BYTE $0B
	.BYTE $0B
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0D
	.BYTE $0D
	.BYTE $0D
	.BYTE $0D
	.BYTE $0D
	.BYTE $0D
	.BYTE $0E
	.BYTE $0E
	.BYTE $0E
	.BYTE $0E
	.BYTE $0E
	.BYTE $0E
	.BYTE $0E
	.BYTE $0F
	.BYTE $0F
	.BYTE $0F
	.BYTE $0F
	.BYTE $0F
	.BYTE $0F
	.BYTE $0F
	.BYTE $0F
	.BYTE $0F
	.BYTE $10
	.BYTE $11
	.BYTE -1

;x
	.BYTE $32
	.BYTE $80
	.BYTE $84
	.BYTE $D1
	.BYTE $72
	.BYTE $80
	.BYTE $3B
	.BYTE $40
	.BYTE $A4
	.BYTE $BB
	.BYTE $CF
	.BYTE $30
	.BYTE $99
	.BYTE $AB
	.BYTE $D3
	.BYTE $F2
	.BYTE $0C
	.BYTE $34
	.BYTE $54
	.BYTE $6C
	.BYTE $94
	.BYTE $B5
	.BYTE $EF
	.BYTE $4B
	.BYTE $74
	.BYTE $76
	.BYTE $AC
	.BYTE $D4
	.BYTE $E9
	.BYTE $EC
	.BYTE $14
	.BYTE $25
	.BYTE $53
	.BYTE $F0
	.BYTE $10
	.BYTE $47
	.BYTE $72
	.BYTE $C0
	.BYTE $40
	.BYTE $8F
	.BYTE $D5
	.BYTE $14
	.BYTE $35
	.BYTE $51
	.BYTE $81
	.BYTE $C0
	.BYTE $D7
	.BYTE $4E
	.BYTE $7B
	.BYTE $80
	.BYTE $80
	.BYTE $8A
	.BYTE $95
	.BYTE $D7
	.BYTE $2C
	.BYTE $54
	.BYTE $80
	.BYTE $A3
	.BYTE $AC
	.BYTE $D4
	.BYTE $E4
	.BYTE $2F
	.BYTE $79
	.BYTE $90
	.BYTE $9B
	.BYTE $B1
	.BYTE $EC
	.BYTE $14
	.BYTE $4C
	.BYTE $4F
	.BYTE $74
	.BYTE $80
	.BYTE $AF
	.BYTE $EB
	.BYTE $13
	.BYTE $26
	.BYTE $4B
	.BYTE $58
	.BYTE $73
	.BYTE $98
	.BYTE $AC
	.BYTE $C0
	.BYTE $DD
	.BYTE $80
	.BYTE $80
	.BYTE -1

;y
	.BYTE $B7
	.BYTE $58
	.BYTE $B7
	.BYTE $B7
	.BYTE $4C
	.BYTE $07
	.BYTE $97
	.BYTE $08
	.BYTE $5B
	.BYTE $46
	.BYTE $31
	.BYTE $79
	.BYTE $4A
	.BYTE $00
	.BYTE $01
	.BYTE $2C
	.BYTE $22
	.BYTE $23
	.BYTE $2C
	.BYTE $44
	.BYTE $45
	.BYTE $43
	.BYTE $69
	.BYTE $66
	.BYTE $67
	.BYTE $55
	.BYTE $88
	.BYTE $89
	.BYTE $2D
	.BYTE $AA
	.BYTE $AB
	.BYTE $4A
	.BYTE $67
	.BYTE $89
	.BYTE $59
	.BYTE $4A
	.BYTE $4A
	.BYTE $2B
	.BYTE $7D
	.BYTE $BB
	.BYTE $B7
	.BYTE $41
	.BYTE $B7
	.BYTE $B7
	.BYTE $37
	.BYTE $0D
	.BYTE $B7
	.BYTE $9B
	.BYTE $3B
	.BYTE $07
	.BYTE $08
	.BYTE $7B
	.BYTE $7B
	.BYTE $29
	.BYTE $0C
	.BYTE $0D
	.BYTE $62
	.BYTE $1B
	.BYTE $2E
	.BYTE $2F
	.BYTE $57
	.BYTE $98
	.BYTE $46
	.BYTE $69
	.BYTE $1B
	.BYTE $59
	.BYTE $50
	.BYTE $51
	.BYTE $72
	.BYTE $2A
	.BYTE $73
	.BYTE $61
	.BYTE $56
	.BYTE $94
	.BYTE $95
	.BYTE $6B
	.BYTE $B6
	.BYTE $8F
	.BYTE $B7
	.BYTE $50
	.BYTE $99
	.BYTE $09
	.BYTE $6A
	.BYTE $60
	.BYTE $6E
	.BYTE -1

;objects
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_scrolling
	.BYTE objects_1up
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_ben_k
	.BYTE objects_scrolling
	.BYTE objects_e_tank
	.BYTE objects_scrolling
	.BYTE objects_fire_telly
	.BYTE objects_fire_telly
	.BYTE objects_fire_telly
	.BYTE objects_pooker
	.BYTE objects_fire_telly
	.BYTE objects_pressure_block
	.BYTE objects_pressure_block
	.BYTE objects_fire_telly
	.BYTE objects_pressure_block
	.BYTE objects_pressure_block
	.BYTE objects_fire_telly
	.BYTE objects_pressure_block
	.BYTE objects_pressure_block
	.BYTE objects_fire_telly
	.BYTE objects_pooker
	.BYTE objects_pressure_block
	.BYTE objects_pressure_block
	.BYTE objects_fire_telly
	.BYTE objects_pressure_block
	.BYTE objects_pressure_block
	.BYTE objects_fire_telly
	.BYTE objects_pressure_block
	.BYTE objects_pressure_block
	.BYTE objects_fire_telly
	.BYTE objects_fire_telly
	.BYTE objects_pooker
	.BYTE objects_pooker
	.BYTE objects_fire_telly
	.BYTE objects_fire_telly
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_small_life_capsule
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_cannopeller
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_e_tank
	.BYTE objects_cannopeller
	.BYTE objects_scrolling
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_cannopeller
	.BYTE objects_cannopeller
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_fire_telly
	.BYTE objects_pressure_block
	.BYTE objects_pressure_block
	.BYTE objects_scrolling
	.BYTE objects_fire_telly
	.BYTE objects_pressure_block
	.BYTE objects_pressure_block
	.BYTE objects_fire_telly
	.BYTE objects_pooker
	.BYTE objects_fire_telly
	.BYTE objects_pooker
	.BYTE objects_fire_telly
	.BYTE objects_pooker
	.BYTE objects_pressure_block
	.BYTE objects_pressure_block
	.BYTE objects_pressure_block
	.BYTE objects_fire_telly
	.BYTE objects_pressure_block
	.BYTE objects_scrolling
	.BYTE objects_large_life_capsule
	.BYTE objects_pressure_block
	.BYTE objects_pressure_block
	.BYTE objects_fire_telly
	.BYTE objects_pressure_block
	.BYTE objects_fire_telly
	.BYTE objects_pressure_block
	.BYTE objects_fire_telly
	.BYTE objects_pooker
	.BYTE objects_scrolling
	.BYTE objects_fire_telly
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE -1
x3_objects_set_end:
