plantman_objects_set:
;id
	.BYTE $00
	.BYTE $00
	.BYTE $01
	.BYTE $01
	.BYTE $02
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $04
	.BYTE $04
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $07
	.BYTE $07
	.BYTE $08
	.BYTE $08
	.BYTE $09
	.BYTE $09
	.BYTE $09
	.BYTE $0A
	.BYTE $0A
	.BYTE $0A
	.BYTE $0B
	.BYTE $0B
	.BYTE $0B
	.BYTE $0B
	.BYTE $0B
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0D
	.BYTE $0D
	.BYTE $0D
	.BYTE $0D
	.BYTE $0D
	.BYTE $0E
	.BYTE $0E
	.BYTE $0F
	.BYTE $0F
	.BYTE $0F
	.BYTE $10
	.BYTE $10
	.BYTE $10
	.BYTE $10
	.BYTE $10
	.BYTE $10
	.BYTE $11
	.BYTE $11
	.BYTE $11
	.BYTE $11
	.BYTE $11
	.BYTE $11
	.BYTE $11
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $14
	.BYTE $14
	.BYTE $14
	.BYTE $14
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $16
	.BYTE $17
	.BYTE -1

;x
	.BYTE $40
	.BYTE $76
	.BYTE $75
	.BYTE $C4
	.BYTE $53
	.BYTE $12
	.BYTE $90
	.BYTE $93
	.BYTE $B0
	.BYTE $B8
	.BYTE $C0
	.BYTE $51
	.BYTE $80
	.BYTE $29
	.BYTE $40
	.BYTE $CA
	.BYTE $1A
	.BYTE $7F
	.BYTE $8F
	.BYTE $BD
	.BYTE $C0
	.BYTE $4E
	.BYTE $80
	.BYTE $70
	.BYTE $80
	.BYTE $80
	.BYTE $97
	.BYTE $A4
	.BYTE $4E
	.BYTE $7F
	.BYTE $B3
	.BYTE $3A
	.BYTE $46
	.BYTE $8B
	.BYTE $95
	.BYTE $9D
	.BYTE $1D
	.BYTE $30
	.BYTE $7C
	.BYTE $AE
	.BYTE $4E
	.BYTE $89
	.BYTE $95
	.BYTE $98
	.BYTE $C0
	.BYTE $6B
	.BYTE $80
	.BYTE $10
	.BYTE $11
	.BYTE $B0
	.BYTE $10
	.BYTE $1B
	.BYTE $20
	.BYTE $50
	.BYTE $D0
	.BYTE $EF
	.BYTE $2E
	.BYTE $40
	.BYTE $50
	.BYTE $6C
	.BYTE $A9
	.BYTE $AE
	.BYTE $F0
	.BYTE $25
	.BYTE $28
	.BYTE $48
	.BYTE $4C
	.BYTE $83
	.BYTE $88
	.BYTE $9F
	.BYTE $A8
	.BYTE $B9
	.BYTE $08
	.BYTE $2F
	.BYTE $48
	.BYTE $68
	.BYTE $7C
	.BYTE $8E
	.BYTE $29
	.BYTE $4E
	.BYTE $EC
	.BYTE $EF
	.BYTE $28
	.BYTE $4F
	.BYTE $6D
	.BYTE $6F
	.BYTE $88
	.BYTE $A8
	.BYTE $B1
	.BYTE $C0
	.BYTE $C8
	.BYTE $80
	.BYTE $80
	.BYTE -1

;y
	.BYTE $00
	.BYTE $F3
	.BYTE $56
	.BYTE $56
	.BYTE $A8
	.BYTE $68
	.BYTE $47
	.BYTE $77
	.BYTE $77
	.BYTE $F3
	.BYTE $0D
	.BYTE $6C
	.BYTE $07
	.BYTE $45
	.BYTE $08
	.BYTE $90
	.BYTE $6D
	.BYTE $19
	.BYTE $6F
	.BYTE $85
	.BYTE $1B
	.BYTE $53
	.BYTE $02
	.BYTE $1C
	.BYTE $F8
	.BYTE $00
	.BYTE $F9
	.BYTE $F4
	.BYTE $87
	.BYTE $55
	.BYTE $88
	.BYTE $4B
	.BYTE $4B
	.BYTE $2B
	.BYTE $2B
	.BYTE $87
	.BYTE $0F
	.BYTE $97
	.BYTE $F4
	.BYTE $57
	.BYTE $97
	.BYTE $99
	.BYTE $68
	.BYTE $99
	.BYTE $1D
	.BYTE $1C
	.BYTE $F8
	.BYTE $00
	.BYTE $F8
	.BYTE $70
	.BYTE $CC
	.BYTE $71
	.BYTE $1F
	.BYTE $CC
	.BYTE $CC
	.BYTE $70
	.BYTE $6D
	.BYTE $1E
	.BYTE $CC
	.BYTE $40
	.BYTE $5D
	.BYTE $29
	.BYTE $70
	.BYTE $64
	.BYTE $37
	.BYTE $17
	.BYTE $75
	.BYTE $76
	.BYTE $57
	.BYTE $CA
	.BYTE $36
	.BYTE $50
	.BYTE $16
	.BYTE $47
	.BYTE $16
	.BYTE $37
	.BYTE $82
	.BYTE $CC
	.BYTE $5C
	.BYTE $CC
	.BYTE $81
	.BYTE $9F
	.BYTE $16
	.BYTE $9F
	.BYTE $74
	.BYTE $CC
	.BYTE $37
	.BYTE $17
	.BYTE $90
	.BYTE $09
	.BYTE $37
	.BYTE $0B
	.BYTE $0A
	.BYTE -1

;objects
	.BYTE objects_scrolling
	.BYTE objects_leaf
	.BYTE objects_heli_buton
	.BYTE objects_heli_buton
	.BYTE objects_batabattan
	.BYTE objects_batabattan
	.BYTE objects_batabattan
	.BYTE objects_large_life_capsule
	.BYTE objects_1up
	.BYTE objects_leaf
	.BYTE objects_scrolling
	.BYTE objects_power_slam
	.BYTE objects_scrolling
	.BYTE objects_propeller_eye
	.BYTE objects_scrolling
	.BYTE objects_tadahou
	.BYTE objects_propeller_eye
	.BYTE objects_propeller_eye
	.BYTE objects_tadahou
	.BYTE objects_propeller_eye
	.BYTE objects_scrolling
	.BYTE objects_eddie
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_gorilla_tank
	.BYTE objects_scrolling
	.BYTE objects_spring
	.BYTE objects_leaf
	.BYTE objects_batabattan
	.BYTE objects_heli_buton
	.BYTE objects_batabattan
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_small_weapon_capsule
	.BYTE objects_small_weapon_capsule
	.BYTE objects_batabattan
	.BYTE objects_heli_buton
	.BYTE objects_batabattan
	.BYTE objects_leaf
	.BYTE objects_batabattan
	.BYTE objects_batabattan
	.BYTE objects_large_weapon_capsule
	.BYTE objects_batabattan
	.BYTE objects_large_weapon_capsule
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_gorilla_tank
	.BYTE objects_scrolling
	.BYTE objects_spring
	.BYTE objects_tadahou
	.BYTE objects_gabgyo_vertical
	.BYTE objects_jet_buton
	.BYTE objects_scrolling
	.BYTE objects_gabgyo_vertical
	.BYTE objects_gabgyo_vertical
	.BYTE objects_tadahou
	.BYTE objects_propellor_platform
	.BYTE objects_scrolling
	.BYTE objects_gabgyo_vertical
	.BYTE objects_propellor_platform
	.BYTE objects_jet_buton
	.BYTE objects_propellor_platform
	.BYTE objects_tadahou
	.BYTE objects_propellor_platform
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_jet_buton
	.BYTE objects_propellor_platform
	.BYTE objects_small_life_capsule
	.BYTE objects_gabgyo_vertical
	.BYTE objects_small_life_capsule
	.BYTE objects_propellor_platform
	.BYTE objects_small_life_capsule
	.BYTE objects_propellor_platform
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_jet_buton
	.BYTE objects_gabgyo_vertical
	.BYTE objects_jet_buton
	.BYTE objects_gabgyo_vertical
	.BYTE objects_jet_buton
	.BYTE objects_tadahou
	.BYTE objects_small_life_capsule
	.BYTE objects_tadahou
	.BYTE objects_jet_buton
	.BYTE objects_gabgyo_vertical
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_tadahou
	.BYTE objects_scrolling
	.BYTE objects_small_life_capsule
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE -1
plantman_objects_set_end:
