.SEGMENT "BANK20"
.INCLUDE "constants/oam.asm"
.INCBIN  "sprites/pointers/sprites_32_pointers.bin"
.INCLUDE "sprites/pointers/oamcoord_pointers_1.asm"
.INCLUDE "sprites/pointers/oam_frameset_pointers_1.asm"
.INCLUDE "sprites/oamcoord_1.asm"
.INCBIN  "sprites/sprites_32.bin"
.INCLUDE "sprites/oam_frameset_1.asm"
.INCLUDE "sprites/unused/unused_43c35.asm"

.SEGMENT "BANK22"
.INCBIN  "sprites/pointers/sprites_34_pointers.bin"
.INCLUDE "sprites/pointers/oamcoord_pointers_2.asm"
.INCLUDE "sprites/pointers/oam_frameset_pointers_2.asm"
.INCLUDE "sprites/oamcoord_2.asm"
.INCBIN  "sprites/sprites_34.bin"
.INCLUDE "sprites/oam_frameset_2.asm"
.INCLUDE "sprites/unused/unused_478d2.asm"

.SEGMENT "BANK24"
.INCBIN  "sprites/pointers/sprites_36_pointers.bin"
.INCLUDE "sprites/pointers/oamcoord_pointers_3.asm"
.INCLUDE "sprites/pointers/oam_frameset_pointers_3.asm"
.INCLUDE "sprites/oamcoord_3.asm"
.INCBIN  "sprites/sprites_36.bin"
.INCLUDE "sprites/oam_frameset_3.asm"
.INCLUDE "sprites/unused/unused_4b2f7.asm"
