.SEGMENT "BANK20"
.INCLUDE "constants/oam.asm"
.INCLUDE "sprites/pointers/oam_sprites_pointers_1.asm"
.INCLUDE "sprites/pointers/oamcoord_pointers_1.asm"
.INCLUDE "sprites/pointers/oam_frameset_pointers_1.asm"
.INCLUDE "sprites/oamcoord_1.asm"
.INCLUDE "sprites/oam_sprites_1.asm"
.INCLUDE "sprites/oam_frameset_1.asm"
.INCLUDE "sprites/unused/unused_43c35.asm"

.SEGMENT "BANK22"
.INCLUDE "sprites/pointers/oam_sprites_pointers_2.asm"
.INCLUDE "sprites/pointers/oamcoord_pointers_2.asm"
.INCLUDE "sprites/pointers/oam_frameset_pointers_2.asm"
.INCLUDE "sprites/oamcoord_2.asm"
.INCLUDE "sprites/oam_sprites_2.asm"
.INCLUDE "sprites/oam_frameset_2.asm"
.INCLUDE "sprites/unused/unused_478d2.asm"

.SEGMENT "BANK24"
.INCLUDE "sprites/pointers/oam_sprites_pointers_3.asm"
.INCLUDE "sprites/pointers/oamcoord_pointers_3.asm"
.INCLUDE "sprites/pointers/oam_frameset_pointers_3.asm"
.INCLUDE "sprites/oamcoord_3.asm"
.INCLUDE "sprites/oam_sprites_3.asm"
.INCLUDE "sprites/oam_frameset_3.asm"
.INCLUDE "sprites/unused/unused_4b2f7.asm"
