.SEGMENT "BANK26"
.INCLUDE "stages/x1/x1_mapset.asm"
.INCLUDE "stages/x2/x2_mapset.asm"
.INCLUDE "stages/x3/x3_mapset.asm"
.INCLUDE "stages/x4/x4_mapset.asm"

.SEGMENT "BANK27"
.INCLUDE "stages/wily1/wily1_mapset.asm"
.INCLUDE "stages/wily2/wily2_mapset.asm"
.INCLUDE "stages/wily3/wily3_mapset.asm"
.INCLUDE "stages/wily4/wily4_mapset.asm"

.SEGMENT "BANK28"
.INCBIN  "stages/palettes_40_0.bin"
.INCLUDE "stages/unused/unused_50488.asm"
.INCBIN  "stages/palettes_40_1.bin"
.INCLUDE "stages/unused/unused_5189f.asm"

.SEGMENT "BANK2A"
.INCLUDE "constants/tsa.asm"
.INCLUDE "stages/wily1/wily1_tsa.asm"
.INCLUDE "stages/wily2/wily2_tsa.asm"
.INCLUDE "stages/wily3/wily3_tsa.asm"
.INCBIN  "stages/42.bin"

.SEGMENT "BANK2B"
.INCLUDE "stages/x4/x4_tsa.asm"
.INCLUDE "stages/wily4/wily4_tsa.asm"
.INCLUDE "stages/unused/unused_57210.asm"
.INCBIN  "stages/43.bin"

.SEGMENT "BANK2C"
.INCLUDE "stages/windman/windman_tsa.asm"
.INCLUDE "stages/tomahawkman/tomahawkman_tsa.asm"
.INCLUDE "stages/x1/x1_tsa.asm"
.INCBIN  "stages/44.bin"

.SEGMENT "BANK2D"
.INCLUDE "stages/knightman/knightman_tsa.asm"
.INCLUDE "stages/centaurman/centaurman_tsa.asm"
.INCLUDE "stages/unused/unused_5b210.asm"
.INCBIN  "stages/45.bin"

.SEGMENT "BANK2E"
.INCLUDE "stages/blizzardman/blizzardman_tsa.asm"
.INCLUDE "stages/yamatoman/yamatoman_tsa.asm"
.INCLUDE "stages/plantman/plantman_tsa.asm"
.INCBIN  "stages/46.bin"

.SEGMENT "BANK2F"
.INCLUDE "stages/flameman/flameman_tsa.asm"
.INCLUDE "stages/x2/x2_tsa.asm"
.INCLUDE "stages/x3/x3_tsa.asm"
.INCBIN  "stages/47.bin"

.SEGMENT "BANK32"
.INCLUDE "stages/blizzardman/blizzardman_mapset.asm"
.INCLUDE "stages/windman/windman_mapset.asm"
.INCLUDE "stages/plantman/plantman_mapset.asm"
.INCLUDE "stages/flameman/flameman_mapset.asm"

.SEGMENT "BANK33"
.INCLUDE "stages/yamatoman/yamatoman_mapset.asm"
.INCLUDE "stages/tomahawkman/tomahawkman_mapset.asm"
.INCLUDE "stages/knightman/knightman_mapset.asm"
.INCLUDE "stages/centaurman/centaurman_mapset.asm"

.SEGMENT "BANK37"
.INCBIN  "stages/palettes_55_0.bin"
.INCLUDE "stages/unused/unused_6e410.asm"
.INCBIN  "stages/palettes_55_1.bin"
.INCLUDE "stages/unused/unused_6f89f.asm"
