.SEGMENT "BANK2A"
.INCLUDE "constants/tsa.asm"
.INCLUDE "stages/wily1/wily1_tsa.asm"
.INCLUDE "stages/wily2/wily2_tsa.asm"
.INCLUDE "stages/wily3/wily3_tsa.asm"
.INCBIN  "stages/42.bin"

.SEGMENT "BANK2B"
.INCLUDE "stages/x4/x4_tsa.asm"
.INCLUDE "stages/wily4/wily4_tsa.asm"
.INCBIN  "stages/43.bin"

.SEGMENT "BANK2C"
.INCLUDE "stages/windman/windman_tsa.asm"
.INCLUDE "stages/tomahawkman/tomahawkman_tsa.asm"
.INCLUDE "stages/x1/x1_tsa.asm"
.INCBIN  "stages/44.bin"

.SEGMENT "BANK2D"
.INCLUDE "stages/knightman/knightman_tsa.asm"
.INCLUDE "stages/centaurman/centaurman_tsa.asm"
.INCBIN  "stages/45.bin"

.SEGMENT "BANK2E"
.INCLUDE "stages/blizzardman/blizzardman_tsa.asm"
.INCLUDE "stages/yamatoman/yamatoman_tsa.asm"
.INCLUDE "stages/plantman/plantman_tsa.asm"
.INCBIN  "stages/46.bin"

.SEGMENT "BANK2F"
.INCLUDE "stages/flameman/flameman_tsa.asm"
.INCLUDE "stages/x2/x2_tsa.asm"
.INCLUDE "stages/x3/x3_tsa.asm"
.INCBIN  "stages/47.bin"
