yamatoman_objects_set:
;id
	.BYTE $00
	.BYTE $01
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $04
	.BYTE $04
	.BYTE $05
	.BYTE $05
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $07
	.BYTE $08
	.BYTE $08
	.BYTE $09
	.BYTE $0A
	.BYTE $0B
	.BYTE $0B
	.BYTE $0B
	.BYTE $0C
	.BYTE $0C
	.BYTE $0D
	.BYTE $0D
	.BYTE $0E
	.BYTE $0F
	.BYTE $0F
	.BYTE $10
	.BYTE $10
	.BYTE $11
	.BYTE $11
	.BYTE $11
	.BYTE $11
	.BYTE $11
	.BYTE $11
	.BYTE $11
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $13
	.BYTE $13
	.BYTE $14
	.BYTE $14
	.BYTE $14
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $16
	.BYTE $17
	.BYTE $18
	.BYTE $18
	.BYTE $19
	.BYTE $19
	.BYTE $1A
	.BYTE $1A
	.BYTE $1B
	.BYTE $1B
	.BYTE $1B
	.BYTE $1C
	.BYTE $1D
	.BYTE -1

;x
	.BYTE $40
	.BYTE $70
	.BYTE $31
	.BYTE $91
	.BYTE $C0
	.BYTE $47
	.BYTE $70
	.BYTE $80
	.BYTE $40
	.BYTE $D6
	.BYTE $21
	.BYTE $A7
	.BYTE $18
	.BYTE $43
	.BYTE $93
	.BYTE $C0
	.BYTE $C0
	.BYTE $CF
	.BYTE $40
	.BYTE $47
	.BYTE $C0
	.BYTE $40
	.BYTE $40
	.BYTE $50
	.BYTE $90
	.BYTE $C0
	.BYTE $8E
	.BYTE $C0
	.BYTE $40
	.BYTE $5E
	.BYTE $80
	.BYTE $70
	.BYTE $C0
	.BYTE $40
	.BYTE $72
	.BYTE $41
	.BYTE $4F
	.BYTE $6F
	.BYTE $8F
	.BYTE $B0
	.BYTE $C0
	.BYTE $C1
	.BYTE $25
	.BYTE $78
	.BYTE $80
	.BYTE $40
	.BYTE $7F
	.BYTE $10
	.BYTE $4F
	.BYTE $C0
	.BYTE $40
	.BYTE $48
	.BYTE $79
	.BYTE $A7
	.BYTE $B1
	.BYTE $80
	.BYTE $80
	.BYTE $6B
	.BYTE $80
	.BYTE $40
	.BYTE $70
	.BYTE $40
	.BYTE $F0
	.BYTE $81
	.BYTE $C0
	.BYTE $E3
	.BYTE $80
	.BYTE $80
	.BYTE -1

;y
	.BYTE $00
	.BYTE $6F
	.BYTE $7F
	.BYTE $5F
	.BYTE $2D
	.BYTE $AD
	.BYTE $57
	.BYTE $2E
	.BYTE $08
	.BYTE $4B
	.BYTE $2E
	.BYTE $19
	.BYTE $4C
	.BYTE $63
	.BYTE $72
	.BYTE $01
	.BYTE $39
	.BYTE $7A
	.BYTE $03
	.BYTE $8F
	.BYTE $01
	.BYTE $2F
	.BYTE $00
	.BYTE $6F
	.BYTE $8F
	.BYTE $30
	.BYTE $8C
	.BYTE $35
	.BYTE $36
	.BYTE $67
	.BYTE $37
	.BYTE $57
	.BYTE $38
	.BYTE $7F
	.BYTE $AF
	.BYTE $F5
	.BYTE $8F
	.BYTE $CC
	.BYTE $6F
	.BYTE $CC
	.BYTE $7A
	.BYTE $F6
	.BYTE $53
	.BYTE $33
	.BYTE $33
	.BYTE $34
	.BYTE $6C
	.BYTE $8D
	.BYTE $4C
	.BYTE $01
	.BYTE $1A
	.BYTE $5B
	.BYTE $5B
	.BYTE $5B
	.BYTE $AC
	.BYTE $0B
	.BYTE $0A
	.BYTE $64
	.BYTE $31
	.BYTE $32
	.BYTE $4C
	.BYTE $39
	.BYTE $67
	.BYTE $97
	.BYTE $09
	.BYTE $87
	.BYTE $0B
	.BYTE $0A
	.BYTE -1

;objects
	.BYTE objects_scrolling
	.BYTE objects_shigaraky
	.BYTE objects_shigaraky
	.BYTE objects_shigaraky
	.BYTE objects_scrolling
	.BYTE objects_ben_k
	.BYTE objects_1up
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_katonbyon
	.BYTE objects_katonbyon
	.BYTE objects_katonbyon
	.BYTE objects_katonbyon
	.BYTE objects_katonbyon
	.BYTE objects_katonbyon
	.BYTE objects_scrolling
	.BYTE objects_large_weapon_capsule
	.BYTE objects_katonbyon
	.BYTE objects_scrolling
	.BYTE objects_dachone_ltd_ed
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_shigaraky
	.BYTE objects_shigaraky
	.BYTE objects_scrolling
	.BYTE objects_ben_k
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_large_life_capsule
	.BYTE objects_scrolling
	.BYTE objects_e_tank
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_tadahou
	.BYTE objects_yamato_gabgyo_water
	.BYTE objects_tadahou
	.BYTE objects_gabgyo_vertical
	.BYTE objects_tadahou
	.BYTE objects_gabgyo_vertical
	.BYTE objects_scrolling
	.BYTE objects_yamato_gabgyo_water
	.BYTE objects_propeller_eye
	.BYTE objects_propeller_eye
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_teck
	.BYTE objects_teck
	.BYTE objects_teck
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_ben_k
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_cyber_gabyoall_top
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_ben_k
	.BYTE objects_scrolling
	.BYTE objects_spring_face_bomb
	.BYTE objects_spring_face_bomb
	.BYTE objects_scrolling
	.BYTE objects_spring_face_bomb
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE -1
yamatoman_objects_set_end:
