screen_lo_pointers:
	.LOBYTES screen_set_00
	.LOBYTES screen_set_01
	.LOBYTES screen_set_02
	.LOBYTES screen_set_03
	.LOBYTES screen_set_04
	.LOBYTES screen_set_05
	.LOBYTES screen_set_06
	.LOBYTES screen_set_07
	.LOBYTES screen_set_08
	.LOBYTES screen_set_09
	.LOBYTES screen_set_0a
	.LOBYTES screen_set_0b
	.LOBYTES screen_set_0c
	.LOBYTES screen_set_0d
	.LOBYTES screen_set_0e
	.LOBYTES screen_set_0f
	.LOBYTES screen_set_10
	.LOBYTES screen_set_11
	.LOBYTES screen_set_12
	.LOBYTES screen_set_13
	.LOBYTES screen_set_14
	.LOBYTES screen_set_15
	.LOBYTES screen_set_16
	.LOBYTES screen_set_17
	.LOBYTES screen_set_18
	.LOBYTES screen_set_19
	.LOBYTES screen_set_1a
	.LOBYTES screen_set_1b
	.LOBYTES screen_set_1c
	.LOBYTES screen_set_1d
	.LOBYTES screen_set_1e
	.LOBYTES screen_set_1f
	.LOBYTES screen_set_20
	.LOBYTES screen_set_21
	.LOBYTES screen_set_22
	.LOBYTES screen_set_23
	.LOBYTES screen_set_24
	.LOBYTES screen_set_25
	.LOBYTES screen_set_26
	.LOBYTES screen_set_27
	.LOBYTES screen_set_28
	.LOBYTES screen_set_29
	.LOBYTES screen_set_2a
	.LOBYTES screen_set_2b
	.LOBYTES screen_set_2c
	.LOBYTES screen_set_2d
	.LOBYTES screen_set_2e
	.LOBYTES screen_set_2f
	.LOBYTES screen_set_30
	.LOBYTES screen_set_31
	.LOBYTES screen_set_32
	.LOBYTES screen_set_33
	.LOBYTES screen_set_34
	.LOBYTES screen_set_35
	.LOBYTES screen_set_36
	.LOBYTES screen_set_37
	.LOBYTES screen_set_38
	.LOBYTES screen_set_39
	.LOBYTES screen_set_3a
	.LOBYTES screen_set_3b
	.LOBYTES screen_set_3c
	.LOBYTES screen_set_3d
	.LOBYTES screen_set_3e
	.LOBYTES screen_set_3f
	.LOBYTES screen_set_40
	.LOBYTES screen_set_41
	.LOBYTES screen_set_42
	.LOBYTES screen_set_43
	.LOBYTES screen_set_44
	.LOBYTES screen_set_45
	.LOBYTES screen_set_46
	.LOBYTES screen_set_47
	.LOBYTES screen_set_48
	.LOBYTES screen_set_49
	.LOBYTES screen_set_4a
	.LOBYTES screen_set_4b
	.LOBYTES screen_set_4c
	.LOBYTES screen_set_4d
	.LOBYTES screen_set_4e
	.LOBYTES screen_set_4f
	.LOBYTES screen_set_50
	.LOBYTES screen_set_51
	.LOBYTES screen_set_52
	.LOBYTES screen_set_53
	.LOBYTES screen_set_54
	.LOBYTES screen_set_55
	.LOBYTES screen_set_56
	.LOBYTES screen_set_57
	.LOBYTES screen_set_58
	.LOBYTES screen_set_59
	.LOBYTES screen_set_5a
	.LOBYTES screen_set_5b
	.LOBYTES screen_set_5c
	.LOBYTES screen_set_5d
	.LOBYTES screen_set_5e
	.LOBYTES screen_set_5f
	.LOBYTES screen_set_60
	.LOBYTES screen_set_61
	.LOBYTES screen_set_62
	.LOBYTES screen_set_63
	.LOBYTES screen_set_64
	.LOBYTES screen_set_65
	.LOBYTES screen_set_66
	.LOBYTES screen_set_67
	.LOBYTES screen_set_68
	.LOBYTES screen_set_69
	.LOBYTES screen_set_6a
	.LOBYTES screen_set_6b
	.LOBYTES screen_set_6c
	.LOBYTES screen_set_6d
	.LOBYTES screen_set_6e
	.LOBYTES screen_set_6f
	.LOBYTES screen_set_70
	.LOBYTES screen_set_71
	.LOBYTES screen_set_72
	.LOBYTES screen_set_73
	.LOBYTES screen_set_74
	.LOBYTES screen_set_75
	.LOBYTES screen_set_76
	.LOBYTES screen_set_77
	.LOBYTES screen_set_78
	.LOBYTES screen_set_79
	.LOBYTES screen_set_7a
	.LOBYTES screen_set_7b
	.LOBYTES screen_set_7c
	.LOBYTES screen_set_7d
	.LOBYTES screen_set_7e
	.LOBYTES screen_set_7f
	.LOBYTES screen_set_80
	.LOBYTES screen_set_81
	.LOBYTES screen_set_82
	.LOBYTES screen_set_83
	.LOBYTES screen_set_84
	.LOBYTES screen_set_85
	.LOBYTES screen_set_86
	.LOBYTES screen_set_87
	.LOBYTES screen_set_88
	.LOBYTES screen_set_89
	.LOBYTES screen_set_8a
	.LOBYTES screen_set_8b
	.LOBYTES screen_set_8c
	.LOBYTES screen_set_8d
	.LOBYTES screen_set_8e
	.LOBYTES screen_set_8f
	.LOBYTES screen_set_90
	.LOBYTES screen_set_91
	.LOBYTES screen_set_92
	.LOBYTES screen_set_93
	.LOBYTES screen_set_94
	.LOBYTES screen_set_95
	.LOBYTES screen_set_96
	.LOBYTES screen_set_97
	.LOBYTES screen_set_98
	.LOBYTES screen_set_99
	.LOBYTES screen_set_9a
	.LOBYTES screen_set_9b
	.LOBYTES screen_set_9c
	.LOBYTES screen_set_9d
	.LOBYTES screen_set_9e
	.LOBYTES screen_set_9f
	.LOBYTES screen_set_a0
	.LOBYTES screen_set_a1
	.LOBYTES screen_set_a2
	.LOBYTES screen_set_a3
	.LOBYTES screen_set_a4
	.LOBYTES screen_set_a5
	.LOBYTES screen_set_a6
	.LOBYTES screen_set_a7

screen_hi_pointers:
	.HIBYTES screen_set_00
	.HIBYTES screen_set_01
	.HIBYTES screen_set_02
	.HIBYTES screen_set_03
	.HIBYTES screen_set_04
	.HIBYTES screen_set_05
	.HIBYTES screen_set_06
	.HIBYTES screen_set_07
	.HIBYTES screen_set_08
	.HIBYTES screen_set_09
	.HIBYTES screen_set_0a
	.HIBYTES screen_set_0b
	.HIBYTES screen_set_0c
	.HIBYTES screen_set_0d
	.HIBYTES screen_set_0e
	.HIBYTES screen_set_0f
	.HIBYTES screen_set_10
	.HIBYTES screen_set_11
	.HIBYTES screen_set_12
	.HIBYTES screen_set_13
	.HIBYTES screen_set_14
	.HIBYTES screen_set_15
	.HIBYTES screen_set_16
	.HIBYTES screen_set_17
	.HIBYTES screen_set_18
	.HIBYTES screen_set_19
	.HIBYTES screen_set_1a
	.HIBYTES screen_set_1b
	.HIBYTES screen_set_1c
	.HIBYTES screen_set_1d
	.HIBYTES screen_set_1e
	.HIBYTES screen_set_1f
	.HIBYTES screen_set_20
	.HIBYTES screen_set_21
	.HIBYTES screen_set_22
	.HIBYTES screen_set_23
	.HIBYTES screen_set_24
	.HIBYTES screen_set_25
	.HIBYTES screen_set_26
	.HIBYTES screen_set_27
	.HIBYTES screen_set_28
	.HIBYTES screen_set_29
	.HIBYTES screen_set_2a
	.HIBYTES screen_set_2b
	.HIBYTES screen_set_2c
	.HIBYTES screen_set_2d
	.HIBYTES screen_set_2e
	.HIBYTES screen_set_2f
	.HIBYTES screen_set_30
	.HIBYTES screen_set_31
	.HIBYTES screen_set_32
	.HIBYTES screen_set_33
	.HIBYTES screen_set_34
	.HIBYTES screen_set_35
	.HIBYTES screen_set_36
	.HIBYTES screen_set_37
	.HIBYTES screen_set_38
	.HIBYTES screen_set_39
	.HIBYTES screen_set_3a
	.HIBYTES screen_set_3b
	.HIBYTES screen_set_3c
	.HIBYTES screen_set_3d
	.HIBYTES screen_set_3e
	.HIBYTES screen_set_3f
	.HIBYTES screen_set_40
	.HIBYTES screen_set_41
	.HIBYTES screen_set_42
	.HIBYTES screen_set_43
	.HIBYTES screen_set_44
	.HIBYTES screen_set_45
	.HIBYTES screen_set_46
	.HIBYTES screen_set_47
	.HIBYTES screen_set_48
	.HIBYTES screen_set_49
	.HIBYTES screen_set_4a
	.HIBYTES screen_set_4b
	.HIBYTES screen_set_4c
	.HIBYTES screen_set_4d
	.HIBYTES screen_set_4e
	.HIBYTES screen_set_4f
	.HIBYTES screen_set_50
	.HIBYTES screen_set_51
	.HIBYTES screen_set_52
	.HIBYTES screen_set_53
	.HIBYTES screen_set_54
	.HIBYTES screen_set_55
	.HIBYTES screen_set_56
	.HIBYTES screen_set_57
	.HIBYTES screen_set_58
	.HIBYTES screen_set_59
	.HIBYTES screen_set_5a
	.HIBYTES screen_set_5b
	.HIBYTES screen_set_5c
	.HIBYTES screen_set_5d
	.HIBYTES screen_set_5e
	.HIBYTES screen_set_5f
	.HIBYTES screen_set_60
	.HIBYTES screen_set_61
	.HIBYTES screen_set_62
	.HIBYTES screen_set_63
	.HIBYTES screen_set_64
	.HIBYTES screen_set_65
	.HIBYTES screen_set_66
	.HIBYTES screen_set_67
	.HIBYTES screen_set_68
	.HIBYTES screen_set_69
	.HIBYTES screen_set_6a
	.HIBYTES screen_set_6b
	.HIBYTES screen_set_6c
	.HIBYTES screen_set_6d
	.HIBYTES screen_set_6e
	.HIBYTES screen_set_6f
	.HIBYTES screen_set_70
	.HIBYTES screen_set_71
	.HIBYTES screen_set_72
	.HIBYTES screen_set_73
	.HIBYTES screen_set_74
	.HIBYTES screen_set_75
	.HIBYTES screen_set_76
	.HIBYTES screen_set_77
	.HIBYTES screen_set_78
	.HIBYTES screen_set_79
	.HIBYTES screen_set_7a
	.HIBYTES screen_set_7b
	.HIBYTES screen_set_7c
	.HIBYTES screen_set_7d
	.HIBYTES screen_set_7e
	.HIBYTES screen_set_7f
	.HIBYTES screen_set_80
	.HIBYTES screen_set_81
	.HIBYTES screen_set_82
	.HIBYTES screen_set_83
	.HIBYTES screen_set_84
	.HIBYTES screen_set_85
	.HIBYTES screen_set_86
	.HIBYTES screen_set_87
	.HIBYTES screen_set_88
	.HIBYTES screen_set_89
	.HIBYTES screen_set_8a
	.HIBYTES screen_set_8b
	.HIBYTES screen_set_8c
	.HIBYTES screen_set_8d
	.HIBYTES screen_set_8e
	.HIBYTES screen_set_8f
	.HIBYTES screen_set_90
	.HIBYTES screen_set_91
	.HIBYTES screen_set_92
	.HIBYTES screen_set_93
	.HIBYTES screen_set_94
	.HIBYTES screen_set_95
	.HIBYTES screen_set_96
	.HIBYTES screen_set_97
	.HIBYTES screen_set_98
	.HIBYTES screen_set_99
	.HIBYTES screen_set_9a
	.HIBYTES screen_set_9b
	.HIBYTES screen_set_9c
	.HIBYTES screen_set_9d
	.HIBYTES screen_set_9e
	.HIBYTES screen_set_9f
	.HIBYTES screen_set_a0
	.HIBYTES screen_set_a1
	.HIBYTES screen_set_a2
	.HIBYTES screen_set_a3
	.HIBYTES screen_set_a4
	.HIBYTES screen_set_a5
	.HIBYTES screen_set_a6
	.HIBYTES screen_set_a7
