wily1_objects_set:
;id
	.BYTE $00
	.BYTE $00
	.BYTE $01
	.BYTE $01
	.BYTE $01
	.BYTE $01
	.BYTE $01
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $07
	.BYTE $07
	.BYTE $08
	.BYTE $09
	.BYTE $0A
	.BYTE $0A
	.BYTE $0A
	.BYTE $0A
	.BYTE $0A
	.BYTE $0A
	.BYTE $0A
	.BYTE $0B
	.BYTE $0B
	.BYTE $0C
	.BYTE $0D
	.BYTE $0D
	.BYTE $0E
	.BYTE $0F
	.BYTE $0F
	.BYTE $0F
	.BYTE $0F
	.BYTE $0F
	.BYTE $0F
	.BYTE $10
	.BYTE $10
	.BYTE $11
	.BYTE $11
	.BYTE $12
	.BYTE $13
	.BYTE $14
	.BYTE $15
	.BYTE $15
	.BYTE $16
	.BYTE $16
	.BYTE $16
	.BYTE $16
	.BYTE $16
	.BYTE $16
	.BYTE $16
	.BYTE $16
	.BYTE $16
	.BYTE $17
	.BYTE $17
	.BYTE $17
	.BYTE $17
	.BYTE -1

;x
	.BYTE $40
	.BYTE $EF
	.BYTE $50
	.BYTE $6F
	.BYTE $B0
	.BYTE $CF
	.BYTE $F3
	.BYTE $68
	.BYTE $73
	.BYTE $90
	.BYTE $B1
	.BYTE $C0
	.BYTE $32
	.BYTE $80
	.BYTE $80
	.BYTE $80
	.BYTE $96
	.BYTE $AF
	.BYTE $CF
	.BYTE $45
	.BYTE $70
	.BYTE $80
	.BYTE $90
	.BYTE $30
	.BYTE $50
	.BYTE $79
	.BYTE $80
	.BYTE $93
	.BYTE $7C
	.BYTE $80
	.BYTE $80
	.BYTE $80
	.BYTE $3B
	.BYTE $54
	.BYTE $70
	.BYTE $80
	.BYTE $90
	.BYTE $B0
	.BYTE $D0
	.BYTE $80
	.BYTE $8E
	.BYTE $80
	.BYTE $4F
	.BYTE $80
	.BYTE $40
	.BYTE $80
	.BYTE $91
	.BYTE $B6
	.BYTE $C4
	.BYTE $D1
	.BYTE $DE
	.BYTE $80
	.BYTE $B2
	.BYTE $6F
	.BYTE $C0
	.BYTE $80
	.BYTE $80
	.BYTE $80
	.BYTE $80
	.BYTE $98
	.BYTE $80
	.BYTE $8B
	.BYTE $97
	.BYTE $A2
	.BYTE $AD
	.BYTE $B7
	.BYTE $C0
	.BYTE $CB
	.BYTE $D5
	.BYTE $80
	.BYTE $AD
	.BYTE $C0
	.BYTE $D3
	.BYTE -1

;y
	.BYTE $00
	.BYTE $75
	.BYTE $95
	.BYTE $14
	.BYTE $77
	.BYTE $75
	.BYTE $2E
	.BYTE $95
	.BYTE $24
	.BYTE $35
	.BYTE $18
	.BYTE $47
	.BYTE $73
	.BYTE $93
	.BYTE $48
	.BYTE $02
	.BYTE $B7
	.BYTE $85
	.BYTE $57
	.BYTE $52
	.BYTE $CF
	.BYTE $02
	.BYTE $1F
	.BYTE $CF
	.BYTE $CF
	.BYTE $A7
	.BYTE $02
	.BYTE $63
	.BYTE $B4
	.BYTE $02
	.BYTE $02
	.BYTE $45
	.BYTE $9F
	.BYTE $53
	.BYTE $1F
	.BYTE $02
	.BYTE $CF
	.BYTE $CF
	.BYTE $1F
	.BYTE $02
	.BYTE $51
	.BYTE $02
	.BYTE $59
	.BYTE $36
	.BYTE $7E
	.BYTE $36
	.BYTE $6C
	.BYTE $9B
	.BYTE $9B
	.BYTE $9B
	.BYTE $9B
	.BYTE $36
	.BYTE $47
	.BYTE $6F
	.BYTE $1A
	.BYTE $49
	.BYTE $67
	.BYTE $02
	.BYTE $02
	.BYTE $78
	.BYTE $02
	.BYTE $9C
	.BYTE $9C
	.BYTE $9C
	.BYTE $9C
	.BYTE $9C
	.BYTE $9C
	.BYTE $9C
	.BYTE $9C
	.BYTE $46
	.BYTE $99
	.BYTE $99
	.BYTE $99
	.BYTE -1

;objects
	.BYTE objects_scrolling
	.BYTE objects_metall
	.BYTE objects_metall
	.BYTE objects_fire_telly
	.BYTE objects_1up
	.BYTE objects_metall
	.BYTE objects_fire_telly
	.BYTE objects_metall
	.BYTE objects_fire_telly
	.BYTE objects_metall
	.BYTE objects_fire_telly
	.BYTE objects_scrolling
	.BYTE objects_tatebo
	.BYTE objects_tatebo
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_cannopeller
	.BYTE objects_large_life_capsule
	.BYTE objects_cannopeller
	.BYTE objects_fan_up
	.BYTE objects_scrolling
	.BYTE objects_fan_down
	.BYTE objects_fan_up
	.BYTE objects_fan_up
	.BYTE objects_cannopeller
	.BYTE objects_scrolling
	.BYTE objects_cannopeller
	.BYTE objects_flip_platform
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_cannopeller
	.BYTE objects_cannopeller
	.BYTE objects_fan_down
	.BYTE objects_scrolling
	.BYTE objects_fan_up
	.BYTE objects_fan_up
	.BYTE objects_fan_down
	.BYTE objects_scrolling
	.BYTE objects_cannon_joe_right
	.BYTE objects_scrolling
	.BYTE objects_large_weapon_capsule
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_ben_k
	.BYTE objects_small_life_capsule
	.BYTE objects_small_weapon_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_small_weapon_capsule
	.BYTE objects_scrolling
	.BYTE objects_squidon
	.BYTE objects_cannon_joe_right
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_e_tank
	.BYTE objects_scrolling
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_scrolling
	.BYTE objects_large_weapon_capsule
	.BYTE objects_large_weapon_capsule
	.BYTE objects_large_weapon_capsule
	.BYTE -1
wily1_objects_set_end:
