base $8000
incsrc .\scripts\audio.asm
pad $8a40
;incsrc audio.asm
incsrc track_data_pointers.asm
;incsrc instruments.asm
pad $8d47
incsrc .\music\wind.asm
;incsrc .\music\blizzard.asm
;incsrc .\music\yamato.asm
;incsrc .\music\flame.asm
;incsrc .\music\plant.asm
;incsrc .\music\centaur.asm
;incsrc .\music\tomahawk.asm
;incsrc .\music\knight.asm
;incsrc .\music\ending_part1.asm
;incsrc .\music\x.asm
;incsrc .\music\ending_part2.asm
;incsrc .\music\wily.asm
;incsrc .\music\boss.asm
;incsrc .\music\opening.asm
;incsrc .\music\capcom.asm
;incsrc .\music\stage_select.asm
;incsrc .\music\game_start.asm
;incsrc .\music\x_map.asm
;incsrc .\music\wily_map.asm
;incsrc .\music\stage_clear.asm
;incsrc .\music\game_over.asm
;incsrc .\music\pass_word.asm
;incsrc .\music\get_weapon.asm
;incsrc .\music\all_stage_clear.asm
;incsrc .\music\last_boss.asm
;incsrc .\music\title.asm
pad $c986
incsrc .\unused\unused1a.asm
;incsrc .\music\blizzard_ending.asm
;incsrc .\music\centaur_ending.asm
;incsrc .\music\flame_ending.asm
;incsrc .\music\knight_ending.asm
;incsrc .\music\plant_ending.asm
;incsrc .\music\tomahawk_ending.asm
;incsrc .\music\wind_ending.asm
;incsrc .\music\yamato_ending.asm
pad $d758
incsrc .\sfx\shoot.asm
incsrc .\sfx\landing.asm
incsrc .\sfx\damage_mm.asm
incsrc .\sfx\death.asm
incsrc .\sfx\shoot_recoil.asm
incsrc .\sfx\fully_charged_shoot.asm
incsrc .\sfx\charge_buster.asm
incsrc .\sfx\switch_adapter.asm
incsrc .\sfx\power.asm
incsrc .\sfx\destroy_block.asm
incsrc .\sfx\jet.asm
incsrc .\sfx\beat.asm
incsrc .\sfx\1up.asm
incsrc .\sfx\boss_door.asm
incsrc .\sfx\gain_bar.asm
incsrc .\sfx\change_weapon.asm
incsrc .\sfx\close_menu.asm
incsrc .\sfx\open_menu.asm
incsrc .\sfx\destroy_enemy.asm
incsrc .\sfx\explosion.asm
incsrc .\sfx\teleport_in.asm
incsrc .\sfx\password_wrong.asm
incsrc .\music\proto_whistle.asm
incsrc .\sfx\teleport_out.asm
incsrc .\sfx\yoku_block.asm
incsrc .\sfx\water.asm
incsrc .\unused\unused3d.asm
incsrc .\sfx\destroy_ice.asm
incsrc .\sfx\jet_mute.asm
incsrc .\sfx\ship_down.asm
incsrc .\sfx\ship_up.asm
incsrc .\sfx\met.asm
incsrc .\sfx\pooker.asm
incsrc .\sfx\colton.asm
incsrc .\sfx\fire_telly.asm
incsrc .\sfx\teck.asm
incsrc .\sfx\curlinger.asm
incsrc .\sfx\heli_buton.asm
;incsrc .\sfx\power_slam_up.asm
;incsrc .\sfx\enemy_falling.asm
;incsrc .\sfx\power_slam_down.asm
;incsrc .\sfx\skull_walker.asm
;incsrc .\unused\unused4d.asm
;incsrc .\sfx\count_bomb.asm
;incsrc .\sfx\fan.asm
;incsrc .\sfx\oil.asm
;incsrc .\unused\unused51.asm
;incsrc .\sfx\flamethrower.asm
;incsrc .\sfx\heli_buton_appeared.asm
;incsrc .\sfx\spring.asm
;incsrc .\sfx\spikes_press_up.asm
;incsrc .\sfx\spikes_press_down.asm
;incsrc .\sfx\spikes_press_stop.asm
;incsrc .\sfx\centaur_flash.asm
;incsrc .\sfx\blizzard_attack.asm
;incsrc .\sfx\blizzard_rolling.asm
;incsrc .\sfx\blizzard_rollout.asm
;incsrc .\sfx\centaur_disappeared1.asm
;incsrc .\sfx\centaur_disappeared2.asm
;incsrc .\sfx\centaur_running.asm
;incsrc .\sfx\get_weapon_energy.asm
;incsrc .\sfx\wily_machine.asm
pad $de99
incsrc .\sfx\lighting.asm
incsrc .\sfx\routine_map.asm
incsrc .\sfx\ufo.asm
incsrc .\sfx\ending_mute.asm
;incsrc .\sfx\get_weapon.asm
;incsrc .\unused\unusedpre.asm
pad $e000