;track_total
	db (track_data_end-track_data_start)/2

;instruments_pointers
	;dh instruments_data
	;dl instruments_data

track_data_start
;music
	dh music_wind
	dl music_wind
	;dh music_blizzard
	;dl music_blizzard
	;dh music_yamato
	;dl music_yamato
	;dh music_flame
	;dl music_flame
	;dh music_plant
	;dl music_plant
	;dh music_centaur
	;dl music_centaur
	;dh music_tomahawk
	;dl music_tomahawk
	;dh music_knight
	;dl music_knight
	;dh music_ending_part1
	;dl music_ending_part1
	;dh music_x
	;dl music_x
	;dh music_ending_part2
	;dl music_ending_part2
	;dh music_wily
	;dl music_wily
	;dh music_boss
	;dl music_boss
	;dh music_opening
	;dl music_opening
	;dh music_capcom
	;dl music_capcom
	;dh music_stage_select
	;dl music_stage_select
	;dh music_game_start
	;dl music_game_start
	;dh music_x_map
	;dl music_x_map
	;dh music_wily_map
	;dl music_wily_map
	;dh music_stage_clear
	;dl music_stage_clear
	;dh music_game_over
	;dl music_game_over
	;dh music_pass_word
	;dl music_pass_word
	;dh music_get_weapon
	;dl music_get_weapon
	;dh music_all_stage_clear
	;dl music_all_stage_clear
	;dh music_last_boss
	;dl music_last_boss
	;dh music_title
	;dl music_title
	dh music_unused1a
	dl music_unused1a
	;dh music_blizzard_ending
	;dl music_blizzard_ending
	;dh music_centaur_ending
	;dl music_centaur_ending
	;dh music_flame_ending
	;dl music_flame_ending
	;dh music_knight_ending
	;dl music_knight_ending
	;dh music_plant_ending
	;dl music_plant_ending
	;dh music_tomahawk_ending
	;dl music_tomahawk_ending
	;dh music_wind_ending
	;dl music_wind_ending
	;dh music_yamato_ending
	;dl music_yamato_ending

;sfx
	dh sfx_shoot
	dl sfx_shoot
	dh sfx_landing
	dl sfx_landing
	dh sfx_damage_mm
	dl sfx_damage_mm
	dh sfx_death
	dl sfx_death
	dh sfx_shoot_recoil
	dl sfx_shoot_recoil
	dh sfx_fully_charged_shoot
	dl sfx_fully_charged_shoot
	dh sfx_charge_buster
	dl sfx_charge_buster
	dh sfx_switch_adapter
	dl sfx_switch_adapter
	dh sfx_power
	dl sfx_power
	dh sfx_destroy_block
	dl sfx_destroy_block
	dh sfx_jet
	dl sfx_jet
	dh sfx_beat
	dl sfx_beat
	dh sfx_1up
	dl sfx_1up
	dh sfx_boss_door
	dl sfx_boss_door
	dh sfx_gain_bar
	dl sfx_gain_bar
	dh sfx_change_weapon
	dl sfx_change_weapon
	dh sfx_close_menu
	dl sfx_close_menu
	dh sfx_open_menu
	dl sfx_open_menu
	dh sfx_destroy_enemy
	dl sfx_destroy_enemy
	dh sfx_explosion
	dl sfx_explosion
	dh sfx_teleport_in
	dl sfx_teleport_in
	dh sfx_password_wrong
	dl sfx_password_wrong

;music
	dh music_proto_whistle
	dl music_proto_whistle

;sfx
	dh sfx_teleport_out
	dl sfx_teleport_out
	dh sfx_yoku_block
	dl sfx_yoku_block
	dh sfx_water
	dl sfx_water
	dh sfx_unused3d
	dl sfx_unused3d
	dh sfx_destroy_ice
	dl sfx_destroy_ice
	dh sfx_jet_mute
	dl sfx_jet_mute
	dh sfx_ship_down
	dl sfx_ship_down
	dh sfx_ship_up
	dl sfx_ship_up
	dh sfx_met
	dl sfx_met
	dh sfx_pooker
	dl sfx_pooker
	dh sfx_colton
	dl sfx_colton
	dh sfx_fire_telly
	dl sfx_fire_telly
	dh sfx_teck
	dl sfx_teck
	dh sfx_curlinger
	dl sfx_curlinger
	dh sfx_heli_buton
	dl sfx_heli_buton
	dh sfx_power_slam_up
	dl sfx_power_slam_up
	dh sfx_enemy_falling
	dl sfx_enemy_falling
	dh sfx_power_slam_down
	dl sfx_power_slam_down
	dh sfx_skull_walker
	dl sfx_skull_walker
	dh sfx_unused4d
	dl sfx_unused4d
	dh sfx_count_bomb
	dl sfx_count_bomb
	dh sfx_fan
	dl sfx_fan
	dh sfx_oil
	dl sfx_oil
	dh sfx_unused51
	dl sfx_unused51
	dh sfx_flamethrower
	dl sfx_flamethrower
	dh sfx_heli_buton_appeared
	dl sfx_heli_buton_appeared
	dh sfx_spring
	dl sfx_spring
	dh sfx_spikes_press_up
	dl sfx_spikes_press_up
	dh sfx_spikes_press_down
	dl sfx_spikes_press_down
	dh sfx_spikes_press_stop
	dl sfx_spikes_press_stop
	;dh sfx_centaur_flash
	;dl sfx_centaur_flash
	;dh sfx_blizzard_attack
	;dl sfx_blizzard_attack
	;dh sfx_blizzard_rolling
	;dl sfx_blizzard_rolling
	;dh sfx_blizzard_rollout
	;dl sfx_blizzard_rollout
	;dh sfx_centaur_disappeared1
	;dl sfx_centaur_disappeared1
	;dh sfx_centaur_disappeared2
	;dl sfx_centaur_disappeared2
	;dh sfx_centaur_running
	;dl sfx_centaur_running
	;dh sfx_get_weapon_energy
	;dl sfx_get_weapon_energy
	;dh sfx_wily_machine
	;dl sfx_wily_machine
	dh sfx_lighting
	dl sfx_lighting
	dh sfx_routine_map
	dl sfx_routine_map
	dh sfx_ufo
	dl sfx_ufo
	dh sfx_ending_mute
	dl sfx_ending_mute
	;dh sfx_get_weapon
	;dl sfx_get_weapon
track_data_end