track_pointers:
	.DBYT music_windman
	.DBYT music_blizzardman
	.DBYT music_yamatoman
	.DBYT music_flameman
	.DBYT music_plantman
	.DBYT music_centaurman
	.DBYT music_tomahawkman
	.DBYT music_knightman
	.DBYT music_ending
	.DBYT music_x
	.DBYT music_staff_roll
	.DBYT music_wily
	.DBYT music_boss_fighting
	.DBYT music_opening
	.DBYT music_capcom
	.DBYT music_stage_select
	.DBYT music_boss_show
	.DBYT music_x_castle
	.DBYT music_wily_castle
	.DBYT music_boss_defeated
	.DBYT music_game_over
	.DBYT music_password
	.DBYT music_get_weapon
	.DBYT music_wily_defeated
	.DBYT music_wily_fighting
	.DBYT music_title
	.DBYT music_nothing
	.DBYT music_ending_blizzardman
	.DBYT music_ending_centaurman
	.DBYT music_ending_flameman
	.DBYT music_ending_knightman
	.DBYT music_ending_plantman
	.DBYT music_ending_tomahawkman
	.DBYT music_ending_windman
	.DBYT music_ending_yamatoman
	.DBYT sfx_mega_buster
	.DBYT sfx_landing
	.DBYT sfx_megaman_hit
	.DBYT sfx_death
	.DBYT sfx_enemy_immune
	.DBYT sfx_28
	.DBYT sfx_charge_shot_full_charging
	.DBYT sfx_adapter
	.DBYT sfx_power_adapter_half_charge_shot
	.DBYT sfx_power_adapter_destroy_block
	.DBYT sfx_jet
	.DBYT sfx_beat
	.DBYT sfx_1up
	.DBYT sfx_door
	.DBYT sfx_refill
	.DBYT sfx_select
	.DBYT sfx_confirm
	.DBYT sfx_open_menu
	.DBYT sfx_enemy_hit
	.DBYT sfx_explosion
	.DBYT sfx_teleport_in
	.DBYT sfx_error
	.DBYT music_protoman_whistle
	.DBYT sfx_teleport_out
	.DBYT sfx_appearing_block
	.DBYT sfx_jump_into_water
	.DBYT sfx_3d
	.DBYT sfx_power_adapter_destroy_ice
	.DBYT sfx_3f
	.DBYT sfx_submarine_up
	.DBYT sfx_submarine_down
	.DBYT sfx_enemy_bullet
	.DBYT sfx_brown
	.DBYT sfx_colton
	.DBYT sfx_fire_telly
	.DBYT sfx_teck
	.DBYT sfx_curlinger
	.DBYT sfx_heli_buton
	.DBYT sfx_power_slam_up
	.DBYT sfx_power_slam_down
	.DBYT sfx_power_slam_landing
	.DBYT sfx_batabattan_landing
	.DBYT sfx_4d
	.DBYT sfx_count_bomb
	.DBYT sfx_fan
	.DBYT sfx_oil
	.DBYT sfx_51
	.DBYT sfx_flameman_fire_pillar
	.DBYT sfx_heli_buton_appear
	.DBYT sfx_spring
	.DBYT sfx_spike_ceiling_up
	.DBYT sfx_spike_ceiling_down
	.DBYT sfx_spike_ceiling_end
	.DBYT sfx_centaur_flash
	.DBYT sfx_blizzard_attack
	.DBYT sfx_blizzardman_rolling
	.DBYT sfx_blizzardman_rollout
	.DBYT sfx_centaurman_disappear
	.DBYT sfx_centaurman_appear
	.DBYT sfx_centaurman_running
	.DBYT sfx_get_weapon_energy
	.DBYT sfx_wily_machine_6_stomp
	.DBYT sfx_lighting
	.DBYT sfx_route
	.DBYT sfx_wily_ufo
	.DBYT sfx_64
	.DBYT sfx_get_weapon_blast
