wily2_objects_set:
;id
	.BYTE $00
	.BYTE $00
	.BYTE $01
	.BYTE $01
	.BYTE $01
	.BYTE $01
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $05
	.BYTE $06
	.BYTE $06
	.BYTE $07
	.BYTE $08
	.BYTE $09
	.BYTE $09
	.BYTE $09
	.BYTE $09
	.BYTE $0A
	.BYTE $0A
	.BYTE $0B
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0D
	.BYTE $0D
	.BYTE $0D
	.BYTE $0E
	.BYTE $0F
	.BYTE $10
	.BYTE $11
	.BYTE $11
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE -1

;x
	.BYTE $30
	.BYTE $40
	.BYTE $1A
	.BYTE $57
	.BYTE $D6
	.BYTE $FA
	.BYTE $76
	.BYTE $A3
	.BYTE $CA
	.BYTE $49
	.BYTE $C0
	.BYTE $D6
	.BYTE $D6
	.BYTE $28
	.BYTE $48
	.BYTE $58
	.BYTE $58
	.BYTE $58
	.BYTE $78
	.BYTE $80
	.BYTE $88
	.BYTE $98
	.BYTE $A8
	.BYTE $A8
	.BYTE $C8
	.BYTE $40
	.BYTE $13
	.BYTE $94
	.BYTE $55
	.BYTE $01
	.BYTE $34
	.BYTE $78
	.BYTE $B7
	.BYTE $C0
	.BYTE $80
	.BYTE $B7
	.BYTE $40
	.BYTE $08
	.BYTE $17
	.BYTE $68
	.BYTE $76
	.BYTE $D6
	.BYTE $36
	.BYTE $97
	.BYTE $C0
	.BYTE $80
	.BYTE $80
	.BYTE $40
	.BYTE $33
	.BYTE $D3
	.BYTE $33
	.BYTE $72
	.BYTE $C0
	.BYTE -1

;y
	.BYTE $77
	.BYTE $00
	.BYTE $55
	.BYTE $55
	.BYTE $74
	.BYTE $5F
	.BYTE $6F
	.BYTE $90
	.BYTE $54
	.BYTE $94
	.BYTE $0D
	.BYTE $8F
	.BYTE $3F
	.BYTE $10
	.BYTE $01
	.BYTE $23
	.BYTE $34
	.BYTE $42
	.BYTE $25
	.BYTE $4A
	.BYTE $16
	.BYTE $07
	.BYTE $09
	.BYTE $38
	.BYTE $4A
	.BYTE $08
	.BYTE $A3
	.BYTE $83
	.BYTE $33
	.BYTE $33
	.BYTE $A3
	.BYTE $97
	.BYTE $83
	.BYTE $01
	.BYTE $50
	.BYTE $99
	.BYTE $03
	.BYTE $39
	.BYTE $93
	.BYTE $37
	.BYTE $93
	.BYTE $73
	.BYTE $63
	.BYTE $53
	.BYTE $09
	.BYTE $5F
	.BYTE $6D
	.BYTE $00
	.BYTE $B3
	.BYTE $63
	.BYTE $93
	.BYTE $53
	.BYTE $4B
	.BYTE -1

;objects
	.BYTE objects_e_tank
	.BYTE objects_scrolling
	.BYTE objects_curlinger
	.BYTE objects_curlinger
	.BYTE objects_curlinger
	.BYTE objects_shield_attacker_gtr
	.BYTE objects_shield_attacker_gtr
	.BYTE objects_shield_attacker_gtr
	.BYTE objects_curlinger
	.BYTE objects_curlinger
	.BYTE objects_scrolling
	.BYTE objects_shield_attacker_gtr
	.BYTE objects_shield_attacker_gtr
	.BYTE objects_appearing_block
	.BYTE objects_appearing_block
	.BYTE objects_appearing_block
	.BYTE objects_appearing_block
	.BYTE objects_appearing_block
	.BYTE objects_appearing_block
	.BYTE objects_scrolling
	.BYTE objects_appearing_block
	.BYTE objects_appearing_block
	.BYTE objects_appearing_block
	.BYTE objects_appearing_block
	.BYTE objects_appearing_block
	.BYTE objects_scrolling
	.BYTE objects_brain_break
	.BYTE objects_brain_break
	.BYTE objects_brain_break
	.BYTE objects_brain_break
	.BYTE objects_brain_break
	.BYTE objects_e_tank
	.BYTE objects_brain_break
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_large_weapon_capsule
	.BYTE objects_scrolling
	.BYTE objects_large_weapon_capsule
	.BYTE objects_brain_break
	.BYTE objects_large_life_capsule
	.BYTE objects_brain_break
	.BYTE objects_brain_break
	.BYTE objects_brain_break
	.BYTE objects_brain_break
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_tatebo
	.BYTE objects_tatebo
	.BYTE objects_tatebo
	.BYTE objects_tatebo
	.BYTE objects_scrolling
	.BYTE -1
wily2_objects_set_end:
