centaurman_objects_set:
;id
	.BYTE $00
	.BYTE $00
	.BYTE $01
	.BYTE $01
	.BYTE $01
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $07
	.BYTE $07
	.BYTE $07
	.BYTE $07
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $09
	.BYTE $09
	.BYTE $09
	.BYTE $09
	.BYTE $0A
	.BYTE $0A
	.BYTE $0C
	.BYTE $0C
	.BYTE $0D
	.BYTE $0D
	.BYTE $0E
	.BYTE $0E
	.BYTE $0E
	.BYTE $0E
	.BYTE $0F
	.BYTE $0F
	.BYTE $10
	.BYTE $10
	.BYTE $11
	.BYTE $11
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $14
	.BYTE $14
	.BYTE $15
	.BYTE $16
	.BYTE $17
	.BYTE $18
	.BYTE $19
	.BYTE $1A
	.BYTE -1

;x
	.BYTE $40
	.BYTE $50
	.BYTE $0F
	.BYTE $96
	.BYTE $CA
	.BYTE $10
	.BYTE $46
	.BYTE $E1
	.BYTE $F0
	.BYTE $75
	.BYTE $98
	.BYTE $A4
	.BYTE $20
	.BYTE $B2
	.BYTE $C0
	.BYTE $D2
	.BYTE $2E
	.BYTE $4E
	.BYTE $80
	.BYTE $40
	.BYTE $B7
	.BYTE $C9
	.BYTE $56
	.BYTE $92
	.BYTE $D7
	.BYTE $FF
	.BYTE $16
	.BYTE $82
	.BYTE $9B
	.BYTE $C0
	.BYTE $57
	.BYTE $80
	.BYTE $9E
	.BYTE $D0
	.BYTE $40
	.BYTE $4B
	.BYTE $10
	.BYTE $92
	.BYTE $8C
	.BYTE $C0
	.BYTE $80
	.BYTE $95
	.BYTE $C9
	.BYTE $D5
	.BYTE $29
	.BYTE $80
	.BYTE $40
	.BYTE $50
	.BYTE $1D
	.BYTE $99
	.BYTE $36
	.BYTE $78
	.BYTE $A6
	.BYTE $BB
	.BYTE $C0
	.BYTE $43
	.BYTE $4D
	.BYTE $80
	.BYTE $86
	.BYTE $97
	.BYTE $40
	.BYTE $9B
	.BYTE $C0
	.BYTE $80
	.BYTE $80
	.BYTE $80
	.BYTE $80
	.BYTE $80
	.BYTE -1

;y
	.BYTE $5A
	.BYTE $FF
	.BYTE $08
	.BYTE $5B
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $27
	.BYTE $07
	.BYTE $08
	.BYTE $08
	.BYTE $1C
	.BYTE $35
	.BYTE $2E
	.BYTE $01
	.BYTE $21
	.BYTE $40
	.BYTE $91
	.BYTE $59
	.BYTE $03
	.BYTE $AF
	.BYTE $70
	.BYTE $8E
	.BYTE $53
	.BYTE $71
	.BYTE $93
	.BYTE $6F
	.BYTE $94
	.BYTE $4C
	.BYTE $2B
	.BYTE $4F
	.BYTE $02
	.BYTE $B1
	.BYTE $82
	.BYTE $5B
	.BYTE $00
	.BYTE $6F
	.BYTE $6F
	.BYTE $AF
	.BYTE $57
	.BYTE $07
	.BYTE $89
	.BYTE $B7
	.BYTE $79
	.BYTE $B3
	.BYTE $5C
	.BYTE $08
	.BYTE $FF
	.BYTE $45
	.BYTE $27
	.BYTE $A7
	.BYTE $28
	.BYTE $87
	.BYTE $FF
	.BYTE $0D
	.BYTE $2A
	.BYTE $2A
	.BYTE $07
	.BYTE $2A
	.BYTE $2A
	.BYTE $19
	.BYTE $87
	.BYTE $5E
	.BYTE $5D
	.BYTE $0A
	.BYTE $7B
	.BYTE $5D
	.BYTE $0A
	.BYTE -1

;objects
	.BYTE objects_scrolling
	.BYTE objects_water
	.BYTE objects_sru_21_p
	.BYTE objects_pelicanu
	.BYTE objects_sru_21_p
	.BYTE objects_sru_21_p
	.BYTE objects_sru_21_p
	.BYTE objects_pelicanu
	.BYTE objects_sru_21_p
	.BYTE objects_sru_21_p
	.BYTE objects_sru_21_p
	.BYTE objects_pelicanu
	.BYTE objects_pelicanu
	.BYTE objects_pelicanu
	.BYTE objects_scrolling
	.BYTE objects_sru_21_p
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_scrolling
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_scrolling
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_scrolling
	.BYTE objects_water
	.BYTE objects_choker_oh
	.BYTE objects_choker_oh
	.BYTE objects_choker_oh
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_pooker
	.BYTE objects_large_life_capsule
	.BYTE objects_pooker
	.BYTE objects_eddie
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_water
	.BYTE objects_submarine_flier
	.BYTE objects_submarine_flier
	.BYTE objects_submarine_flier
	.BYTE objects_submarine_flier
	.BYTE objects_submarine_flier
	.BYTE objects_water
	.BYTE objects_scrolling
	.BYTE objects_sru_21_p
	.BYTE objects_sru_21_p
	.BYTE objects_scrolling
	.BYTE objects_sru_21_p
	.BYTE objects_sru_21_p
	.BYTE objects_scrolling
	.BYTE objects_squidon
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE -1
centaurman_objects_set_end:
