flameman_objects_set:
;id
	.BYTE $00
	.BYTE $00
	.BYTE $01
	.BYTE $01
	.BYTE $01
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $03
	.BYTE $04
	.BYTE $04
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $07
	.BYTE $07
	.BYTE $07
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $09
	.BYTE $0A
	.BYTE $0A
	.BYTE $0A
	.BYTE $0B
	.BYTE $0B
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0D
	.BYTE $0D
	.BYTE $0D
	.BYTE $0D
	.BYTE $0E
	.BYTE $0E
	.BYTE $0F
	.BYTE $10
	.BYTE $10
	.BYTE $11
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $14
	.BYTE $14
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $16
	.BYTE $17
	.BYTE -1

;x
	.BYTE $40
	.BYTE $8C
	.BYTE $57
	.BYTE $8F
	.BYTE $C8
	.BYTE $69
	.BYTE $90
	.BYTE $AB
	.BYTE $CF
	.BYTE $92
	.BYTE $3E
	.BYTE $CE
	.BYTE $88
	.BYTE $91
	.BYTE $C0
	.BYTE $D8
	.BYTE $27
	.BYTE $76
	.BYTE $80
	.BYTE $40
	.BYTE $74
	.BYTE $8C
	.BYTE $15
	.BYTE $70
	.BYTE $D0
	.BYTE $F5
	.BYTE $88
	.BYTE $A0
	.BYTE $F6
	.BYTE $76
	.BYTE $DB
	.BYTE $5D
	.BYTE $77
	.BYTE $A6
	.BYTE $C0
	.BYTE $CD
	.BYTE $D6
	.BYTE $E1
	.BYTE $28
	.BYTE $6A
	.BYTE $80
	.BYTE $B6
	.BYTE $40
	.BYTE $D6
	.BYTE $40
	.BYTE $77
	.BYTE $FC
	.BYTE $EF
	.BYTE $70
	.BYTE $73
	.BYTE $EA
	.BYTE $F6
	.BYTE $36
	.BYTE $40
	.BYTE $DE
	.BYTE $AC
	.BYTE $D4
	.BYTE $50
	.BYTE $C0
	.BYTE $C2
	.BYTE $C0
	.BYTE $80
	.BYTE -1

;y
	.BYTE $18
	.BYTE $01
	.BYTE $95
	.BYTE $6B
	.BYTE $95
	.BYTE $75
	.BYTE $57
	.BYTE $FF
	.BYTE $5B
	.BYTE $36
	.BYTE $4A
	.BYTE $2F
	.BYTE $18
	.BYTE $97
	.BYTE $0D
	.BYTE $80
	.BYTE $6F
	.BYTE $4E
	.BYTE $07
	.BYTE $08
	.BYTE $FF
	.BYTE $79
	.BYTE $59
	.BYTE $89
	.BYTE $27
	.BYTE $59
	.BYTE $29
	.BYTE $43
	.BYTE $79
	.BYTE $79
	.BYTE $4A
	.BYTE $3B
	.BYTE $23
	.BYTE $4A
	.BYTE $0C
	.BYTE $2A
	.BYTE $FF
	.BYTE $4A
	.BYTE $8F
	.BYTE $6F
	.BYTE $0E
	.BYTE $B0
	.BYTE $26
	.BYTE $97
	.BYTE $73
	.BYTE $57
	.BYTE $74
	.BYTE $73
	.BYTE $47
	.BYTE $93
	.BYTE $97
	.BYTE $67
	.BYTE $97
	.BYTE $53
	.BYTE $63
	.BYTE $33
	.BYTE $33
	.BYTE $63
	.BYTE $09
	.BYTE $93
	.BYTE $0B
	.BYTE $0A
	.BYTE -1

;objects
	.BYTE objects_scrolling
	.BYTE objects_oil
	.BYTE objects_metall
	.BYTE objects_small_life_capsule
	.BYTE objects_metall
	.BYTE objects_metall
	.BYTE objects_1up
	.BYTE objects_fire_telly_ignite
	.BYTE objects_small_life_capsule
	.BYTE objects_fire_telly
	.BYTE objects_fire_telly
	.BYTE objects_fire_telly
	.BYTE objects_fire_telly
	.BYTE objects_large_life_capsule
	.BYTE objects_scrolling
	.BYTE objects_fire_telly
	.BYTE objects_wall_blaster_ii_right
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_fire_telly_ignite
	.BYTE objects_pooker
	.BYTE objects_pooker
	.BYTE objects_pooker
	.BYTE objects_large_life_capsule
	.BYTE objects_pooker
	.BYTE objects_fire_telly
	.BYTE objects_fire_telly
	.BYTE objects_pooker
	.BYTE objects_pooker
	.BYTE objects_fire_telly
	.BYTE objects_fire_telly
	.BYTE objects_fire_telly
	.BYTE objects_fire_telly
	.BYTE objects_scrolling
	.BYTE objects_fire_telly
	.BYTE objects_fire_telly_ignite
	.BYTE objects_fire_telly
	.BYTE objects_wall_blaster_ii_right
	.BYTE objects_wall_blaster_ii_right
	.BYTE objects_scrolling
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_scrolling
	.BYTE objects_cyber_gabyoall_2
	.BYTE objects_fire_boy
	.BYTE objects_cyber_gabyoall_2
	.BYTE objects_fire_boy
	.BYTE objects_fire_boy
	.BYTE objects_large_life_capsule
	.BYTE objects_fire_boy
	.BYTE objects_e_tank
	.BYTE objects_cyber_gabyoall_2
	.BYTE objects_cyber_gabyoall_2
	.BYTE objects_fire_boy
	.BYTE objects_fire_boy
	.BYTE objects_fire_boy
	.BYTE objects_fire_boy
	.BYTE objects_fire_boy
	.BYTE objects_scrolling
	.BYTE objects_fire_boy
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE -1
flameman_objects_set_end:
