windman_objects_set:
;id
	.BYTE $00
	.BYTE $01
	.BYTE $01
	.BYTE $01
	.BYTE $02
	.BYTE $02
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $07
	.BYTE $07
	.BYTE $07
	.BYTE $07
	.BYTE $07
	.BYTE $08
	.BYTE $08
	.BYTE $09
	.BYTE $09
	.BYTE $09
	.BYTE $09
	.BYTE $09
	.BYTE $0A
	.BYTE $0A
	.BYTE $0A
	.BYTE $0A
	.BYTE $0A
	.BYTE $0A
	.BYTE $0B
	.BYTE $0B
	.BYTE $0B
	.BYTE $0B
	.BYTE $0C
	.BYTE $0C
	.BYTE $0D
	.BYTE $0D
	.BYTE $0D
	.BYTE $0E
	.BYTE $0E
	.BYTE $0F
	.BYTE $0F
	.BYTE $0F
	.BYTE $10
	.BYTE $10
	.BYTE $11
	.BYTE $11
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $14
	.BYTE $15
	.BYTE -1

;x
	.BYTE $40
	.BYTE $72
	.BYTE $C0
	.BYTE $D3
	.BYTE $2E
	.BYTE $80
	.BYTE $80
	.BYTE $C4
	.BYTE $CD
	.BYTE $34
	.BYTE $50
	.BYTE $80
	.BYTE $B0
	.BYTE $40
	.BYTE $5E
	.BYTE $78
	.BYTE $90
	.BYTE $10
	.BYTE $50
	.BYTE $85
	.BYTE $91
	.BYTE $B0
	.BYTE $E9
	.BYTE $14
	.BYTE $50
	.BYTE $8F
	.BYTE $C0
	.BYTE $D0
	.BYTE $40
	.BYTE $D1
	.BYTE $25
	.BYTE $D3
	.BYTE $D9
	.BYTE $E9
	.BYTE $F7
	.BYTE $07
	.BYTE $1A
	.BYTE $2F
	.BYTE $98
	.BYTE $C0
	.BYTE $D1
	.BYTE $3A
	.BYTE $68
	.BYTE $78
	.BYTE $80
	.BYTE $40
	.BYTE $82
	.BYTE $8E
	.BYTE $C0
	.BYTE $CD
	.BYTE $70
	.BYTE $80
	.BYTE $46
	.BYTE $67
	.BYTE $80
	.BYTE $40
	.BYTE $D2
	.BYTE $50
	.BYTE $8F
	.BYTE $01
	.BYTE $50
	.BYTE $90
	.BYTE $C0
	.BYTE $D2
	.BYTE $28
	.BYTE $39
	.BYTE $80
	.BYTE $80
	.BYTE $80
	.BYTE -1

;y
	.BYTE $00
	.BYTE $9C
	.BYTE $0F
	.BYTE $4B
	.BYTE $73
	.BYTE $10
	.BYTE $07
	.BYTE $B7
	.BYTE $5A
	.BYTE $56
	.BYTE $CF
	.BYTE $11
	.BYTE $CF
	.BYTE $12
	.BYTE $A7
	.BYTE $77
	.BYTE $C7
	.BYTE $B7
	.BYTE $CF
	.BYTE $57
	.BYTE $97
	.BYTE $CF
	.BYTE $58
	.BYTE $97
	.BYTE $CF
	.BYTE $97
	.BYTE $14
	.BYTE $CF
	.BYTE $00
	.BYTE $90
	.BYTE $9B
	.BYTE $BA
	.BYTE $2B
	.BYTE $2B
	.BYTE $2B
	.BYTE $2B
	.BYTE $97
	.BYTE $27
	.BYTE $D7
	.BYTE $0D
	.BYTE $D0
	.BYTE $66
	.BYTE $37
	.BYTE $37
	.BYTE $07
	.BYTE $08
	.BYTE $5B
	.BYTE $6B
	.BYTE $15
	.BYTE $8B
	.BYTE $4B
	.BYTE $02
	.BYTE $93
	.BYTE $A3
	.BYTE $16
	.BYTE $03
	.BYTE $6B
	.BYTE $CF
	.BYTE $CF
	.BYTE $8B
	.BYTE $CF
	.BYTE $CF
	.BYTE $17
	.BYTE $6B
	.BYTE $57
	.BYTE $59
	.BYTE $20
	.BYTE $0B
	.BYTE $0A
	.BYTE -1

;id
	.BYTE objects_scrolling
	.BYTE objects_pandeeta
	.BYTE objects_scrolling
	.BYTE objects_pandeeta
	.BYTE objects_twin_roader
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_large_life_capsule
	.BYTE objects_pandeeta
	.BYTE objects_cannopeller
	.BYTE objects_fan_up
	.BYTE objects_scrolling
	.BYTE objects_fan_up
	.BYTE objects_scrolling
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_large_life_capsule
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_fan_up
	.BYTE objects_cannopeller
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_fan_up
	.BYTE objects_cannopeller
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_fan_up
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_scrolling
	.BYTE objects_fan_up
	.BYTE objects_scrolling
	.BYTE objects_flip_platform
	.BYTE objects_flip_platform
	.BYTE objects_flip_platform
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_flip_platform
	.BYTE objects_e_tank
	.BYTE objects_flip_platform
	.BYTE objects_scrolling
	.BYTE objects_fan_up
	.BYTE objects_cyber_gabyoall_top
	.BYTE objects_1up
	.BYTE objects_large_life_capsule
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_pandeeta
	.BYTE objects_pandeeta
	.BYTE objects_scrolling
	.BYTE objects_pandeeta
	.BYTE objects_power_slam
	.BYTE objects_scrolling
	.BYTE objects_twin_roader
	.BYTE objects_twin_roader
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_pandeeta
	.BYTE objects_fan_up
	.BYTE objects_fan_up
	.BYTE objects_pandeeta
	.BYTE objects_fan_up
	.BYTE objects_fan_up
	.BYTE objects_scrolling
	.BYTE objects_pandeeta
	.BYTE objects_large_life_capsule
	.BYTE objects_large_weapon_capsule
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE -1
windman_objects_set_end:
