x1_objects_set:
;id
	.BYTE $00
	.BYTE $01
	.BYTE $01
	.BYTE $02
	.BYTE $02
	.BYTE $03
	.BYTE $03
	.BYTE $04
	.BYTE $04
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $07
	.BYTE $07
	.BYTE $07
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $09
	.BYTE $09
	.BYTE $09
	.BYTE $09
	.BYTE $0A
	.BYTE $0A
	.BYTE $0B
	.BYTE $0B
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0C
	.BYTE $0D
	.BYTE $0D
	.BYTE $0D
	.BYTE $0D
	.BYTE $0E
	.BYTE $0F
	.BYTE $0F
	.BYTE $0F
	.BYTE $10
	.BYTE $11
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $14
	.BYTE $14
	.BYTE $14
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE $15
	.BYTE -1

;x
	.BYTE $40
	.BYTE $72
	.BYTE $FE
	.BYTE $7D
	.BYTE $C0
	.BYTE $29
	.BYTE $80
	.BYTE $80
	.BYTE $B7
	.BYTE $16
	.BYTE $45
	.BYTE $80
	.BYTE $6D
	.BYTE $80
	.BYTE $A7
	.BYTE $80
	.BYTE $96
	.BYTE $B7
	.BYTE $69
	.BYTE $80
	.BYTE $B6
	.BYTE $40
	.BYTE $85
	.BYTE $98
	.BYTE $B5
	.BYTE $40
	.BYTE $DB
	.BYTE $10
	.BYTE $C9
	.BYTE $4D
	.BYTE $6F
	.BYTE $F0
	.BYTE $F1
	.BYTE $4A
	.BYTE $9A
	.BYTE $C0
	.BYTE $D1
	.BYTE $C0
	.BYTE $69
	.BYTE $B6
	.BYTE $C0
	.BYTE $C0
	.BYTE $C0
	.BYTE $6C
	.BYTE $74
	.BYTE $7B
	.BYTE $83
	.BYTE $8B
	.BYTE $92
	.BYTE $AF
	.BYTE $C0
	.BYTE $30
	.BYTE $52
	.BYTE $8F
	.BYTE $A2
	.BYTE $D1
	.BYTE $6F
	.BYTE $9D
	.BYTE $DE
	.BYTE $5C
	.BYTE $88
	.BYTE $88
	.BYTE $98
	.BYTE $98
	.BYTE $C0
	.BYTE -1

;y
	.BYTE $3A
	.BYTE $73
	.BYTE $94
	.BYTE $93
	.BYTE $3B
	.BYTE $97
	.BYTE $07
	.BYTE $07
	.BYTE $38
	.BYTE $33
	.BYTE $67
	.BYTE $07
	.BYTE $AF
	.BYTE $3C
	.BYTE $91
	.BYTE $07
	.BYTE $7F
	.BYTE $3D
	.BYTE $97
	.BYTE $6C
	.BYTE $3C
	.BYTE $19
	.BYTE $7E
	.BYTE $2F
	.BYTE $63
	.BYTE $00
	.BYTE $13
	.BYTE $2F
	.BYTE $2F
	.BYTE $16
	.BYTE $4E
	.BYTE $97
	.BYTE $3F
	.BYTE $6F
	.BYTE $1C
	.BYTE $01
	.BYTE $2C
	.BYTE $42
	.BYTE $6F
	.BYTE $4E
	.BYTE $3D
	.BYTE $4F
	.BYTE $77
	.BYTE $BB
	.BYTE $BB
	.BYTE $BB
	.BYTE $BB
	.BYTE $BB
	.BYTE $BB
	.BYTE $97
	.BYTE $00
	.BYTE $97
	.BYTE $77
	.BYTE $99
	.BYTE $99
	.BYTE $77
	.BYTE $77
	.BYTE $57
	.BYTE $37
	.BYTE $77
	.BYTE $77
	.BYTE $68
	.BYTE $68
	.BYTE $77
	.BYTE $3E
	.BYTE -1

;objects
	.BYTE objects_scrolling
	.BYTE objects_tatebo
	.BYTE objects_tatebo
	.BYTE objects_tatebo
	.BYTE objects_scrolling
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_cannopeller
	.BYTE objects_cannopeller
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_scrolling
	.BYTE objects_flip_platform
	.BYTE objects_scrolling
	.BYTE objects_flip_platform
	.BYTE objects_scrolling
	.BYTE objects_cannopeller
	.BYTE objects_cannopeller
	.BYTE objects_cyber_gabyoall_1
	.BYTE objects_scrolling
	.BYTE objects_cannopeller
	.BYTE objects_scrolling
	.BYTE objects_cannopeller
	.BYTE objects_cannopeller
	.BYTE objects_cannopeller
	.BYTE objects_scrolling
	.BYTE objects_hotchkissn
	.BYTE objects_skull_walker
	.BYTE objects_skull_walker
	.BYTE objects_hotchkissn
	.BYTE objects_skull_walker
	.BYTE objects_e_tank
	.BYTE objects_skull_walker
	.BYTE objects_skull_walker
	.BYTE objects_hotchkissn
	.BYTE objects_scrolling
	.BYTE objects_hotchkissn
	.BYTE objects_scrolling
	.BYTE objects_wall_blaster_ii_right
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_small_weapon_capsule
	.BYTE objects_small_weapon_capsule
	.BYTE objects_small_weapon_capsule
	.BYTE objects_small_weapon_capsule
	.BYTE objects_small_weapon_capsule
	.BYTE objects_small_weapon_capsule
	.BYTE objects_batabattan
	.BYTE objects_scrolling
	.BYTE objects_large_life_capsule
	.BYTE objects_batabattan
	.BYTE objects_large_weapon_capsule
	.BYTE objects_large_weapon_capsule
	.BYTE objects_batabattan
	.BYTE objects_batabattan
	.BYTE objects_batabattan
	.BYTE objects_batabattan
	.BYTE objects_batabattan
	.BYTE objects_1up
	.BYTE objects_1up
	.BYTE objects_1up
	.BYTE objects_1up
	.BYTE objects_scrolling
	.BYTE -1
x1_objects_set_end:
