x4_objects_set:
;id
	.BYTE $00
	.BYTE $00
	.BYTE $00
	.BYTE $01
	.BYTE $01
	.BYTE $01
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $07
	.BYTE $07
	.BYTE $07
	.BYTE $07
	.BYTE $07
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $09
	.BYTE $09
	.BYTE $09
	.BYTE $0A
	.BYTE $0A
	.BYTE $0B
	.BYTE $0B
	.BYTE $0C
	.BYTE $0C
	.BYTE $0D
	.BYTE $0D
	.BYTE $0D
	.BYTE $0E
	.BYTE $0E
	.BYTE $0E
	.BYTE $0E
	.BYTE $0F
	.BYTE $10
	.BYTE $10
	.BYTE $11
	.BYTE $11
	.BYTE $11
	.BYTE $11
	.BYTE $12
	.BYTE $12
	.BYTE $12
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $13
	.BYTE $14
	.BYTE $15
	.BYTE $16
	.BYTE $16
	.BYTE $17
	.BYTE $17
	.BYTE $18
	.BYTE $18
	.BYTE -1

;x
	.BYTE $3D
	.BYTE $80
	.BYTE $80
	.BYTE $47
	.BYTE $80
	.BYTE $96
	.BYTE $40
	.BYTE $D6
	.BYTE $F6
	.BYTE $16
	.BYTE $4F
	.BYTE $90
	.BYTE $D3
	.BYTE $DB
	.BYTE $E3
	.BYTE $EB
	.BYTE $F6
	.BYTE $0C
	.BYTE $2C
	.BYTE $34
	.BYTE $C8
	.BYTE $16
	.BYTE $70
	.BYTE $8F
	.BYTE $30
	.BYTE $4E
	.BYTE $A6
	.BYTE $28
	.BYTE $50
	.BYTE $B7
	.BYTE $C0
	.BYTE $D0
	.BYTE $75
	.BYTE $7F
	.BYTE $80
	.BYTE $80
	.BYTE $8C
	.BYTE $80
	.BYTE $B3
	.BYTE $D3
	.BYTE $80
	.BYTE $C1
	.BYTE $52
	.BYTE $F6
	.BYTE $66
	.BYTE $CE
	.BYTE $13
	.BYTE $72
	.BYTE $D4
	.BYTE $12
	.BYTE $86
	.BYTE $B5
	.BYTE $C0
	.BYTE $80
	.BYTE $40
	.BYTE $E8
	.BYTE $10
	.BYTE $30
	.BYTE $96
	.BYTE $B0
	.BYTE $76
	.BYTE $90
	.BYTE $A6
	.BYTE $28
	.BYTE $4E
	.BYTE $77
	.BYTE $90
	.BYTE $C0
	.BYTE $D6
	.BYTE $80
	.BYTE $80
	.BYTE $40
	.BYTE $F0
	.BYTE $70
	.BYTE $B0
	.BYTE $71
	.BYTE $C0
	.BYTE -1

;y
	.BYTE $78
	.BYTE $49
	.BYTE $69
	.BYTE $7F
	.BYTE $07
	.BYTE $7F
	.BYTE $08
	.BYTE $87
	.BYTE $67
	.BYTE $47
	.BYTE $37
	.BYTE $39
	.BYTE $BB
	.BYTE $BB
	.BYTE $BB
	.BYTE $BB
	.BYTE $46
	.BYTE $77
	.BYTE $3B
	.BYTE $3B
	.BYTE $A8
	.BYTE $A7
	.BYTE $8F
	.BYTE $B7
	.BYTE $6F
	.BYTE $B6
	.BYTE $77
	.BYTE $97
	.BYTE $B5
	.BYTE $8F
	.BYTE $0D
	.BYTE $75
	.BYTE $BB
	.BYTE $4F
	.BYTE $07
	.BYTE $BB
	.BYTE $BB
	.BYTE $4C
	.BYTE $AF
	.BYTE $8F
	.BYTE $08
	.BYTE $2D
	.BYTE $2D
	.BYTE $4D
	.BYTE $2D
	.BYTE $2D
	.BYTE $77
	.BYTE $57
	.BYTE $77
	.BYTE $57
	.BYTE $77
	.BYTE $77
	.BYTE $01
	.BYTE $02
	.BYTE $03
	.BYTE $B7
	.BYTE $4F
	.BYTE $B4
	.BYTE $8F
	.BYTE $74
	.BYTE $8F
	.BYTE $74
	.BYTE $56
	.BYTE $88
	.BYTE $B3
	.BYTE $AF
	.BYTE $94
	.BYTE $09
	.BYTE $4F
	.BYTE $6B
	.BYTE $70
	.BYTE $00
	.BYTE $6F
	.BYTE $6F
	.BYTE $3F
	.BYTE $5F
	.BYTE $4D
	.BYTE -1

;objects
	.BYTE objects_spike_platform
	.BYTE objects_large_weapon_capsule
	.BYTE objects_scrolling
	.BYTE objects_wall_blaster_ii_right
	.BYTE objects_scrolling
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_scrolling
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_large_life_capsule
	.BYTE objects_large_weapon_capsule
	.BYTE objects_small_weapon_capsule
	.BYTE objects_small_weapon_capsule
	.BYTE objects_small_weapon_capsule
	.BYTE objects_small_weapon_capsule
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_e_tank
	.BYTE objects_small_weapon_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_wall_blaster_ii_right
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_push_block
	.BYTE objects_peat_generator
	.BYTE objects_push_block
	.BYTE objects_peat_generator
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_wall_blaster_ii_right
	.BYTE objects_peat_generator
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_scrolling
	.BYTE objects_peat_generator
	.BYTE objects_small_life_capsule
	.BYTE objects_tadahou
	.BYTE objects_scrolling
	.BYTE objects_small_life_capsule
	.BYTE objects_small_life_capsule
	.BYTE objects_scrolling
	.BYTE objects_shield_attacker_gtr
	.BYTE objects_shield_attacker_gtr
	.BYTE objects_scrolling
	.BYTE objects_sw_525
	.BYTE objects_sw_525
	.BYTE objects_sw_525
	.BYTE objects_sw_525
	.BYTE objects_sw_525
	.BYTE objects_sw_525
	.BYTE objects_sw_525
	.BYTE objects_sw_525
	.BYTE objects_1up
	.BYTE objects_sw_525
	.BYTE objects_sw_525
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_e_tank
	.BYTE objects_push_block
	.BYTE objects_peat_generator
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_peat_generator
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_peat_generator
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_wall_blaster_ii_right
	.BYTE objects_peat_generator
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_peat_generator
	.BYTE objects_scrolling
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_colton
	.BYTE objects_colton
	.BYTE objects_colton
	.BYTE objects_colton
	.BYTE objects_scrolling
	.BYTE -1
x4_objects_set_end:
