wily3_objects_set:
;id
	.BYTE $00
	.BYTE $00
	.BYTE $01
	.BYTE $01
	.BYTE $01
	.BYTE $02
	.BYTE $02
	.BYTE $02
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $03
	.BYTE $04
	.BYTE $04
	.BYTE $04
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $05
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $06
	.BYTE $07
	.BYTE $07
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $08
	.BYTE $09
	.BYTE $0A
	.BYTE $0B
	.BYTE $0C
	.BYTE $0D
	.BYTE $0E
	.BYTE $0F
	.BYTE $10
	.BYTE -1

;x
	.BYTE $40
	.BYTE $78
	.BYTE $7A
	.BYTE $80
	.BYTE $A9
	.BYTE $0E
	.BYTE $47
	.BYTE $95
	.BYTE $1C
	.BYTE $7D
	.BYTE $CA
	.BYTE $F8
	.BYTE $14
	.BYTE $9F
	.BYTE $B0
	.BYTE $2F
	.BYTE $50
	.BYTE $69
	.BYTE $C0
	.BYTE $CE
	.BYTE $28
	.BYTE $28
	.BYTE $80
	.BYTE $D6
	.BYTE $80
	.BYTE $D1
	.BYTE $21
	.BYTE $21
	.BYTE $21
	.BYTE $71
	.BYTE $80
	.BYTE $81
	.BYTE $91
	.BYTE $E1
	.BYTE $E1
	.BYTE $E1
	.BYTE $80
	.BYTE $80
	.BYTE $80
	.BYTE $80
	.BYTE $80
	.BYTE $80
	.BYTE $80
	.BYTE $80
	.BYTE -1

;y
	.BYTE $53
	.BYTE $FF
	.BYTE $51
	.BYTE $99
	.BYTE $47
	.BYTE $B7
	.BYTE $53
	.BYTE $48
	.BYTE $73
	.BYTE $58
	.BYTE $87
	.BYTE $99
	.BYTE $53
	.BYTE $79
	.BYTE $70
	.BYTE $B7
	.BYTE $51
	.BYTE $67
	.BYTE $54
	.BYTE $43
	.BYTE $4F
	.BYTE $8F
	.BYTE $55
	.BYTE $6F
	.BYTE $56
	.BYTE $58
	.BYTE $68
	.BYTE $28
	.BYTE $A8
	.BYTE $A8
	.BYTE $71
	.BYTE $28
	.BYTE $A8
	.BYTE $A8
	.BYTE $68
	.BYTE $28
	.BYTE $72
	.BYTE $72
	.BYTE $72
	.BYTE $72
	.BYTE $72
	.BYTE $72
	.BYTE $72
	.BYTE $72
	.BYTE -1

;objects
	.BYTE objects_scrolling
	.BYTE objects_water
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_large_weapon_capsule
	.BYTE objects_yaffu
	.BYTE objects_e_tank
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_yaffu
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_yaffu
	.BYTE objects_large_weapon_capsule
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_large_weapon_capsule
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_large_life_capsule
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_yaffu
	.BYTE objects_scrolling
	.BYTE objects_gabgyo_horizontal
	.BYTE objects_wall_blaster_ii_right
	.BYTE objects_wall_blaster_ii_right
	.BYTE objects_scrolling
	.BYTE objects_wall_blaster_ii_left
	.BYTE objects_scrolling
	.BYTE objects_teleport
	.BYTE objects_teleport
	.BYTE objects_teleport
	.BYTE objects_teleport
	.BYTE objects_teleport
	.BYTE objects_scrolling
	.BYTE objects_teleport
	.BYTE objects_teleport
	.BYTE objects_teleport
	.BYTE objects_teleport
	.BYTE objects_teleport
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE objects_scrolling
	.BYTE -1
wily3_objects_set_end:
