palettes_set_0_lo_pointers:
	.LOBYTES palettes_set_000
	.LOBYTES palettes_set_001
	.LOBYTES palettes_set_002
	.LOBYTES palettes_set_003
	.LOBYTES palettes_set_004
	.LOBYTES palettes_set_005
	.LOBYTES palettes_set_006
	.LOBYTES palettes_set_007
	.LOBYTES palettes_set_008
	.LOBYTES palettes_set_009
	.LOBYTES palettes_set_00a
	.LOBYTES palettes_set_00b
	.LOBYTES palettes_set_00c
	.LOBYTES palettes_set_00d
	.LOBYTES palettes_set_00e
	.LOBYTES palettes_set_00f
	.LOBYTES palettes_set_010
	.LOBYTES palettes_set_011
	.LOBYTES palettes_set_012
	.LOBYTES palettes_set_013
	.LOBYTES palettes_set_014
	.LOBYTES palettes_set_015
	.LOBYTES palettes_set_016
	.LOBYTES palettes_set_017
	.LOBYTES palettes_set_018
	.LOBYTES palettes_set_019
	.LOBYTES palettes_set_01a
	.LOBYTES palettes_set_01b
	.LOBYTES palettes_set_01c
	.LOBYTES palettes_set_01d
	.LOBYTES palettes_set_01e
	.LOBYTES palettes_set_01f
	.LOBYTES palettes_set_020
	.LOBYTES palettes_set_021
	.LOBYTES palettes_set_022
	.LOBYTES palettes_set_023
	.LOBYTES palettes_set_024
	.LOBYTES palettes_set_025
	.LOBYTES palettes_set_026
	.LOBYTES palettes_set_027
	.LOBYTES palettes_set_028
	.LOBYTES palettes_set_029
	.LOBYTES palettes_set_02a
	.LOBYTES palettes_set_02b
	.LOBYTES palettes_set_02c
	.LOBYTES palettes_set_02d
	.LOBYTES palettes_set_02e
	.LOBYTES palettes_set_02f
	.LOBYTES palettes_set_030
	.LOBYTES palettes_set_031
	.LOBYTES palettes_set_032
	.LOBYTES palettes_set_033
	.LOBYTES palettes_set_034
	.LOBYTES palettes_set_035
	.LOBYTES palettes_set_036
	.LOBYTES palettes_set_037
	.LOBYTES palettes_set_038
	.LOBYTES palettes_set_039
	.LOBYTES palettes_set_03a
	.LOBYTES palettes_set_03b
	.LOBYTES palettes_set_03c
	.LOBYTES palettes_set_03d
	.LOBYTES palettes_set_03e
	.LOBYTES palettes_set_03f
	.LOBYTES palettes_set_040
	.LOBYTES palettes_set_041
	.LOBYTES palettes_set_042
	.LOBYTES palettes_set_043
	.LOBYTES palettes_set_044
	.LOBYTES palettes_set_045
	.LOBYTES palettes_set_046
	.LOBYTES palettes_set_047
	.LOBYTES palettes_set_048
	.LOBYTES palettes_set_049
	.LOBYTES palettes_set_04a
	.LOBYTES palettes_set_04b
	.LOBYTES palettes_set_04c
	.LOBYTES palettes_set_04d
	.LOBYTES palettes_set_04e
	.LOBYTES palettes_set_04f
	.LOBYTES palettes_set_050
	.LOBYTES palettes_set_051
	.LOBYTES palettes_set_052
	.LOBYTES palettes_set_053
	.LOBYTES palettes_set_054
	.LOBYTES palettes_set_055
	.LOBYTES palettes_set_056
	.LOBYTES palettes_set_057
	.LOBYTES palettes_set_058
	.LOBYTES palettes_set_059
	.LOBYTES palettes_set_05a
	.LOBYTES palettes_set_05b
	.LOBYTES palettes_set_05c
	.LOBYTES palettes_set_05d
	.LOBYTES palettes_set_05e
	.LOBYTES palettes_set_05f
	.LOBYTES palettes_set_060
	.LOBYTES palettes_set_061
	.LOBYTES palettes_set_062
	.LOBYTES palettes_set_063
	.LOBYTES palettes_set_064
	.LOBYTES palettes_set_065
	.LOBYTES palettes_set_066
	.LOBYTES palettes_set_067
	.LOBYTES palettes_set_068
	.LOBYTES palettes_set_069
	.LOBYTES palettes_set_06a
	.LOBYTES palettes_set_06b
	.LOBYTES palettes_set_06c
	.LOBYTES palettes_set_06d
	.LOBYTES palettes_set_06e
	.LOBYTES palettes_set_06f
	.LOBYTES palettes_set_070
	.LOBYTES palettes_set_071
	.LOBYTES palettes_set_072
	.LOBYTES palettes_set_073
	.LOBYTES palettes_set_074
	.LOBYTES palettes_set_075
	.LOBYTES palettes_set_076
	.LOBYTES palettes_set_077
	.LOBYTES palettes_set_078
	.LOBYTES palettes_set_079
	.LOBYTES palettes_set_07a
	.LOBYTES palettes_set_07b
	.LOBYTES palettes_set_07c
	.LOBYTES palettes_set_07d
	.LOBYTES palettes_set_07e
	.LOBYTES palettes_set_07f
	.LOBYTES palettes_set_080
	.LOBYTES palettes_set_081
	.LOBYTES palettes_set_082
	.LOBYTES palettes_set_083
	.LOBYTES palettes_set_084
	.LOBYTES palettes_set_085
	.LOBYTES palettes_set_086
	.LOBYTES palettes_set_087
	.LOBYTES palettes_set_088
	.LOBYTES palettes_set_089
	.LOBYTES palettes_set_08a
	.LOBYTES palettes_set_08b
	.LOBYTES palettes_set_08c
	.LOBYTES palettes_set_08d
	.LOBYTES palettes_set_08e
	.LOBYTES palettes_set_08f
	.LOBYTES palettes_set_090
	.LOBYTES palettes_set_091
	.LOBYTES palettes_set_092
	.LOBYTES palettes_set_093
	.LOBYTES palettes_set_094
	.LOBYTES palettes_set_095
	.LOBYTES palettes_set_096
	.LOBYTES palettes_set_097
	.LOBYTES palettes_set_098
	.LOBYTES palettes_set_099
	.LOBYTES palettes_set_09a
	.LOBYTES palettes_set_09b
	.LOBYTES palettes_set_09c
	.LOBYTES palettes_set_09d
	.LOBYTES palettes_set_09e
	.LOBYTES palettes_set_09f
	.LOBYTES palettes_set_0a0
	.LOBYTES palettes_set_0a1
	.LOBYTES palettes_set_0a2
	.LOBYTES palettes_set_0a3
	.LOBYTES palettes_set_0a4
	.LOBYTES palettes_set_0a5
	.LOBYTES palettes_set_0a6
	.LOBYTES palettes_set_0a7
	.LOBYTES palettes_set_0a8
	.LOBYTES palettes_set_0a9
	.LOBYTES palettes_set_0aa
	.LOBYTES palettes_set_0ab
	.LOBYTES palettes_set_0ac
	.LOBYTES palettes_set_0ad
	.LOBYTES palettes_set_0ae
	.LOBYTES palettes_set_0af
	.LOBYTES palettes_set_0b0
	.LOBYTES palettes_set_0b1
	.LOBYTES palettes_set_0b2
	.LOBYTES palettes_set_0b3
	.LOBYTES palettes_set_0b4
	.LOBYTES palettes_set_0b5
	.LOBYTES palettes_set_0b6
	.LOBYTES palettes_set_0b7
	.LOBYTES palettes_set_0b8
	.LOBYTES palettes_set_0b9
	.LOBYTES palettes_set_0ba
	.LOBYTES palettes_set_0bb
	.LOBYTES palettes_set_0bc
	.LOBYTES palettes_set_0bd
	.LOBYTES palettes_set_0be
	.LOBYTES palettes_set_0bf
	.LOBYTES palettes_set_0c0
	.LOBYTES palettes_set_0c1
	.LOBYTES palettes_set_0c2
	.LOBYTES palettes_set_0c3
	.LOBYTES palettes_set_0c4
	.LOBYTES palettes_set_0c5
	.LOBYTES palettes_set_0c6
	.LOBYTES palettes_set_0c7
	.LOBYTES palettes_set_0c8
	.LOBYTES palettes_set_0c9
	.LOBYTES palettes_set_0ca
	.LOBYTES palettes_set_0cb
	.LOBYTES palettes_set_0cc
	.LOBYTES palettes_set_0cd
	.LOBYTES palettes_set_0ce
	.LOBYTES palettes_set_0cf
	.LOBYTES palettes_set_0d0
	.LOBYTES palettes_set_0d1
	.LOBYTES palettes_set_0d2
	.LOBYTES palettes_set_0d3
	.LOBYTES palettes_set_0d4
	.LOBYTES palettes_set_0d5
	.LOBYTES palettes_set_0d6
	.LOBYTES palettes_set_0d7
	.LOBYTES palettes_set_0d8
	.LOBYTES palettes_set_0d9
	.LOBYTES palettes_set_0da
	.LOBYTES palettes_set_0db
	.LOBYTES palettes_set_0dc
	.LOBYTES palettes_set_0dd
	.LOBYTES palettes_set_0de
	.LOBYTES palettes_set_0df
	.LOBYTES palettes_set_0e0
	.LOBYTES palettes_set_0e1
	.LOBYTES palettes_set_0e2
	.LOBYTES palettes_set_0e3
	.LOBYTES palettes_set_0e4
	.LOBYTES palettes_set_0e5
	.LOBYTES palettes_set_0e6
	.LOBYTES palettes_set_0e7
	.LOBYTES palettes_set_0e8
	.LOBYTES palettes_set_0e9
	.LOBYTES palettes_set_0ea
	.LOBYTES palettes_set_0eb
	.LOBYTES palettes_set_0ec
	.LOBYTES palettes_set_0ed
	.LOBYTES palettes_set_0ee
	.LOBYTES palettes_set_0ef
	.LOBYTES palettes_set_0f0
	.LOBYTES palettes_set_0f1
	.LOBYTES palettes_set_0f2
	.LOBYTES palettes_set_0f3
	.LOBYTES palettes_set_0f4
	.LOBYTES palettes_set_0f5
	.LOBYTES palettes_set_0f6
	.LOBYTES palettes_set_0f7
	.LOBYTES palettes_set_0f8
	.LOBYTES palettes_set_0f9
	.LOBYTES palettes_set_0fa
	.LOBYTES palettes_set_0fb
	.LOBYTES palettes_set_0fc
	.LOBYTES palettes_set_0fd
	.LOBYTES palettes_set_0fe
	.LOBYTES palettes_set_0ff

palettes_set_0_hi_pointers:
	.HIBYTES palettes_set_000
	.HIBYTES palettes_set_001
	.HIBYTES palettes_set_002
	.HIBYTES palettes_set_003
	.HIBYTES palettes_set_004
	.HIBYTES palettes_set_005
	.HIBYTES palettes_set_006
	.HIBYTES palettes_set_007
	.HIBYTES palettes_set_008
	.HIBYTES palettes_set_009
	.HIBYTES palettes_set_00a
	.HIBYTES palettes_set_00b
	.HIBYTES palettes_set_00c
	.HIBYTES palettes_set_00d
	.HIBYTES palettes_set_00e
	.HIBYTES palettes_set_00f
	.HIBYTES palettes_set_010
	.HIBYTES palettes_set_011
	.HIBYTES palettes_set_012
	.HIBYTES palettes_set_013
	.HIBYTES palettes_set_014
	.HIBYTES palettes_set_015
	.HIBYTES palettes_set_016
	.HIBYTES palettes_set_017
	.HIBYTES palettes_set_018
	.HIBYTES palettes_set_019
	.HIBYTES palettes_set_01a
	.HIBYTES palettes_set_01b
	.HIBYTES palettes_set_01c
	.HIBYTES palettes_set_01d
	.HIBYTES palettes_set_01e
	.HIBYTES palettes_set_01f
	.HIBYTES palettes_set_020
	.HIBYTES palettes_set_021
	.HIBYTES palettes_set_022
	.HIBYTES palettes_set_023
	.HIBYTES palettes_set_024
	.HIBYTES palettes_set_025
	.HIBYTES palettes_set_026
	.HIBYTES palettes_set_027
	.HIBYTES palettes_set_028
	.HIBYTES palettes_set_029
	.HIBYTES palettes_set_02a
	.HIBYTES palettes_set_02b
	.HIBYTES palettes_set_02c
	.HIBYTES palettes_set_02d
	.HIBYTES palettes_set_02e
	.HIBYTES palettes_set_02f
	.HIBYTES palettes_set_030
	.HIBYTES palettes_set_031
	.HIBYTES palettes_set_032
	.HIBYTES palettes_set_033
	.HIBYTES palettes_set_034
	.HIBYTES palettes_set_035
	.HIBYTES palettes_set_036
	.HIBYTES palettes_set_037
	.HIBYTES palettes_set_038
	.HIBYTES palettes_set_039
	.HIBYTES palettes_set_03a
	.HIBYTES palettes_set_03b
	.HIBYTES palettes_set_03c
	.HIBYTES palettes_set_03d
	.HIBYTES palettes_set_03e
	.HIBYTES palettes_set_03f
	.HIBYTES palettes_set_040
	.HIBYTES palettes_set_041
	.HIBYTES palettes_set_042
	.HIBYTES palettes_set_043
	.HIBYTES palettes_set_044
	.HIBYTES palettes_set_045
	.HIBYTES palettes_set_046
	.HIBYTES palettes_set_047
	.HIBYTES palettes_set_048
	.HIBYTES palettes_set_049
	.HIBYTES palettes_set_04a
	.HIBYTES palettes_set_04b
	.HIBYTES palettes_set_04c
	.HIBYTES palettes_set_04d
	.HIBYTES palettes_set_04e
	.HIBYTES palettes_set_04f
	.HIBYTES palettes_set_050
	.HIBYTES palettes_set_051
	.HIBYTES palettes_set_052
	.HIBYTES palettes_set_053
	.HIBYTES palettes_set_054
	.HIBYTES palettes_set_055
	.HIBYTES palettes_set_056
	.HIBYTES palettes_set_057
	.HIBYTES palettes_set_058
	.HIBYTES palettes_set_059
	.HIBYTES palettes_set_05a
	.HIBYTES palettes_set_05b
	.HIBYTES palettes_set_05c
	.HIBYTES palettes_set_05d
	.HIBYTES palettes_set_05e
	.HIBYTES palettes_set_05f
	.HIBYTES palettes_set_060
	.HIBYTES palettes_set_061
	.HIBYTES palettes_set_062
	.HIBYTES palettes_set_063
	.HIBYTES palettes_set_064
	.HIBYTES palettes_set_065
	.HIBYTES palettes_set_066
	.HIBYTES palettes_set_067
	.HIBYTES palettes_set_068
	.HIBYTES palettes_set_069
	.HIBYTES palettes_set_06a
	.HIBYTES palettes_set_06b
	.HIBYTES palettes_set_06c
	.HIBYTES palettes_set_06d
	.HIBYTES palettes_set_06e
	.HIBYTES palettes_set_06f
	.HIBYTES palettes_set_070
	.HIBYTES palettes_set_071
	.HIBYTES palettes_set_072
	.HIBYTES palettes_set_073
	.HIBYTES palettes_set_074
	.HIBYTES palettes_set_075
	.HIBYTES palettes_set_076
	.HIBYTES palettes_set_077
	.HIBYTES palettes_set_078
	.HIBYTES palettes_set_079
	.HIBYTES palettes_set_07a
	.HIBYTES palettes_set_07b
	.HIBYTES palettes_set_07c
	.HIBYTES palettes_set_07d
	.HIBYTES palettes_set_07e
	.HIBYTES palettes_set_07f
	.HIBYTES palettes_set_080
	.HIBYTES palettes_set_081
	.HIBYTES palettes_set_082
	.HIBYTES palettes_set_083
	.HIBYTES palettes_set_084
	.HIBYTES palettes_set_085
	.HIBYTES palettes_set_086
	.HIBYTES palettes_set_087
	.HIBYTES palettes_set_088
	.HIBYTES palettes_set_089
	.HIBYTES palettes_set_08a
	.HIBYTES palettes_set_08b
	.HIBYTES palettes_set_08c
	.HIBYTES palettes_set_08d
	.HIBYTES palettes_set_08e
	.HIBYTES palettes_set_08f
	.HIBYTES palettes_set_090
	.HIBYTES palettes_set_091
	.HIBYTES palettes_set_092
	.HIBYTES palettes_set_093
	.HIBYTES palettes_set_094
	.HIBYTES palettes_set_095
	.HIBYTES palettes_set_096
	.HIBYTES palettes_set_097
	.HIBYTES palettes_set_098
	.HIBYTES palettes_set_099
	.HIBYTES palettes_set_09a
	.HIBYTES palettes_set_09b
	.HIBYTES palettes_set_09c
	.HIBYTES palettes_set_09d
	.HIBYTES palettes_set_09e
	.HIBYTES palettes_set_09f
	.HIBYTES palettes_set_0a0
	.HIBYTES palettes_set_0a1
	.HIBYTES palettes_set_0a2
	.HIBYTES palettes_set_0a3
	.HIBYTES palettes_set_0a4
	.HIBYTES palettes_set_0a5
	.HIBYTES palettes_set_0a6
	.HIBYTES palettes_set_0a7
	.HIBYTES palettes_set_0a8
	.HIBYTES palettes_set_0a9
	.HIBYTES palettes_set_0aa
	.HIBYTES palettes_set_0ab
	.HIBYTES palettes_set_0ac
	.HIBYTES palettes_set_0ad
	.HIBYTES palettes_set_0ae
	.HIBYTES palettes_set_0af
	.HIBYTES palettes_set_0b0
	.HIBYTES palettes_set_0b1
	.HIBYTES palettes_set_0b2
	.HIBYTES palettes_set_0b3
	.HIBYTES palettes_set_0b4
	.HIBYTES palettes_set_0b5
	.HIBYTES palettes_set_0b6
	.HIBYTES palettes_set_0b7
	.HIBYTES palettes_set_0b8
	.HIBYTES palettes_set_0b9
	.HIBYTES palettes_set_0ba
	.HIBYTES palettes_set_0bb
	.HIBYTES palettes_set_0bc
	.HIBYTES palettes_set_0bd
	.HIBYTES palettes_set_0be
	.HIBYTES palettes_set_0bf
	.HIBYTES palettes_set_0c0
	.HIBYTES palettes_set_0c1
	.HIBYTES palettes_set_0c2
	.HIBYTES palettes_set_0c3
	.HIBYTES palettes_set_0c4
	.HIBYTES palettes_set_0c5
	.HIBYTES palettes_set_0c6
	.HIBYTES palettes_set_0c7
	.HIBYTES palettes_set_0c8
	.HIBYTES palettes_set_0c9
	.HIBYTES palettes_set_0ca
	.HIBYTES palettes_set_0cb
	.HIBYTES palettes_set_0cc
	.HIBYTES palettes_set_0cd
	.HIBYTES palettes_set_0ce
	.HIBYTES palettes_set_0cf
	.HIBYTES palettes_set_0d0
	.HIBYTES palettes_set_0d1
	.HIBYTES palettes_set_0d2
	.HIBYTES palettes_set_0d3
	.HIBYTES palettes_set_0d4
	.HIBYTES palettes_set_0d5
	.HIBYTES palettes_set_0d6
	.HIBYTES palettes_set_0d7
	.HIBYTES palettes_set_0d8
	.HIBYTES palettes_set_0d9
	.HIBYTES palettes_set_0da
	.HIBYTES palettes_set_0db
	.HIBYTES palettes_set_0dc
	.HIBYTES palettes_set_0dd
	.HIBYTES palettes_set_0de
	.HIBYTES palettes_set_0df
	.HIBYTES palettes_set_0e0
	.HIBYTES palettes_set_0e1
	.HIBYTES palettes_set_0e2
	.HIBYTES palettes_set_0e3
	.HIBYTES palettes_set_0e4
	.HIBYTES palettes_set_0e5
	.HIBYTES palettes_set_0e6
	.HIBYTES palettes_set_0e7
	.HIBYTES palettes_set_0e8
	.HIBYTES palettes_set_0e9
	.HIBYTES palettes_set_0ea
	.HIBYTES palettes_set_0eb
	.HIBYTES palettes_set_0ec
	.HIBYTES palettes_set_0ed
	.HIBYTES palettes_set_0ee
	.HIBYTES palettes_set_0ef
	.HIBYTES palettes_set_0f0
	.HIBYTES palettes_set_0f1
	.HIBYTES palettes_set_0f2
	.HIBYTES palettes_set_0f3
	.HIBYTES palettes_set_0f4
	.HIBYTES palettes_set_0f5
	.HIBYTES palettes_set_0f6
	.HIBYTES palettes_set_0f7
	.HIBYTES palettes_set_0f8
	.HIBYTES palettes_set_0f9
	.HIBYTES palettes_set_0fa
	.HIBYTES palettes_set_0fb
	.HIBYTES palettes_set_0fc
	.HIBYTES palettes_set_0fd
	.HIBYTES palettes_set_0fe
	.HIBYTES palettes_set_0ff
