palettes_set_1_lo_pointers:
	.LOBYTES palettes_set_100
	.LOBYTES palettes_set_101
	.LOBYTES palettes_set_102
	.LOBYTES palettes_set_103
	.LOBYTES palettes_set_104
	.LOBYTES palettes_set_105
	.LOBYTES palettes_set_106
	.LOBYTES palettes_set_107
	.LOBYTES palettes_set_108
	.LOBYTES palettes_set_109
	.LOBYTES palettes_set_10a
	.LOBYTES palettes_set_10b
	.LOBYTES palettes_set_10c
	.LOBYTES palettes_set_10d
	.LOBYTES palettes_set_10e
	.LOBYTES palettes_set_10f
	.LOBYTES palettes_set_110
	.LOBYTES palettes_set_111
	.LOBYTES palettes_set_112
	.LOBYTES palettes_set_113
	.LOBYTES palettes_set_114
	.LOBYTES palettes_set_115
	.LOBYTES palettes_set_116
	.LOBYTES palettes_set_117
	.LOBYTES palettes_set_118
	.LOBYTES palettes_set_119
	.LOBYTES palettes_set_11a
	.LOBYTES palettes_set_11b
	.LOBYTES palettes_set_11c
	.LOBYTES palettes_set_11d
	.LOBYTES palettes_set_11e
	.LOBYTES palettes_set_11f
	.LOBYTES palettes_set_120
	.LOBYTES palettes_set_121
	.LOBYTES palettes_set_122
	.LOBYTES palettes_set_123
	.LOBYTES palettes_set_124
	.LOBYTES palettes_set_125
	.LOBYTES palettes_set_126
	.LOBYTES palettes_set_127
	.LOBYTES palettes_set_128
	.LOBYTES palettes_set_129
	.LOBYTES palettes_set_12a
	.LOBYTES palettes_set_12b
	.LOBYTES palettes_set_12c
	.LOBYTES palettes_set_12d
	.LOBYTES palettes_set_12e
	.LOBYTES palettes_set_12f
	.LOBYTES palettes_set_130
	.LOBYTES palettes_set_131
	.LOBYTES palettes_set_132
	.LOBYTES palettes_set_133
	.LOBYTES palettes_set_134
	.LOBYTES palettes_set_135
	.LOBYTES palettes_set_136
	.LOBYTES palettes_set_137
	.LOBYTES palettes_set_138
	.LOBYTES palettes_set_139
	.LOBYTES palettes_set_13a
	.LOBYTES palettes_set_13b
	.LOBYTES palettes_set_13c
	.LOBYTES palettes_set_13d
	.LOBYTES palettes_set_13e
	.LOBYTES palettes_set_13f
	.LOBYTES palettes_set_140
	.LOBYTES palettes_set_141
	.LOBYTES palettes_set_142
	.LOBYTES palettes_set_143
	.LOBYTES palettes_set_144
	.LOBYTES palettes_set_145
	.LOBYTES palettes_set_146
	.LOBYTES palettes_set_147
	.LOBYTES palettes_set_148
	.LOBYTES palettes_set_149
	.LOBYTES palettes_set_14a
	.LOBYTES palettes_set_14b
	.LOBYTES palettes_set_14c
	.LOBYTES palettes_set_14d
	.LOBYTES palettes_set_14e
	.LOBYTES palettes_set_14f
	.LOBYTES palettes_set_150
	.LOBYTES palettes_set_151
	.LOBYTES palettes_set_152
	.LOBYTES palettes_set_153
	.LOBYTES palettes_set_154
	.LOBYTES palettes_set_155
	.LOBYTES palettes_set_156
	.LOBYTES palettes_set_157
	.LOBYTES palettes_set_158
	.LOBYTES palettes_set_159
	.LOBYTES palettes_set_15a
	.LOBYTES palettes_set_15b
	.LOBYTES palettes_set_15c
	.LOBYTES palettes_set_15d
	.LOBYTES palettes_set_15e
	.LOBYTES palettes_set_15f
	.LOBYTES palettes_set_160
	.LOBYTES palettes_set_161
	.LOBYTES palettes_set_162
	.LOBYTES palettes_set_163
	.LOBYTES palettes_set_164
	.LOBYTES palettes_set_165
	.LOBYTES palettes_set_166
	.LOBYTES palettes_set_167
	.LOBYTES palettes_set_168
	.LOBYTES palettes_set_169
	.LOBYTES palettes_set_16a
	.LOBYTES palettes_set_16b
	.LOBYTES palettes_set_16c
	.LOBYTES palettes_set_16d
	.LOBYTES palettes_set_16e
	.LOBYTES palettes_set_16f
	.LOBYTES palettes_set_170
	.LOBYTES palettes_set_171
	.LOBYTES palettes_set_172
	.LOBYTES palettes_set_173
	.LOBYTES palettes_set_174
	.LOBYTES palettes_set_175
	.LOBYTES palettes_set_176
	.LOBYTES palettes_set_177
	.LOBYTES palettes_set_178
	.LOBYTES palettes_set_179
	.LOBYTES palettes_set_17a
	.LOBYTES palettes_set_17b
	.LOBYTES palettes_set_17c
	.LOBYTES palettes_set_17d
	.LOBYTES palettes_set_17e
	.LOBYTES palettes_set_17f
	.LOBYTES palettes_set_180
	.LOBYTES palettes_set_181
	.LOBYTES palettes_set_182
	.LOBYTES palettes_set_183
	.LOBYTES palettes_set_184
	.LOBYTES palettes_set_185
	.LOBYTES palettes_set_186
	.LOBYTES palettes_set_187
	.LOBYTES palettes_set_188
	.LOBYTES palettes_set_189
	.LOBYTES palettes_set_18a
	.LOBYTES palettes_set_18b
	.LOBYTES palettes_set_18c
	.LOBYTES palettes_set_18d
	.LOBYTES palettes_set_18e
	.LOBYTES palettes_set_18f
	.LOBYTES palettes_set_190
	.LOBYTES palettes_set_191
	.LOBYTES palettes_set_192
	.LOBYTES palettes_set_193
	.LOBYTES palettes_set_194
	.LOBYTES palettes_set_195
	.LOBYTES palettes_set_196
	.LOBYTES palettes_set_197
	.LOBYTES palettes_set_198
	.LOBYTES palettes_set_199
	.LOBYTES palettes_set_19a
	.LOBYTES palettes_set_19b
	.LOBYTES palettes_set_19c
	.LOBYTES palettes_set_19d
	.LOBYTES palettes_set_19e
	.LOBYTES palettes_set_19f
	.LOBYTES palettes_set_1a0
	.LOBYTES palettes_set_1a1
	.LOBYTES palettes_set_1a2
	.LOBYTES palettes_set_1a3
	.LOBYTES palettes_set_1a4
	.LOBYTES palettes_set_1a5
	.LOBYTES palettes_set_1a6
	.LOBYTES palettes_set_1a7
	.LOBYTES palettes_set_1a8
	.LOBYTES palettes_set_1a9
	.LOBYTES palettes_set_1aa
	.LOBYTES palettes_set_1ab
	.LOBYTES palettes_set_1ac
	.LOBYTES palettes_set_1ad
	.LOBYTES palettes_set_1ae
	.LOBYTES palettes_set_1af
	.LOBYTES palettes_set_1b0
	.LOBYTES palettes_set_1b1
	.LOBYTES palettes_set_1b2
	.LOBYTES palettes_set_1b3
	.LOBYTES palettes_set_1b4
	.LOBYTES palettes_set_1b5
	.LOBYTES palettes_set_1b6
	.LOBYTES palettes_set_1b7
	.LOBYTES palettes_set_1b8
	.LOBYTES palettes_set_1b9
	.LOBYTES palettes_set_1ba
	.LOBYTES palettes_set_1bb
	.LOBYTES palettes_set_1bc
	.LOBYTES palettes_set_1bd
	.LOBYTES palettes_set_1be
	.LOBYTES palettes_set_1bf
	.LOBYTES palettes_set_1c0
	.LOBYTES palettes_set_1c1
	.LOBYTES palettes_set_1c2
	.LOBYTES palettes_set_1c3
	.LOBYTES palettes_set_1c4
	.LOBYTES palettes_set_1c5
	.LOBYTES palettes_set_1c6
	.LOBYTES palettes_set_1c7
	.LOBYTES palettes_set_1c8
	.LOBYTES palettes_set_1c9
	.LOBYTES palettes_set_1ca
	.LOBYTES palettes_set_1cb
	.LOBYTES palettes_set_1cc
	.LOBYTES palettes_set_1cd
	.LOBYTES palettes_set_1ce
	.LOBYTES palettes_set_1cf
	.LOBYTES palettes_set_1d0
	.LOBYTES palettes_set_1d1
	.LOBYTES palettes_set_1d2
	.LOBYTES palettes_set_1d3
	.LOBYTES palettes_set_1d4
	.LOBYTES palettes_set_1d5
	.LOBYTES palettes_set_1d6
	.LOBYTES palettes_set_1d7
	.LOBYTES palettes_set_1d8
	.LOBYTES palettes_set_1d9
	.LOBYTES palettes_set_1da
	.LOBYTES palettes_set_1db
	.LOBYTES palettes_set_1dc
	.LOBYTES palettes_set_1dd
	.LOBYTES palettes_set_1de
	.LOBYTES palettes_set_1df
	.LOBYTES palettes_set_1e0
	.LOBYTES palettes_set_1e1
	.LOBYTES palettes_set_1e2
	.LOBYTES palettes_set_1e3
	.LOBYTES palettes_set_1e4
	.LOBYTES palettes_set_1e5
	.LOBYTES palettes_set_1e6
	.LOBYTES palettes_set_1e7
	.LOBYTES palettes_set_1e8
	.LOBYTES palettes_set_1e9
	.LOBYTES palettes_set_1ea
	.LOBYTES palettes_set_1eb
	.LOBYTES palettes_set_1ec
	.LOBYTES palettes_set_1ed
	.LOBYTES palettes_set_1ee
	.LOBYTES palettes_set_1ef
	.LOBYTES palettes_set_1f0
	.LOBYTES palettes_set_1f1
	.LOBYTES palettes_set_1f2
	.LOBYTES palettes_set_1f3
	.LOBYTES palettes_set_1f4
	.LOBYTES palettes_set_1f5
	.LOBYTES palettes_set_1f6
	.LOBYTES palettes_set_1f7
	.LOBYTES palettes_set_1f8
	.LOBYTES palettes_set_1f9
	.LOBYTES palettes_set_1fa
	.LOBYTES palettes_set_1fb
	.LOBYTES palettes_set_1fc
	.LOBYTES palettes_set_1fd
	.LOBYTES palettes_set_1fe
	.LOBYTES palettes_set_1ff

palettes_set_1_hi_pointers:
	.HIBYTES palettes_set_100
	.HIBYTES palettes_set_101
	.HIBYTES palettes_set_102
	.HIBYTES palettes_set_103
	.HIBYTES palettes_set_104
	.HIBYTES palettes_set_105
	.HIBYTES palettes_set_106
	.HIBYTES palettes_set_107
	.HIBYTES palettes_set_108
	.HIBYTES palettes_set_109
	.HIBYTES palettes_set_10a
	.HIBYTES palettes_set_10b
	.HIBYTES palettes_set_10c
	.HIBYTES palettes_set_10d
	.HIBYTES palettes_set_10e
	.HIBYTES palettes_set_10f
	.HIBYTES palettes_set_110
	.HIBYTES palettes_set_111
	.HIBYTES palettes_set_112
	.HIBYTES palettes_set_113
	.HIBYTES palettes_set_114
	.HIBYTES palettes_set_115
	.HIBYTES palettes_set_116
	.HIBYTES palettes_set_117
	.HIBYTES palettes_set_118
	.HIBYTES palettes_set_119
	.HIBYTES palettes_set_11a
	.HIBYTES palettes_set_11b
	.HIBYTES palettes_set_11c
	.HIBYTES palettes_set_11d
	.HIBYTES palettes_set_11e
	.HIBYTES palettes_set_11f
	.HIBYTES palettes_set_120
	.HIBYTES palettes_set_121
	.HIBYTES palettes_set_122
	.HIBYTES palettes_set_123
	.HIBYTES palettes_set_124
	.HIBYTES palettes_set_125
	.HIBYTES palettes_set_126
	.HIBYTES palettes_set_127
	.HIBYTES palettes_set_128
	.HIBYTES palettes_set_129
	.HIBYTES palettes_set_12a
	.HIBYTES palettes_set_12b
	.HIBYTES palettes_set_12c
	.HIBYTES palettes_set_12d
	.HIBYTES palettes_set_12e
	.HIBYTES palettes_set_12f
	.HIBYTES palettes_set_130
	.HIBYTES palettes_set_131
	.HIBYTES palettes_set_132
	.HIBYTES palettes_set_133
	.HIBYTES palettes_set_134
	.HIBYTES palettes_set_135
	.HIBYTES palettes_set_136
	.HIBYTES palettes_set_137
	.HIBYTES palettes_set_138
	.HIBYTES palettes_set_139
	.HIBYTES palettes_set_13a
	.HIBYTES palettes_set_13b
	.HIBYTES palettes_set_13c
	.HIBYTES palettes_set_13d
	.HIBYTES palettes_set_13e
	.HIBYTES palettes_set_13f
	.HIBYTES palettes_set_140
	.HIBYTES palettes_set_141
	.HIBYTES palettes_set_142
	.HIBYTES palettes_set_143
	.HIBYTES palettes_set_144
	.HIBYTES palettes_set_145
	.HIBYTES palettes_set_146
	.HIBYTES palettes_set_147
	.HIBYTES palettes_set_148
	.HIBYTES palettes_set_149
	.HIBYTES palettes_set_14a
	.HIBYTES palettes_set_14b
	.HIBYTES palettes_set_14c
	.HIBYTES palettes_set_14d
	.HIBYTES palettes_set_14e
	.HIBYTES palettes_set_14f
	.HIBYTES palettes_set_150
	.HIBYTES palettes_set_151
	.HIBYTES palettes_set_152
	.HIBYTES palettes_set_153
	.HIBYTES palettes_set_154
	.HIBYTES palettes_set_155
	.HIBYTES palettes_set_156
	.HIBYTES palettes_set_157
	.HIBYTES palettes_set_158
	.HIBYTES palettes_set_159
	.HIBYTES palettes_set_15a
	.HIBYTES palettes_set_15b
	.HIBYTES palettes_set_15c
	.HIBYTES palettes_set_15d
	.HIBYTES palettes_set_15e
	.HIBYTES palettes_set_15f
	.HIBYTES palettes_set_160
	.HIBYTES palettes_set_161
	.HIBYTES palettes_set_162
	.HIBYTES palettes_set_163
	.HIBYTES palettes_set_164
	.HIBYTES palettes_set_165
	.HIBYTES palettes_set_166
	.HIBYTES palettes_set_167
	.HIBYTES palettes_set_168
	.HIBYTES palettes_set_169
	.HIBYTES palettes_set_16a
	.HIBYTES palettes_set_16b
	.HIBYTES palettes_set_16c
	.HIBYTES palettes_set_16d
	.HIBYTES palettes_set_16e
	.HIBYTES palettes_set_16f
	.HIBYTES palettes_set_170
	.HIBYTES palettes_set_171
	.HIBYTES palettes_set_172
	.HIBYTES palettes_set_173
	.HIBYTES palettes_set_174
	.HIBYTES palettes_set_175
	.HIBYTES palettes_set_176
	.HIBYTES palettes_set_177
	.HIBYTES palettes_set_178
	.HIBYTES palettes_set_179
	.HIBYTES palettes_set_17a
	.HIBYTES palettes_set_17b
	.HIBYTES palettes_set_17c
	.HIBYTES palettes_set_17d
	.HIBYTES palettes_set_17e
	.HIBYTES palettes_set_17f
	.HIBYTES palettes_set_180
	.HIBYTES palettes_set_181
	.HIBYTES palettes_set_182
	.HIBYTES palettes_set_183
	.HIBYTES palettes_set_184
	.HIBYTES palettes_set_185
	.HIBYTES palettes_set_186
	.HIBYTES palettes_set_187
	.HIBYTES palettes_set_188
	.HIBYTES palettes_set_189
	.HIBYTES palettes_set_18a
	.HIBYTES palettes_set_18b
	.HIBYTES palettes_set_18c
	.HIBYTES palettes_set_18d
	.HIBYTES palettes_set_18e
	.HIBYTES palettes_set_18f
	.HIBYTES palettes_set_190
	.HIBYTES palettes_set_191
	.HIBYTES palettes_set_192
	.HIBYTES palettes_set_193
	.HIBYTES palettes_set_194
	.HIBYTES palettes_set_195
	.HIBYTES palettes_set_196
	.HIBYTES palettes_set_197
	.HIBYTES palettes_set_198
	.HIBYTES palettes_set_199
	.HIBYTES palettes_set_19a
	.HIBYTES palettes_set_19b
	.HIBYTES palettes_set_19c
	.HIBYTES palettes_set_19d
	.HIBYTES palettes_set_19e
	.HIBYTES palettes_set_19f
	.HIBYTES palettes_set_1a0
	.HIBYTES palettes_set_1a1
	.HIBYTES palettes_set_1a2
	.HIBYTES palettes_set_1a3
	.HIBYTES palettes_set_1a4
	.HIBYTES palettes_set_1a5
	.HIBYTES palettes_set_1a6
	.HIBYTES palettes_set_1a7
	.HIBYTES palettes_set_1a8
	.HIBYTES palettes_set_1a9
	.HIBYTES palettes_set_1aa
	.HIBYTES palettes_set_1ab
	.HIBYTES palettes_set_1ac
	.HIBYTES palettes_set_1ad
	.HIBYTES palettes_set_1ae
	.HIBYTES palettes_set_1af
	.HIBYTES palettes_set_1b0
	.HIBYTES palettes_set_1b1
	.HIBYTES palettes_set_1b2
	.HIBYTES palettes_set_1b3
	.HIBYTES palettes_set_1b4
	.HIBYTES palettes_set_1b5
	.HIBYTES palettes_set_1b6
	.HIBYTES palettes_set_1b7
	.HIBYTES palettes_set_1b8
	.HIBYTES palettes_set_1b9
	.HIBYTES palettes_set_1ba
	.HIBYTES palettes_set_1bb
	.HIBYTES palettes_set_1bc
	.HIBYTES palettes_set_1bd
	.HIBYTES palettes_set_1be
	.HIBYTES palettes_set_1bf
	.HIBYTES palettes_set_1c0
	.HIBYTES palettes_set_1c1
	.HIBYTES palettes_set_1c2
	.HIBYTES palettes_set_1c3
	.HIBYTES palettes_set_1c4
	.HIBYTES palettes_set_1c5
	.HIBYTES palettes_set_1c6
	.HIBYTES palettes_set_1c7
	.HIBYTES palettes_set_1c8
	.HIBYTES palettes_set_1c9
	.HIBYTES palettes_set_1ca
	.HIBYTES palettes_set_1cb
	.HIBYTES palettes_set_1cc
	.HIBYTES palettes_set_1cd
	.HIBYTES palettes_set_1ce
	.HIBYTES palettes_set_1cf
	.HIBYTES palettes_set_1d0
	.HIBYTES palettes_set_1d1
	.HIBYTES palettes_set_1d2
	.HIBYTES palettes_set_1d3
	.HIBYTES palettes_set_1d4
	.HIBYTES palettes_set_1d5
	.HIBYTES palettes_set_1d6
	.HIBYTES palettes_set_1d7
	.HIBYTES palettes_set_1d8
	.HIBYTES palettes_set_1d9
	.HIBYTES palettes_set_1da
	.HIBYTES palettes_set_1db
	.HIBYTES palettes_set_1dc
	.HIBYTES palettes_set_1dd
	.HIBYTES palettes_set_1de
	.HIBYTES palettes_set_1df
	.HIBYTES palettes_set_1e0
	.HIBYTES palettes_set_1e1
	.HIBYTES palettes_set_1e2
	.HIBYTES palettes_set_1e3
	.HIBYTES palettes_set_1e4
	.HIBYTES palettes_set_1e5
	.HIBYTES palettes_set_1e6
	.HIBYTES palettes_set_1e7
	.HIBYTES palettes_set_1e8
	.HIBYTES palettes_set_1e9
	.HIBYTES palettes_set_1ea
	.HIBYTES palettes_set_1eb
	.HIBYTES palettes_set_1ec
	.HIBYTES palettes_set_1ed
	.HIBYTES palettes_set_1ee
	.HIBYTES palettes_set_1ef
	.HIBYTES palettes_set_1f0
	.HIBYTES palettes_set_1f1
	.HIBYTES palettes_set_1f2
	.HIBYTES palettes_set_1f3
	.HIBYTES palettes_set_1f4
	.HIBYTES palettes_set_1f5
	.HIBYTES palettes_set_1f6
	.HIBYTES palettes_set_1f7
	.HIBYTES palettes_set_1f8
	.HIBYTES palettes_set_1f9
	.HIBYTES palettes_set_1fa
	.HIBYTES palettes_set_1fb
	.HIBYTES palettes_set_1fc
	.HIBYTES palettes_set_1fd
	.HIBYTES palettes_set_1fe
	.HIBYTES palettes_set_1ff
