;oam frameset pointers
;lo
	.LOBYTES oam_frameset_000
	.LOBYTES oam_frameset_001
	.LOBYTES oam_frameset_002
	.LOBYTES oam_frameset_003
	.LOBYTES oam_frameset_004
	.LOBYTES oam_frameset_005
	.LOBYTES oam_frameset_006
	.LOBYTES oam_frameset_007
	.LOBYTES oam_frameset_008
	.LOBYTES oam_frameset_009
	.LOBYTES oam_frameset_00a
	.LOBYTES oam_frameset_00b
	.LOBYTES oam_frameset_00c
	.LOBYTES oam_frameset_00d
	.LOBYTES oam_frameset_00e
	.LOBYTES oam_frameset_00f
	.LOBYTES oam_frameset_010
	.LOBYTES oam_frameset_011
	.LOBYTES oam_frameset_012
	.LOBYTES oam_frameset_013
	.LOBYTES oam_frameset_014
	.LOBYTES oam_frameset_015
	.LOBYTES oam_frameset_016
	.LOBYTES oam_frameset_017
	.LOBYTES oam_frameset_018
	.LOBYTES oam_frameset_019
	.LOBYTES oam_frameset_01a
	.LOBYTES oam_frameset_01b
	.LOBYTES oam_frameset_01c
	.LOBYTES oam_frameset_01d
	.LOBYTES oam_frameset_01e
	.LOBYTES oam_frameset_01f
	.LOBYTES oam_frameset_020
	.LOBYTES oam_frameset_021
	.LOBYTES oam_frameset_022
	.LOBYTES oam_frameset_023
	.LOBYTES oam_frameset_024
	.LOBYTES oam_frameset_025
	.LOBYTES oam_frameset_026
	.LOBYTES oam_frameset_027
	.LOBYTES oam_frameset_028
	.LOBYTES oam_frameset_029
	.LOBYTES oam_frameset_02a
	.LOBYTES oam_frameset_02b
	.LOBYTES oam_frameset_02c
	.LOBYTES oam_frameset_02d
	.LOBYTES oam_frameset_02e
	.LOBYTES oam_frameset_02f
	.LOBYTES oam_frameset_030
	.LOBYTES oam_frameset_031
	.LOBYTES oam_frameset_032
	.LOBYTES oam_frameset_033
	.LOBYTES oam_frameset_034
	.LOBYTES oam_frameset_035
	.LOBYTES oam_frameset_036
	.LOBYTES oam_frameset_037
	.LOBYTES oam_frameset_038
	.LOBYTES oam_frameset_039
	.LOBYTES oam_frameset_03a
	.LOBYTES oam_frameset_03b
	.LOBYTES oam_frameset_03c
	.LOBYTES oam_frameset_03d
	.LOBYTES oam_frameset_03e
	.LOBYTES oam_frameset_03f
	.LOBYTES oam_frameset_040
	.LOBYTES oam_frameset_041
	.LOBYTES oam_frameset_042
	.LOBYTES oam_frameset_043
	.LOBYTES oam_frameset_044
	.LOBYTES oam_frameset_045
	.LOBYTES oam_frameset_046
	.LOBYTES oam_frameset_047
	.LOBYTES oam_frameset_048
	.LOBYTES oam_frameset_049
	.LOBYTES oam_frameset_04a
	.LOBYTES oam_frameset_04b
	.LOBYTES oam_frameset_04c
	.LOBYTES oam_frameset_04d
	.LOBYTES oam_frameset_04e
	.LOBYTES oam_frameset_04f
	.LOBYTES oam_frameset_050
	.LOBYTES oam_frameset_051
	.LOBYTES oam_frameset_052
	.LOBYTES oam_frameset_053
	.LOBYTES oam_frameset_054
	.LOBYTES oam_frameset_055
	.LOBYTES oam_frameset_056
	.LOBYTES oam_frameset_057
	.LOBYTES oam_frameset_058
	.LOBYTES oam_frameset_059
	.LOBYTES oam_frameset_05a
	.LOBYTES oam_frameset_05b
	.LOBYTES oam_frameset_05c
	.LOBYTES oam_frameset_05d
	.LOBYTES oam_frameset_05e
	.LOBYTES oam_frameset_05f
	.LOBYTES oam_frameset_060
	.LOBYTES oam_frameset_061
	.LOBYTES oam_frameset_062
	.LOBYTES oam_frameset_063
	.LOBYTES oam_frameset_064
	.LOBYTES oam_frameset_065
	.LOBYTES oam_frameset_066
	.LOBYTES oam_frameset_067
	.LOBYTES oam_frameset_068
	.LOBYTES oam_frameset_069
	.LOBYTES oam_frameset_06a
	.LOBYTES oam_frameset_06b
	.LOBYTES oam_frameset_06c
	.LOBYTES oam_frameset_06d
	.LOBYTES oam_frameset_06e
	.LOBYTES oam_frameset_06f
	.LOBYTES oam_frameset_070
	.LOBYTES oam_frameset_071
	.LOBYTES oam_frameset_072
	.LOBYTES oam_frameset_073
	.LOBYTES oam_frameset_074
	.LOBYTES oam_frameset_075
	.LOBYTES oam_frameset_076
	.LOBYTES oam_frameset_077
	.LOBYTES oam_frameset_078
	.LOBYTES oam_frameset_079
	.LOBYTES oam_frameset_07a
	.LOBYTES oam_frameset_07b
	.LOBYTES oam_frameset_07c
	.LOBYTES oam_frameset_07d
	.LOBYTES oam_frameset_07e
	.LOBYTES oam_frameset_07f
	.LOBYTES oam_frameset_080
	.LOBYTES oam_frameset_081
	.LOBYTES oam_frameset_082
	.LOBYTES oam_frameset_083
	.LOBYTES oam_frameset_084
	.LOBYTES oam_frameset_085
	.LOBYTES oam_frameset_086
	.LOBYTES oam_frameset_087
	.LOBYTES oam_frameset_088
	.LOBYTES oam_frameset_089
	.LOBYTES oam_frameset_08a
	.LOBYTES oam_frameset_08b
	.LOBYTES oam_frameset_08c
	.LOBYTES oam_frameset_08d
	.LOBYTES oam_frameset_08e
	.LOBYTES oam_frameset_08f
	.LOBYTES oam_frameset_090
	.LOBYTES oam_frameset_091
	.LOBYTES oam_frameset_092
	.LOBYTES oam_frameset_093
	.LOBYTES oam_frameset_094
	.LOBYTES oam_frameset_095
	.LOBYTES oam_frameset_096
	.LOBYTES oam_frameset_097
	.LOBYTES oam_frameset_098
	.LOBYTES oam_frameset_099
	.LOBYTES oam_frameset_09a
	.LOBYTES oam_frameset_09b
	.LOBYTES oam_frameset_09c
	.LOBYTES oam_frameset_09d
	.LOBYTES oam_frameset_09e
	.LOBYTES oam_frameset_09f
	.LOBYTES oam_frameset_0a0
	.LOBYTES oam_frameset_0a1
	.LOBYTES oam_frameset_0a2
	.LOBYTES oam_frameset_0a3
	.LOBYTES oam_frameset_0a4
	.LOBYTES oam_frameset_0a5
	.LOBYTES oam_frameset_0a6
	.LOBYTES oam_frameset_0a7
	.LOBYTES oam_frameset_0a8
	.LOBYTES oam_frameset_0a9
	.LOBYTES oam_frameset_0aa
	.LOBYTES oam_frameset_0ab
	.LOBYTES oam_frameset_0ac
	.LOBYTES oam_frameset_0ad
	.LOBYTES oam_frameset_0ae
	.LOBYTES oam_frameset_0af
	.LOBYTES oam_frameset_0b0
	.LOBYTES oam_frameset_0b1
	.LOBYTES oam_frameset_0b2
	.LOBYTES oam_frameset_0b3
	.LOBYTES oam_frameset_0b4
	.LOBYTES oam_frameset_0b5
	.LOBYTES oam_frameset_0b6
	.LOBYTES oam_frameset_0b7
	.LOBYTES oam_frameset_0b8
	.LOBYTES oam_frameset_0b9
	.LOBYTES oam_frameset_0ba
	.LOBYTES oam_frameset_0bb
	.LOBYTES oam_frameset_0bc
	.LOBYTES oam_frameset_0bd
	.LOBYTES oam_frameset_0be
	.LOBYTES oam_frameset_0bf
	.LOBYTES oam_frameset_0c0
	.LOBYTES oam_frameset_0c1
	.LOBYTES oam_frameset_0c2
	.LOBYTES oam_frameset_0c3
	.LOBYTES oam_frameset_0c4
	.LOBYTES oam_frameset_0c5
	.LOBYTES oam_frameset_0c6
	.LOBYTES oam_frameset_0c7
	.LOBYTES oam_frameset_0c8
	.LOBYTES oam_frameset_0c9
	.LOBYTES oam_frameset_0ca
	.LOBYTES oam_frameset_0cb
	.LOBYTES oam_frameset_0cc
	.LOBYTES oam_frameset_0cd
	.LOBYTES oam_frameset_0ce
	.LOBYTES oam_frameset_0cf

;unused
	.BYTE $00, $00, $00, $00, $00, $00, $00, $00
	.BYTE $00, $00, $00, $00, $00, $00, $00, $00
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF

;hi
	.HIBYTES oam_frameset_000
	.HIBYTES oam_frameset_001
	.HIBYTES oam_frameset_002
	.HIBYTES oam_frameset_003
	.HIBYTES oam_frameset_004
	.HIBYTES oam_frameset_005
	.HIBYTES oam_frameset_006
	.HIBYTES oam_frameset_007
	.HIBYTES oam_frameset_008
	.HIBYTES oam_frameset_009
	.HIBYTES oam_frameset_00a
	.HIBYTES oam_frameset_00b
	.HIBYTES oam_frameset_00c
	.HIBYTES oam_frameset_00d
	.HIBYTES oam_frameset_00e
	.HIBYTES oam_frameset_00f
	.HIBYTES oam_frameset_010
	.HIBYTES oam_frameset_011
	.HIBYTES oam_frameset_012
	.HIBYTES oam_frameset_013
	.HIBYTES oam_frameset_014
	.HIBYTES oam_frameset_015
	.HIBYTES oam_frameset_016
	.HIBYTES oam_frameset_017
	.HIBYTES oam_frameset_018
	.HIBYTES oam_frameset_019
	.HIBYTES oam_frameset_01a
	.HIBYTES oam_frameset_01b
	.HIBYTES oam_frameset_01c
	.HIBYTES oam_frameset_01d
	.HIBYTES oam_frameset_01e
	.HIBYTES oam_frameset_01f
	.HIBYTES oam_frameset_020
	.HIBYTES oam_frameset_021
	.HIBYTES oam_frameset_022
	.HIBYTES oam_frameset_023
	.HIBYTES oam_frameset_024
	.HIBYTES oam_frameset_025
	.HIBYTES oam_frameset_026
	.HIBYTES oam_frameset_027
	.HIBYTES oam_frameset_028
	.HIBYTES oam_frameset_029
	.HIBYTES oam_frameset_02a
	.HIBYTES oam_frameset_02b
	.HIBYTES oam_frameset_02c
	.HIBYTES oam_frameset_02d
	.HIBYTES oam_frameset_02e
	.HIBYTES oam_frameset_02f
	.HIBYTES oam_frameset_030
	.HIBYTES oam_frameset_031
	.HIBYTES oam_frameset_032
	.HIBYTES oam_frameset_033
	.HIBYTES oam_frameset_034
	.HIBYTES oam_frameset_035
	.HIBYTES oam_frameset_036
	.HIBYTES oam_frameset_037
	.HIBYTES oam_frameset_038
	.HIBYTES oam_frameset_039
	.HIBYTES oam_frameset_03a
	.HIBYTES oam_frameset_03b
	.HIBYTES oam_frameset_03c
	.HIBYTES oam_frameset_03d
	.HIBYTES oam_frameset_03e
	.HIBYTES oam_frameset_03f
	.HIBYTES oam_frameset_040
	.HIBYTES oam_frameset_041
	.HIBYTES oam_frameset_042
	.HIBYTES oam_frameset_043
	.HIBYTES oam_frameset_044
	.HIBYTES oam_frameset_045
	.HIBYTES oam_frameset_046
	.HIBYTES oam_frameset_047
	.HIBYTES oam_frameset_048
	.HIBYTES oam_frameset_049
	.HIBYTES oam_frameset_04a
	.HIBYTES oam_frameset_04b
	.HIBYTES oam_frameset_04c
	.HIBYTES oam_frameset_04d
	.HIBYTES oam_frameset_04e
	.HIBYTES oam_frameset_04f
	.HIBYTES oam_frameset_050
	.HIBYTES oam_frameset_051
	.HIBYTES oam_frameset_052
	.HIBYTES oam_frameset_053
	.HIBYTES oam_frameset_054
	.HIBYTES oam_frameset_055
	.HIBYTES oam_frameset_056
	.HIBYTES oam_frameset_057
	.HIBYTES oam_frameset_058
	.HIBYTES oam_frameset_059
	.HIBYTES oam_frameset_05a
	.HIBYTES oam_frameset_05b
	.HIBYTES oam_frameset_05c
	.HIBYTES oam_frameset_05d
	.HIBYTES oam_frameset_05e
	.HIBYTES oam_frameset_05f
	.HIBYTES oam_frameset_060
	.HIBYTES oam_frameset_061
	.HIBYTES oam_frameset_062
	.HIBYTES oam_frameset_063
	.HIBYTES oam_frameset_064
	.HIBYTES oam_frameset_065
	.HIBYTES oam_frameset_066
	.HIBYTES oam_frameset_067
	.HIBYTES oam_frameset_068
	.HIBYTES oam_frameset_069
	.HIBYTES oam_frameset_06a
	.HIBYTES oam_frameset_06b
	.HIBYTES oam_frameset_06c
	.HIBYTES oam_frameset_06d
	.HIBYTES oam_frameset_06e
	.HIBYTES oam_frameset_06f
	.HIBYTES oam_frameset_070
	.HIBYTES oam_frameset_071
	.HIBYTES oam_frameset_072
	.HIBYTES oam_frameset_073
	.HIBYTES oam_frameset_074
	.HIBYTES oam_frameset_075
	.HIBYTES oam_frameset_076
	.HIBYTES oam_frameset_077
	.HIBYTES oam_frameset_078
	.HIBYTES oam_frameset_079
	.HIBYTES oam_frameset_07a
	.HIBYTES oam_frameset_07b
	.HIBYTES oam_frameset_07c
	.HIBYTES oam_frameset_07d
	.HIBYTES oam_frameset_07e
	.HIBYTES oam_frameset_07f
	.HIBYTES oam_frameset_080
	.HIBYTES oam_frameset_081
	.HIBYTES oam_frameset_082
	.HIBYTES oam_frameset_083
	.HIBYTES oam_frameset_084
	.HIBYTES oam_frameset_085
	.HIBYTES oam_frameset_086
	.HIBYTES oam_frameset_087
	.HIBYTES oam_frameset_088
	.HIBYTES oam_frameset_089
	.HIBYTES oam_frameset_08a
	.HIBYTES oam_frameset_08b
	.HIBYTES oam_frameset_08c
	.HIBYTES oam_frameset_08d
	.HIBYTES oam_frameset_08e
	.HIBYTES oam_frameset_08f
	.HIBYTES oam_frameset_090
	.HIBYTES oam_frameset_091
	.HIBYTES oam_frameset_092
	.HIBYTES oam_frameset_093
	.HIBYTES oam_frameset_094
	.HIBYTES oam_frameset_095
	.HIBYTES oam_frameset_096
	.HIBYTES oam_frameset_097
	.HIBYTES oam_frameset_098
	.HIBYTES oam_frameset_099
	.HIBYTES oam_frameset_09a
	.HIBYTES oam_frameset_09b
	.HIBYTES oam_frameset_09c
	.HIBYTES oam_frameset_09d
	.HIBYTES oam_frameset_09e
	.HIBYTES oam_frameset_09f
	.HIBYTES oam_frameset_0a0
	.HIBYTES oam_frameset_0a1
	.HIBYTES oam_frameset_0a2
	.HIBYTES oam_frameset_0a3
	.HIBYTES oam_frameset_0a4
	.HIBYTES oam_frameset_0a5
	.HIBYTES oam_frameset_0a6
	.HIBYTES oam_frameset_0a7
	.HIBYTES oam_frameset_0a8
	.HIBYTES oam_frameset_0a9
	.HIBYTES oam_frameset_0aa
	.HIBYTES oam_frameset_0ab
	.HIBYTES oam_frameset_0ac
	.HIBYTES oam_frameset_0ad
	.HIBYTES oam_frameset_0ae
	.HIBYTES oam_frameset_0af
	.HIBYTES oam_frameset_0b0
	.HIBYTES oam_frameset_0b1
	.HIBYTES oam_frameset_0b2
	.HIBYTES oam_frameset_0b3
	.HIBYTES oam_frameset_0b4
	.HIBYTES oam_frameset_0b5
	.HIBYTES oam_frameset_0b6
	.HIBYTES oam_frameset_0b7
	.HIBYTES oam_frameset_0b8
	.HIBYTES oam_frameset_0b9
	.HIBYTES oam_frameset_0ba
	.HIBYTES oam_frameset_0bb
	.HIBYTES oam_frameset_0bc
	.HIBYTES oam_frameset_0bd
	.HIBYTES oam_frameset_0be
	.HIBYTES oam_frameset_0bf
	.HIBYTES oam_frameset_0c0
	.HIBYTES oam_frameset_0c1
	.HIBYTES oam_frameset_0c2
	.HIBYTES oam_frameset_0c3
	.HIBYTES oam_frameset_0c4
	.HIBYTES oam_frameset_0c5
	.HIBYTES oam_frameset_0c6
	.HIBYTES oam_frameset_0c7
	.HIBYTES oam_frameset_0c8
	.HIBYTES oam_frameset_0c9
	.HIBYTES oam_frameset_0ca
	.HIBYTES oam_frameset_0cb
	.HIBYTES oam_frameset_0cc
	.HIBYTES oam_frameset_0cd
	.HIBYTES oam_frameset_0ce
	.HIBYTES oam_frameset_0cf
