;oam frameset pointers
;lo
	.LOBYTES oam_frameset_100
	.LOBYTES oam_frameset_101
	.LOBYTES oam_frameset_102
	.LOBYTES oam_frameset_103
	.LOBYTES oam_frameset_104
	.LOBYTES oam_frameset_105
	.LOBYTES oam_frameset_106
	.LOBYTES oam_frameset_107
	.LOBYTES oam_frameset_108
	.LOBYTES oam_frameset_109
	.LOBYTES oam_frameset_10a
	.LOBYTES oam_frameset_10b
	.LOBYTES oam_frameset_10c
	.LOBYTES oam_frameset_10d
	.LOBYTES oam_frameset_10e
	.LOBYTES oam_frameset_10f
	.LOBYTES oam_frameset_110
	.LOBYTES oam_frameset_111
	.LOBYTES oam_frameset_112
	.LOBYTES oam_frameset_113
	.LOBYTES oam_frameset_114
	.LOBYTES oam_frameset_115
	.LOBYTES oam_frameset_116
	.LOBYTES oam_frameset_117
	.LOBYTES oam_frameset_118
	.LOBYTES oam_frameset_119
	.LOBYTES oam_frameset_11a
	.LOBYTES oam_frameset_11b
	.LOBYTES oam_frameset_11c
	.LOBYTES oam_frameset_11d
	.LOBYTES oam_frameset_11e
	.LOBYTES oam_frameset_11f
	.LOBYTES oam_frameset_120
	.LOBYTES oam_frameset_121
	.LOBYTES oam_frameset_122
	.LOBYTES oam_frameset_123
	.LOBYTES oam_frameset_124
	.LOBYTES oam_frameset_125
	.LOBYTES oam_frameset_126
	.LOBYTES oam_frameset_127
	.LOBYTES oam_frameset_128
	.LOBYTES oam_frameset_129
	.LOBYTES oam_frameset_12a
	.LOBYTES oam_frameset_12b
	.LOBYTES oam_frameset_12c
	.LOBYTES oam_frameset_12d
	.LOBYTES oam_frameset_12e
	.LOBYTES oam_frameset_12f
	.LOBYTES oam_frameset_130
	.LOBYTES oam_frameset_131
	.LOBYTES oam_frameset_132
	.LOBYTES oam_frameset_133
	.LOBYTES oam_frameset_134
	.LOBYTES oam_frameset_135
	.LOBYTES oam_frameset_136
	.LOBYTES oam_frameset_137
	.LOBYTES oam_frameset_138
	.LOBYTES oam_frameset_139
	.LOBYTES oam_frameset_13a
	.LOBYTES oam_frameset_13b
	.LOBYTES oam_frameset_13c
	.LOBYTES oam_frameset_13d
	.LOBYTES oam_frameset_13e
	.LOBYTES oam_frameset_13f
	.LOBYTES oam_frameset_140
	.LOBYTES oam_frameset_141
	.LOBYTES oam_frameset_142
	.LOBYTES oam_frameset_143
	.LOBYTES oam_frameset_144
	.LOBYTES oam_frameset_145
	.LOBYTES oam_frameset_146
	.LOBYTES oam_frameset_147
	.LOBYTES oam_frameset_148
	.LOBYTES oam_frameset_149
	.LOBYTES oam_frameset_14a
	.LOBYTES oam_frameset_14b
	.LOBYTES oam_frameset_14c
	.LOBYTES oam_frameset_14d
	.LOBYTES oam_frameset_14e
	.LOBYTES oam_frameset_14f
	.LOBYTES oam_frameset_150
	.LOBYTES oam_frameset_151
	.LOBYTES oam_frameset_152
	.LOBYTES oam_frameset_153
	.LOBYTES oam_frameset_154
	.LOBYTES oam_frameset_155
	.LOBYTES oam_frameset_156
	.LOBYTES oam_frameset_157
	.LOBYTES oam_frameset_158
	.LOBYTES oam_frameset_159
	.LOBYTES oam_frameset_15a
	.LOBYTES oam_frameset_15b
	.LOBYTES oam_frameset_15c
	.LOBYTES oam_frameset_15d
	.LOBYTES oam_frameset_15e
	.LOBYTES oam_frameset_15f
	.LOBYTES oam_frameset_160
	.LOBYTES oam_frameset_161
	.LOBYTES oam_frameset_162
	.LOBYTES oam_frameset_163
	.LOBYTES oam_frameset_164
	.LOBYTES oam_frameset_165
	.LOBYTES oam_frameset_166
	.LOBYTES oam_frameset_167
	.LOBYTES oam_frameset_168
	.LOBYTES oam_frameset_169
	.LOBYTES oam_frameset_16a
	.LOBYTES oam_frameset_16b
	.LOBYTES oam_frameset_16c
	.LOBYTES oam_frameset_16d
	.LOBYTES oam_frameset_16e
	.LOBYTES oam_frameset_16f
	.LOBYTES oam_frameset_170
	.LOBYTES oam_frameset_171
	.LOBYTES oam_frameset_172
	.LOBYTES oam_frameset_173
	.LOBYTES oam_frameset_174
	.LOBYTES oam_frameset_175
	.LOBYTES oam_frameset_176
	.LOBYTES oam_frameset_177
	.LOBYTES oam_frameset_178
	.LOBYTES oam_frameset_179
	.LOBYTES oam_frameset_17a
	.LOBYTES oam_frameset_17b
	.LOBYTES oam_frameset_17c
	.LOBYTES oam_frameset_17d
	.LOBYTES oam_frameset_17e
	.LOBYTES oam_frameset_17f
	.LOBYTES oam_frameset_180
	.LOBYTES oam_frameset_181
	.LOBYTES oam_frameset_182
	.LOBYTES oam_frameset_183
	.LOBYTES oam_frameset_184
	.LOBYTES oam_frameset_185
	.LOBYTES oam_frameset_186
	.LOBYTES oam_frameset_187
	.LOBYTES oam_frameset_188
	.LOBYTES oam_frameset_189
	.LOBYTES oam_frameset_18a
	.LOBYTES oam_frameset_18b
	.LOBYTES oam_frameset_18c
	.LOBYTES oam_frameset_18d
	.LOBYTES oam_frameset_18e
	.LOBYTES oam_frameset_18f
	.LOBYTES oam_frameset_190
	.LOBYTES oam_frameset_191
	.LOBYTES oam_frameset_192
	.LOBYTES oam_frameset_193
	.LOBYTES oam_frameset_194
	.LOBYTES oam_frameset_195
	.LOBYTES oam_frameset_196
	.LOBYTES oam_frameset_197
	.LOBYTES oam_frameset_198
	.LOBYTES oam_frameset_199
	.LOBYTES oam_frameset_19a
	.LOBYTES oam_frameset_19b
	.LOBYTES oam_frameset_19c
	.LOBYTES oam_frameset_19d
	.LOBYTES oam_frameset_19e
	.LOBYTES oam_frameset_19f
	.LOBYTES oam_frameset_1a0
	.LOBYTES oam_frameset_1a1
	.LOBYTES oam_frameset_1a2
	.LOBYTES oam_frameset_1a3
	.LOBYTES oam_frameset_1a4
	.LOBYTES oam_frameset_1a5
	.LOBYTES oam_frameset_1a6
	.LOBYTES oam_frameset_1a7
	.LOBYTES oam_frameset_1a8
	.LOBYTES oam_frameset_1a9
	.LOBYTES oam_frameset_1aa
	.LOBYTES oam_frameset_1ab
	.LOBYTES oam_frameset_1ac
	.LOBYTES oam_frameset_1ad
	.LOBYTES oam_frameset_1ae
	.LOBYTES oam_frameset_1af
	.LOBYTES oam_frameset_1b0
	.LOBYTES oam_frameset_1b1
	.LOBYTES oam_frameset_1b2
	.LOBYTES oam_frameset_1b3
	.LOBYTES oam_frameset_1b4
	.LOBYTES oam_frameset_1b5
	.LOBYTES oam_frameset_1b6
	.LOBYTES oam_frameset_1b7
	.LOBYTES oam_frameset_1b8
	.LOBYTES oam_frameset_1b9
	.LOBYTES oam_frameset_1ba
	.LOBYTES oam_frameset_1bb
	.LOBYTES oam_frameset_1bc
	.LOBYTES oam_frameset_1bd
	.LOBYTES oam_frameset_1be
	.LOBYTES oam_frameset_1bf
	.LOBYTES oam_frameset_1c0
	.LOBYTES oam_frameset_1c1
	.LOBYTES oam_frameset_1c2
	.LOBYTES oam_frameset_1c3
	.LOBYTES oam_frameset_1c4
	.LOBYTES oam_frameset_1c5
	.LOBYTES oam_frameset_1c6
	.LOBYTES oam_frameset_1c7
	.LOBYTES oam_frameset_1c8
	.LOBYTES oam_frameset_1c9
	.LOBYTES oam_frameset_1ca
	.LOBYTES oam_frameset_1cb
	.LOBYTES oam_frameset_1cc
	.LOBYTES oam_frameset_1cd
	.LOBYTES oam_frameset_1ce
	.LOBYTES oam_frameset_1cf

;unused
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.BYTE $00, $00, $00, $00, $00, $00, $00, $00
	.BYTE $00, $00, $00, $00, $00, $00, $00, $00
	.BYTE $00, $00, $00, $00, $00, $00, $00, $00
	.BYTE $00, $00, $00, $00, $00, $00, $00, $00

;hi
	.HIBYTES oam_frameset_100
	.HIBYTES oam_frameset_101
	.HIBYTES oam_frameset_102
	.HIBYTES oam_frameset_103
	.HIBYTES oam_frameset_104
	.HIBYTES oam_frameset_105
	.HIBYTES oam_frameset_106
	.HIBYTES oam_frameset_107
	.HIBYTES oam_frameset_108
	.HIBYTES oam_frameset_109
	.HIBYTES oam_frameset_10a
	.HIBYTES oam_frameset_10b
	.HIBYTES oam_frameset_10c
	.HIBYTES oam_frameset_10d
	.HIBYTES oam_frameset_10e
	.HIBYTES oam_frameset_10f
	.HIBYTES oam_frameset_110
	.HIBYTES oam_frameset_111
	.HIBYTES oam_frameset_112
	.HIBYTES oam_frameset_113
	.HIBYTES oam_frameset_114
	.HIBYTES oam_frameset_115
	.HIBYTES oam_frameset_116
	.HIBYTES oam_frameset_117
	.HIBYTES oam_frameset_118
	.HIBYTES oam_frameset_119
	.HIBYTES oam_frameset_11a
	.HIBYTES oam_frameset_11b
	.HIBYTES oam_frameset_11c
	.HIBYTES oam_frameset_11d
	.HIBYTES oam_frameset_11e
	.HIBYTES oam_frameset_11f
	.HIBYTES oam_frameset_120
	.HIBYTES oam_frameset_121
	.HIBYTES oam_frameset_122
	.HIBYTES oam_frameset_123
	.HIBYTES oam_frameset_124
	.HIBYTES oam_frameset_125
	.HIBYTES oam_frameset_126
	.HIBYTES oam_frameset_127
	.HIBYTES oam_frameset_128
	.HIBYTES oam_frameset_129
	.HIBYTES oam_frameset_12a
	.HIBYTES oam_frameset_12b
	.HIBYTES oam_frameset_12c
	.HIBYTES oam_frameset_12d
	.HIBYTES oam_frameset_12e
	.HIBYTES oam_frameset_12f
	.HIBYTES oam_frameset_130
	.HIBYTES oam_frameset_131
	.HIBYTES oam_frameset_132
	.HIBYTES oam_frameset_133
	.HIBYTES oam_frameset_134
	.HIBYTES oam_frameset_135
	.HIBYTES oam_frameset_136
	.HIBYTES oam_frameset_137
	.HIBYTES oam_frameset_138
	.HIBYTES oam_frameset_139
	.HIBYTES oam_frameset_13a
	.HIBYTES oam_frameset_13b
	.HIBYTES oam_frameset_13c
	.HIBYTES oam_frameset_13d
	.HIBYTES oam_frameset_13e
	.HIBYTES oam_frameset_13f
	.HIBYTES oam_frameset_140
	.HIBYTES oam_frameset_141
	.HIBYTES oam_frameset_142
	.HIBYTES oam_frameset_143
	.HIBYTES oam_frameset_144
	.HIBYTES oam_frameset_145
	.HIBYTES oam_frameset_146
	.HIBYTES oam_frameset_147
	.HIBYTES oam_frameset_148
	.HIBYTES oam_frameset_149
	.HIBYTES oam_frameset_14a
	.HIBYTES oam_frameset_14b
	.HIBYTES oam_frameset_14c
	.HIBYTES oam_frameset_14d
	.HIBYTES oam_frameset_14e
	.HIBYTES oam_frameset_14f
	.HIBYTES oam_frameset_150
	.HIBYTES oam_frameset_151
	.HIBYTES oam_frameset_152
	.HIBYTES oam_frameset_153
	.HIBYTES oam_frameset_154
	.HIBYTES oam_frameset_155
	.HIBYTES oam_frameset_156
	.HIBYTES oam_frameset_157
	.HIBYTES oam_frameset_158
	.HIBYTES oam_frameset_159
	.HIBYTES oam_frameset_15a
	.HIBYTES oam_frameset_15b
	.HIBYTES oam_frameset_15c
	.HIBYTES oam_frameset_15d
	.HIBYTES oam_frameset_15e
	.HIBYTES oam_frameset_15f
	.HIBYTES oam_frameset_160
	.HIBYTES oam_frameset_161
	.HIBYTES oam_frameset_162
	.HIBYTES oam_frameset_163
	.HIBYTES oam_frameset_164
	.HIBYTES oam_frameset_165
	.HIBYTES oam_frameset_166
	.HIBYTES oam_frameset_167
	.HIBYTES oam_frameset_168
	.HIBYTES oam_frameset_169
	.HIBYTES oam_frameset_16a
	.HIBYTES oam_frameset_16b
	.HIBYTES oam_frameset_16c
	.HIBYTES oam_frameset_16d
	.HIBYTES oam_frameset_16e
	.HIBYTES oam_frameset_16f
	.HIBYTES oam_frameset_170
	.HIBYTES oam_frameset_171
	.HIBYTES oam_frameset_172
	.HIBYTES oam_frameset_173
	.HIBYTES oam_frameset_174
	.HIBYTES oam_frameset_175
	.HIBYTES oam_frameset_176
	.HIBYTES oam_frameset_177
	.HIBYTES oam_frameset_178
	.HIBYTES oam_frameset_179
	.HIBYTES oam_frameset_17a
	.HIBYTES oam_frameset_17b
	.HIBYTES oam_frameset_17c
	.HIBYTES oam_frameset_17d
	.HIBYTES oam_frameset_17e
	.HIBYTES oam_frameset_17f
	.HIBYTES oam_frameset_180
	.HIBYTES oam_frameset_181
	.HIBYTES oam_frameset_182
	.HIBYTES oam_frameset_183
	.HIBYTES oam_frameset_184
	.HIBYTES oam_frameset_185
	.HIBYTES oam_frameset_186
	.HIBYTES oam_frameset_187
	.HIBYTES oam_frameset_188
	.HIBYTES oam_frameset_189
	.HIBYTES oam_frameset_18a
	.HIBYTES oam_frameset_18b
	.HIBYTES oam_frameset_18c
	.HIBYTES oam_frameset_18d
	.HIBYTES oam_frameset_18e
	.HIBYTES oam_frameset_18f
	.HIBYTES oam_frameset_190
	.HIBYTES oam_frameset_191
	.HIBYTES oam_frameset_192
	.HIBYTES oam_frameset_193
	.HIBYTES oam_frameset_194
	.HIBYTES oam_frameset_195
	.HIBYTES oam_frameset_196
	.HIBYTES oam_frameset_197
	.HIBYTES oam_frameset_198
	.HIBYTES oam_frameset_199
	.HIBYTES oam_frameset_19a
	.HIBYTES oam_frameset_19b
	.HIBYTES oam_frameset_19c
	.HIBYTES oam_frameset_19d
	.HIBYTES oam_frameset_19e
	.HIBYTES oam_frameset_19f
	.HIBYTES oam_frameset_1a0
	.HIBYTES oam_frameset_1a1
	.HIBYTES oam_frameset_1a2
	.HIBYTES oam_frameset_1a3
	.HIBYTES oam_frameset_1a4
	.HIBYTES oam_frameset_1a5
	.HIBYTES oam_frameset_1a6
	.HIBYTES oam_frameset_1a7
	.HIBYTES oam_frameset_1a8
	.HIBYTES oam_frameset_1a9
	.HIBYTES oam_frameset_1aa
	.HIBYTES oam_frameset_1ab
	.HIBYTES oam_frameset_1ac
	.HIBYTES oam_frameset_1ad
	.HIBYTES oam_frameset_1ae
	.HIBYTES oam_frameset_1af
	.HIBYTES oam_frameset_1b0
	.HIBYTES oam_frameset_1b1
	.HIBYTES oam_frameset_1b2
	.HIBYTES oam_frameset_1b3
	.HIBYTES oam_frameset_1b4
	.HIBYTES oam_frameset_1b5
	.HIBYTES oam_frameset_1b6
	.HIBYTES oam_frameset_1b7
	.HIBYTES oam_frameset_1b8
	.HIBYTES oam_frameset_1b9
	.HIBYTES oam_frameset_1ba
	.HIBYTES oam_frameset_1bb
	.HIBYTES oam_frameset_1bc
	.HIBYTES oam_frameset_1bd
	.HIBYTES oam_frameset_1be
	.HIBYTES oam_frameset_1bf
	.HIBYTES oam_frameset_1c0
	.HIBYTES oam_frameset_1c1
	.HIBYTES oam_frameset_1c2
	.HIBYTES oam_frameset_1c3
	.HIBYTES oam_frameset_1c4
	.HIBYTES oam_frameset_1c5
	.HIBYTES oam_frameset_1c6
	.HIBYTES oam_frameset_1c7
	.HIBYTES oam_frameset_1c8
	.HIBYTES oam_frameset_1c9
	.HIBYTES oam_frameset_1ca
	.HIBYTES oam_frameset_1cb
	.HIBYTES oam_frameset_1cc
	.HIBYTES oam_frameset_1cd
	.HIBYTES oam_frameset_1ce
	.HIBYTES oam_frameset_1cf
