;oamcoord pointers
;lo
	.LOBYTES oamcoord_000
	.LOBYTES oamcoord_001
	.LOBYTES oamcoord_002
	.LOBYTES oamcoord_003
	.LOBYTES oamcoord_004
	.LOBYTES oamcoord_005
	.LOBYTES oamcoord_006
	.LOBYTES oamcoord_007
	.LOBYTES oamcoord_008
	.LOBYTES oamcoord_009
	.LOBYTES oamcoord_00a
	.LOBYTES oamcoord_00b
	.LOBYTES oamcoord_00c
	.LOBYTES oamcoord_00d
	.LOBYTES oamcoord_00e
	.LOBYTES oamcoord_00f
	.LOBYTES oamcoord_010
	.LOBYTES oamcoord_011
	.LOBYTES oamcoord_012
	.LOBYTES oamcoord_013
	.LOBYTES oamcoord_014
	.LOBYTES oamcoord_015
	.LOBYTES oamcoord_016
	.LOBYTES oamcoord_017
	.LOBYTES oamcoord_018
	.LOBYTES oamcoord_019
	.LOBYTES oamcoord_01a
	.LOBYTES oamcoord_01b
	.LOBYTES oamcoord_01c
	.LOBYTES oamcoord_01d
	.LOBYTES oamcoord_01e
	.LOBYTES oamcoord_01f
	.LOBYTES oamcoord_020
	.LOBYTES oamcoord_021
	.LOBYTES oamcoord_022
	.LOBYTES oamcoord_023
	.LOBYTES oamcoord_024
	.LOBYTES oamcoord_025
	.LOBYTES oamcoord_026
	.LOBYTES oamcoord_027
	.LOBYTES oamcoord_028
	.LOBYTES oamcoord_029
	.LOBYTES oamcoord_02a
	.LOBYTES oamcoord_02b
	.LOBYTES oamcoord_02c
	.LOBYTES oamcoord_02d
	.LOBYTES oamcoord_02e
	.LOBYTES oamcoord_02f
	.LOBYTES oamcoord_030
	.LOBYTES oamcoord_031
	.LOBYTES oamcoord_032
	.LOBYTES oamcoord_033
	.LOBYTES oamcoord_034
	.LOBYTES oamcoord_035
	.LOBYTES oamcoord_036
	.LOBYTES oamcoord_037
	.LOBYTES oamcoord_038
	.LOBYTES oamcoord_039
	.LOBYTES oamcoord_03a
	.LOBYTES oamcoord_03b
	.LOBYTES oamcoord_03c
	.LOBYTES oamcoord_03d
	.LOBYTES oamcoord_03e
	.LOBYTES oamcoord_03f
	.LOBYTES oamcoord_040
	.LOBYTES oamcoord_041
	.LOBYTES oamcoord_042
	.LOBYTES oamcoord_043
	.LOBYTES oamcoord_044
	.LOBYTES oamcoord_045
	.LOBYTES oamcoord_046
	.LOBYTES oamcoord_047
	.LOBYTES oamcoord_048
	.LOBYTES oamcoord_049
	.LOBYTES oamcoord_04a
	.LOBYTES oamcoord_04b
	.LOBYTES oamcoord_04c
	.LOBYTES oamcoord_04d
	.LOBYTES oamcoord_04e
	.LOBYTES oamcoord_04f
	.LOBYTES oamcoord_050
	.LOBYTES oamcoord_051
	.LOBYTES oamcoord_052
	.LOBYTES oamcoord_053
	.LOBYTES oamcoord_054
	.LOBYTES oamcoord_055
	.LOBYTES oamcoord_056
	.LOBYTES oamcoord_057
	.LOBYTES oamcoord_058
	.LOBYTES oamcoord_059
	.LOBYTES oamcoord_05a
	.LOBYTES oamcoord_05b
	.LOBYTES oamcoord_05c
	.LOBYTES oamcoord_05d
	.LOBYTES oamcoord_05e
	.LOBYTES oamcoord_05f
	.LOBYTES oamcoord_060
	.LOBYTES oamcoord_061
	.LOBYTES oamcoord_062
	.LOBYTES oamcoord_063
	.LOBYTES oamcoord_064
	.LOBYTES oamcoord_065
	.LOBYTES oamcoord_066
	.LOBYTES oamcoord_067
	.LOBYTES oamcoord_068
	.LOBYTES oamcoord_069
	.LOBYTES oamcoord_06a
	.LOBYTES oamcoord_06b
	.LOBYTES oamcoord_06c
	.LOBYTES oamcoord_06d
	.LOBYTES oamcoord_06e
	.LOBYTES oamcoord_06f
	.LOBYTES oamcoord_070
	.LOBYTES oamcoord_071
	.LOBYTES oamcoord_072
	.LOBYTES oamcoord_073
	.LOBYTES oamcoord_074
	.LOBYTES oamcoord_075
	.LOBYTES oamcoord_076
	.LOBYTES oamcoord_077
	.LOBYTES oamcoord_078
	.LOBYTES oamcoord_079
	.LOBYTES oamcoord_07a
	.LOBYTES oamcoord_07b
	.LOBYTES oamcoord_07c
	.LOBYTES oamcoord_07d
	.LOBYTES oamcoord_07e
	.LOBYTES oamcoord_07f
	.LOBYTES oamcoord_080
	.LOBYTES oamcoord_081
	.LOBYTES oamcoord_082
	.LOBYTES oamcoord_083
	.LOBYTES oamcoord_084
	.LOBYTES oamcoord_085
	.LOBYTES oamcoord_086
	.LOBYTES oamcoord_087
	.LOBYTES oamcoord_088
	.LOBYTES oamcoord_089
	.LOBYTES oamcoord_08a
	.LOBYTES oamcoord_08b
	.LOBYTES oamcoord_08c
	.LOBYTES oamcoord_08d
	.LOBYTES oamcoord_08e
	.LOBYTES oamcoord_08f
	.LOBYTES oamcoord_090
	.LOBYTES oamcoord_091
	.LOBYTES oamcoord_092
	.LOBYTES oamcoord_093
	.LOBYTES oamcoord_094
	.LOBYTES oamcoord_095
	.LOBYTES oamcoord_096
	.LOBYTES oamcoord_097
	.LOBYTES oamcoord_098
	.LOBYTES oamcoord_099
	.LOBYTES oamcoord_09a
	.LOBYTES oamcoord_09b
	.LOBYTES oamcoord_09c
	.LOBYTES oamcoord_09d
	.LOBYTES oamcoord_09e
	.LOBYTES oamcoord_09f
	.LOBYTES oamcoord_0a0
	.LOBYTES oamcoord_0a1
	.LOBYTES oamcoord_0a2
	.LOBYTES oamcoord_0a3
	.LOBYTES oamcoord_0a4
	.LOBYTES oamcoord_0a5
	.LOBYTES oamcoord_0a6
	.LOBYTES oamcoord_0a7
	.LOBYTES oamcoord_0a8
	.LOBYTES oamcoord_0a9
	.LOBYTES oamcoord_0aa
	.LOBYTES oamcoord_0ab
	.LOBYTES oamcoord_0ac
	.LOBYTES oamcoord_0ad
	.LOBYTES oamcoord_0ae
	.LOBYTES oamcoord_0af
	.LOBYTES oamcoord_0b0
	.LOBYTES oamcoord_0b1
	.LOBYTES oamcoord_0b2
	.LOBYTES oamcoord_0b3
	.LOBYTES oamcoord_0b4
	.LOBYTES oamcoord_0b5
	.LOBYTES oamcoord_0b6
	.LOBYTES oamcoord_0b7
	.LOBYTES oamcoord_0b8
	.LOBYTES oamcoord_0b9
	.LOBYTES oamcoord_0ba
	.LOBYTES oamcoord_0bb
	.LOBYTES oamcoord_0bc
	.LOBYTES oamcoord_0bd
	.LOBYTES oamcoord_0be
	.LOBYTES oamcoord_0bf
	.LOBYTES oamcoord_0c0
	.LOBYTES oamcoord_0c1
	.LOBYTES oamcoord_0c2
	.LOBYTES oamcoord_0c3
	.LOBYTES oamcoord_0c4
	.LOBYTES oamcoord_0c5
	.LOBYTES oamcoord_0c6
	.LOBYTES oamcoord_0c7
	.LOBYTES oamcoord_0c8
	.LOBYTES oamcoord_0c9
	.LOBYTES oamcoord_0ca
	.LOBYTES oamcoord_0cb
	.LOBYTES oamcoord_0cc
	.LOBYTES oamcoord_0cd
	.LOBYTES oamcoord_0ce
	.LOBYTES oamcoord_0cf
	.LOBYTES oamcoord_0d0
	.LOBYTES oamcoord_0d1
	.LOBYTES oamcoord_0d2
	.LOBYTES oamcoord_0d3
	.LOBYTES oamcoord_0d4
	.LOBYTES oamcoord_0d5
	.LOBYTES oamcoord_0d6
	.LOBYTES oamcoord_0d7
	.LOBYTES oamcoord_0d8
	.LOBYTES oamcoord_0d9
	.LOBYTES oamcoord_0da
	.LOBYTES oamcoord_0db
	.LOBYTES oamcoord_0dc
	.LOBYTES oamcoord_0dd
	.LOBYTES oamcoord_0de
	.LOBYTES oamcoord_0df
	.LOBYTES oamcoord_0e0
	.LOBYTES oamcoord_0e1
	.LOBYTES oamcoord_0e2
	.LOBYTES oamcoord_0e3
	.LOBYTES oamcoord_0e4
	.LOBYTES oamcoord_0e5
	.LOBYTES oamcoord_0e6
	.LOBYTES oamcoord_0e7
	.LOBYTES oamcoord_0e8
	.LOBYTES oamcoord_0e9
	.LOBYTES oamcoord_0ea
	.LOBYTES oamcoord_0eb
	.LOBYTES oamcoord_0ec
	.LOBYTES oamcoord_0ed
	.LOBYTES oamcoord_0ee
	.LOBYTES oamcoord_0ef
	.LOBYTES oamcoord_0f0
	.LOBYTES oamcoord_0f1
	.LOBYTES oamcoord_0f2
	.LOBYTES oamcoord_0f3
	.LOBYTES oamcoord_0f4
	.LOBYTES oamcoord_0f5
	.LOBYTES oamcoord_0f6
	.LOBYTES oamcoord_0f7
	.LOBYTES oamcoord_0f8
	.LOBYTES oamcoord_0f9
	.LOBYTES oamcoord_0fa
	.LOBYTES oamcoord_0fb
	.LOBYTES oamcoord_0fc
	.LOBYTES oamcoord_0fd
	.LOBYTES oamcoord_0fe
	.LOBYTES oamcoord_0ff

;hi
	.HIBYTES oamcoord_000
	.HIBYTES oamcoord_001
	.HIBYTES oamcoord_002
	.HIBYTES oamcoord_003
	.HIBYTES oamcoord_004
	.HIBYTES oamcoord_005
	.HIBYTES oamcoord_006
	.HIBYTES oamcoord_007
	.HIBYTES oamcoord_008
	.HIBYTES oamcoord_009
	.HIBYTES oamcoord_00a
	.HIBYTES oamcoord_00b
	.HIBYTES oamcoord_00c
	.HIBYTES oamcoord_00d
	.HIBYTES oamcoord_00e
	.HIBYTES oamcoord_00f
	.HIBYTES oamcoord_010
	.HIBYTES oamcoord_011
	.HIBYTES oamcoord_012
	.HIBYTES oamcoord_013
	.HIBYTES oamcoord_014
	.HIBYTES oamcoord_015
	.HIBYTES oamcoord_016
	.HIBYTES oamcoord_017
	.HIBYTES oamcoord_018
	.HIBYTES oamcoord_019
	.HIBYTES oamcoord_01a
	.HIBYTES oamcoord_01b
	.HIBYTES oamcoord_01c
	.HIBYTES oamcoord_01d
	.HIBYTES oamcoord_01e
	.HIBYTES oamcoord_01f
	.HIBYTES oamcoord_020
	.HIBYTES oamcoord_021
	.HIBYTES oamcoord_022
	.HIBYTES oamcoord_023
	.HIBYTES oamcoord_024
	.HIBYTES oamcoord_025
	.HIBYTES oamcoord_026
	.HIBYTES oamcoord_027
	.HIBYTES oamcoord_028
	.HIBYTES oamcoord_029
	.HIBYTES oamcoord_02a
	.HIBYTES oamcoord_02b
	.HIBYTES oamcoord_02c
	.HIBYTES oamcoord_02d
	.HIBYTES oamcoord_02e
	.HIBYTES oamcoord_02f
	.HIBYTES oamcoord_030
	.HIBYTES oamcoord_031
	.HIBYTES oamcoord_032
	.HIBYTES oamcoord_033
	.HIBYTES oamcoord_034
	.HIBYTES oamcoord_035
	.HIBYTES oamcoord_036
	.HIBYTES oamcoord_037
	.HIBYTES oamcoord_038
	.HIBYTES oamcoord_039
	.HIBYTES oamcoord_03a
	.HIBYTES oamcoord_03b
	.HIBYTES oamcoord_03c
	.HIBYTES oamcoord_03d
	.HIBYTES oamcoord_03e
	.HIBYTES oamcoord_03f
	.HIBYTES oamcoord_040
	.HIBYTES oamcoord_041
	.HIBYTES oamcoord_042
	.HIBYTES oamcoord_043
	.HIBYTES oamcoord_044
	.HIBYTES oamcoord_045
	.HIBYTES oamcoord_046
	.HIBYTES oamcoord_047
	.HIBYTES oamcoord_048
	.HIBYTES oamcoord_049
	.HIBYTES oamcoord_04a
	.HIBYTES oamcoord_04b
	.HIBYTES oamcoord_04c
	.HIBYTES oamcoord_04d
	.HIBYTES oamcoord_04e
	.HIBYTES oamcoord_04f
	.HIBYTES oamcoord_050
	.HIBYTES oamcoord_051
	.HIBYTES oamcoord_052
	.HIBYTES oamcoord_053
	.HIBYTES oamcoord_054
	.HIBYTES oamcoord_055
	.HIBYTES oamcoord_056
	.HIBYTES oamcoord_057
	.HIBYTES oamcoord_058
	.HIBYTES oamcoord_059
	.HIBYTES oamcoord_05a
	.HIBYTES oamcoord_05b
	.HIBYTES oamcoord_05c
	.HIBYTES oamcoord_05d
	.HIBYTES oamcoord_05e
	.HIBYTES oamcoord_05f
	.HIBYTES oamcoord_060
	.HIBYTES oamcoord_061
	.HIBYTES oamcoord_062
	.HIBYTES oamcoord_063
	.HIBYTES oamcoord_064
	.HIBYTES oamcoord_065
	.HIBYTES oamcoord_066
	.HIBYTES oamcoord_067
	.HIBYTES oamcoord_068
	.HIBYTES oamcoord_069
	.HIBYTES oamcoord_06a
	.HIBYTES oamcoord_06b
	.HIBYTES oamcoord_06c
	.HIBYTES oamcoord_06d
	.HIBYTES oamcoord_06e
	.HIBYTES oamcoord_06f
	.HIBYTES oamcoord_070
	.HIBYTES oamcoord_071
	.HIBYTES oamcoord_072
	.HIBYTES oamcoord_073
	.HIBYTES oamcoord_074
	.HIBYTES oamcoord_075
	.HIBYTES oamcoord_076
	.HIBYTES oamcoord_077
	.HIBYTES oamcoord_078
	.HIBYTES oamcoord_079
	.HIBYTES oamcoord_07a
	.HIBYTES oamcoord_07b
	.HIBYTES oamcoord_07c
	.HIBYTES oamcoord_07d
	.HIBYTES oamcoord_07e
	.HIBYTES oamcoord_07f
	.HIBYTES oamcoord_080
	.HIBYTES oamcoord_081
	.HIBYTES oamcoord_082
	.HIBYTES oamcoord_083
	.HIBYTES oamcoord_084
	.HIBYTES oamcoord_085
	.HIBYTES oamcoord_086
	.HIBYTES oamcoord_087
	.HIBYTES oamcoord_088
	.HIBYTES oamcoord_089
	.HIBYTES oamcoord_08a
	.HIBYTES oamcoord_08b
	.HIBYTES oamcoord_08c
	.HIBYTES oamcoord_08d
	.HIBYTES oamcoord_08e
	.HIBYTES oamcoord_08f
	.HIBYTES oamcoord_090
	.HIBYTES oamcoord_091
	.HIBYTES oamcoord_092
	.HIBYTES oamcoord_093
	.HIBYTES oamcoord_094
	.HIBYTES oamcoord_095
	.HIBYTES oamcoord_096
	.HIBYTES oamcoord_097
	.HIBYTES oamcoord_098
	.HIBYTES oamcoord_099
	.HIBYTES oamcoord_09a
	.HIBYTES oamcoord_09b
	.HIBYTES oamcoord_09c
	.HIBYTES oamcoord_09d
	.HIBYTES oamcoord_09e
	.HIBYTES oamcoord_09f
	.HIBYTES oamcoord_0a0
	.HIBYTES oamcoord_0a1
	.HIBYTES oamcoord_0a2
	.HIBYTES oamcoord_0a3
	.HIBYTES oamcoord_0a4
	.HIBYTES oamcoord_0a5
	.HIBYTES oamcoord_0a6
	.HIBYTES oamcoord_0a7
	.HIBYTES oamcoord_0a8
	.HIBYTES oamcoord_0a9
	.HIBYTES oamcoord_0aa
	.HIBYTES oamcoord_0ab
	.HIBYTES oamcoord_0ac
	.HIBYTES oamcoord_0ad
	.HIBYTES oamcoord_0ae
	.HIBYTES oamcoord_0af
	.HIBYTES oamcoord_0b0
	.HIBYTES oamcoord_0b1
	.HIBYTES oamcoord_0b2
	.HIBYTES oamcoord_0b3
	.HIBYTES oamcoord_0b4
	.HIBYTES oamcoord_0b5
	.HIBYTES oamcoord_0b6
	.HIBYTES oamcoord_0b7
	.HIBYTES oamcoord_0b8
	.HIBYTES oamcoord_0b9
	.HIBYTES oamcoord_0ba
	.HIBYTES oamcoord_0bb
	.HIBYTES oamcoord_0bc
	.HIBYTES oamcoord_0bd
	.HIBYTES oamcoord_0be
	.HIBYTES oamcoord_0bf
	.HIBYTES oamcoord_0c0
	.HIBYTES oamcoord_0c1
	.HIBYTES oamcoord_0c2
	.HIBYTES oamcoord_0c3
	.HIBYTES oamcoord_0c4
	.HIBYTES oamcoord_0c5
	.HIBYTES oamcoord_0c6
	.HIBYTES oamcoord_0c7
	.HIBYTES oamcoord_0c8
	.HIBYTES oamcoord_0c9
	.HIBYTES oamcoord_0ca
	.HIBYTES oamcoord_0cb
	.HIBYTES oamcoord_0cc
	.HIBYTES oamcoord_0cd
	.HIBYTES oamcoord_0ce
	.HIBYTES oamcoord_0cf
	.HIBYTES oamcoord_0d0
	.HIBYTES oamcoord_0d1
	.HIBYTES oamcoord_0d2
	.HIBYTES oamcoord_0d3
	.HIBYTES oamcoord_0d4
	.HIBYTES oamcoord_0d5
	.HIBYTES oamcoord_0d6
	.HIBYTES oamcoord_0d7
	.HIBYTES oamcoord_0d8
	.HIBYTES oamcoord_0d9
	.HIBYTES oamcoord_0da
	.HIBYTES oamcoord_0db
	.HIBYTES oamcoord_0dc
	.HIBYTES oamcoord_0dd
	.HIBYTES oamcoord_0de
	.HIBYTES oamcoord_0df
	.HIBYTES oamcoord_0e0
	.HIBYTES oamcoord_0e1
	.HIBYTES oamcoord_0e2
	.HIBYTES oamcoord_0e3
	.HIBYTES oamcoord_0e4
	.HIBYTES oamcoord_0e5
	.HIBYTES oamcoord_0e6
	.HIBYTES oamcoord_0e7
	.HIBYTES oamcoord_0e8
	.HIBYTES oamcoord_0e9
	.HIBYTES oamcoord_0ea
	.HIBYTES oamcoord_0eb
	.HIBYTES oamcoord_0ec
	.HIBYTES oamcoord_0ed
	.HIBYTES oamcoord_0ee
	.HIBYTES oamcoord_0ef
	.HIBYTES oamcoord_0f0
	.HIBYTES oamcoord_0f1
	.HIBYTES oamcoord_0f2
	.HIBYTES oamcoord_0f3
	.HIBYTES oamcoord_0f4
	.HIBYTES oamcoord_0f5
	.HIBYTES oamcoord_0f6
	.HIBYTES oamcoord_0f7
	.HIBYTES oamcoord_0f8
	.HIBYTES oamcoord_0f9
	.HIBYTES oamcoord_0fa
	.HIBYTES oamcoord_0fb
	.HIBYTES oamcoord_0fc
	.HIBYTES oamcoord_0fd
	.HIBYTES oamcoord_0fe
	.HIBYTES oamcoord_0ff
